### DISCUSSION TITLE
使用中英文训练模型报内存溢出,使用ch_PP-OCRv3_rec.yml配置文件开启训练

### DISCUSSION THREAD

**Discussion by sssjc666** [PaddlePaddle/PaddleOCR#12997] [Q&A] [answered]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem
该模型之前在4g显存上正常运行过，现在换了一个电脑想试一下8g运存发现无法启动训练。模型选用ocr官网上公布pp-ocrv3中英文训练模型，数据为自己的数据，batch_size设置为1时，也无法启动训练。希望大佬回复！
- 系统环境/System Environment：win11
- 版本号/Version：Paddle：2.5.1  PaddleOCR：2.7.0.2 问题相关组件/Related components：paddleocr
- 运行指令/Command Code：python tools/train.py -c configs/rec/PP-OCRv3/ch_PP-OCRv3_rec_distillation.yml -o Global.pretrained_model=./pretrained_model/ch_PP-OCRv3_rec_train/best_accuracy
- 
- 完整报错/Complete Error Message：
MemoryError:

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
Not support stack backtrace yet.

----------------------
Error Message Summary:
----------------------
ResourceExhaustedError:

Out of memory error on GPU 0. Cannot allocate 128.000000MB memory on GPU 0, 7.995605GB memory has been allocated and available memory is only 0.000000B.

Please check whether there is any other process using GPU 0.
1. If yes, please stop them, or start PaddlePaddle on another GPU.
2. If no, please decrease the batch size of your model.
 (at ..\paddle\fluid\memory\allocation\cuda_allocator.cc:86)

![image](https://github.com/PaddlePaddle/PaddleOCR/assets/126962940/b27eac48-b977-40aa-bcf9-7b0e8a564936)

我们提供了AceIssueSolver来帮助你解答问题，你是否想要它来解答(请填写yes/no)?/We provide AceIssueSolver to solve issues, do you want it? (Please write yes/no):

请尽量不要包含图片在问题中/Please try to not include the image in the issue.

**Comment by sssjc666** [comment]
配置详情如下：
![image](https://github.com/PaddlePaddle/PaddleOCR/assets/126962940/d1946e72-744b-45f7-b57f-45cf58ceb3c2)
![3785957da89825ecf5c5ffe4bb72c8e](https://github.com/PaddlePaddle/PaddleOCR/assets/126962940/1ea31c72-e634-4be2-ac2b-2b3d85fc004e)
![32212f622923952a044781e54276905](https://github.com/PaddlePaddle/PaddleOCR/assets/126962940/8f2d2e57-451a-4a26-8c9f-807ba3d6b1c3)
希望大佬回复！

**Comment by sssjc666** [comment]
已经解决

**Comment by sssjc666** [comment, marked as answer]
当时可能是环境出现问题了，对ocr库进行了一次重装，再次进行训练就能正常启动。ps：使用paddle不建议win11进行练习，我遇见好几次包的问题了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleOCR"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年11月20日(星期一) 中午11:24
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleOCR] 使用中英文训练模型报内存溢出,使用ch_PP-OCRv3_rec.yml配置文件开启训练 (Issue #11266)





 
请问怎么解决的呢
