### ISSUE TITLE
推理时报cuda编译器错误

### ISSUE THREAD

**Issue by liangyming** [PaddlePaddle/PaddleOCR#10686]
- 系统环境/System Environment：Ubuntu20.04
- 报错信息如下：
```bash
(nlp) liangym@stresstest:~/PaddleOCR$ bash infer.sh 
Traceback (most recent call last):
  File "tools/infer/predict_rec.py", line 667, in <module>
    main(utility.parse_args())
  File "tools/infer/predict_rec.py", line 629, in main
    text_recognizer = TextRecognizer(args)
  File "tools/infer/predict_rec.py", line 120, in __init__
    utility.create_predictor(args, 'rec', logger)
  File "/home/liangym/PaddleOCR/tools/infer/utility.py", line 278, in create_predictor
    predictor = inference.create_predictor(config)
OSError: (External) CUDA error(222), the provided PTX was compiled with an unsupported toolchain.. 
  [Hint: 'cudaErrorUnsupportedPtxVersion'. This indicates that the provided PTX was compiled with an unsupported toolchain. The most common reason for this, is the PTXwas generated by a compiler newer than what is supported by the CUDA driver and PTX JIT compiler.] (at ../paddle/fluid/platform/device/gpu/gpu_info.cc:124)
```
- 我的cuda版本相关信息如下：
```bash
(base) liangym@stresstest:~$ nvidia-smi
Mon Aug 21 15:05:10 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 510.47.03    Driver Version: 510.47.03    CUDA Version: 11.6     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
```
```bash
(nlp) liangym@stresstest:~/PaddleOCR$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Sun_Feb_14_21:12:58_PST_2021
Cuda compilation tools, release 11.2, V11.2.152
Build cuda_11.2.r11.2/compiler.29618528_0
```

**Comment by YuanLiuuuuuu** [comment]
> * 系统环境/System Environment：Ubuntu20.04
> * 报错信息如下：
> 
> ```shell
> (nlp) liangym@stresstest:~/PaddleOCR$ bash infer.sh 
> Traceback (most recent call last):
>   File "tools/infer/predict_rec.py", line 667, in <module>
>     main(utility.parse_args())
>   File "tools/infer/predict_rec.py", line 629, in main
>     text_recognizer = TextRecognizer(args)
>   File "tools/infer/predict_rec.py", line 120, in __init__
>     utility.create_predictor(args, 'rec', logger)
>   File "/home/liangym/PaddleOCR/tools/infer/utility.py", line 278, in create_predictor
>     predictor = inference.create_predictor(config)
> OSError: (External) CUDA error(222), the provided PTX was compiled with an unsupported toolchain.. 
>   [Hint: 'cudaErrorUnsupportedPtxVersion'. This indicates that the provided PTX was compiled with an unsupported toolchain. The most common reason for this, is the PTXwas generated by a compiler newer than what is supported by the CUDA driver and PTX JIT compiler.] (at ../paddle/fluid/platform/device/gpu/gpu_info.cc:124)
> ```
> 
> * 我的cuda版本相关信息如下：
> 
> ```shell
> (base) liangym@stresstest:~$ nvidia-smi
> Mon Aug 21 15:05:10 2023       
> +-----------------------------------------------------------------------------+
> | NVIDIA-SMI 510.47.03    Driver Version: 510.47.03    CUDA Version: 11.6     |
> |-------------------------------+----------------------+----------------------+
> | GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
> | Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
> |                               |                      |               MIG M. |
> |===============================+======================+======================|
> ```
> 
> ```shell
> (nlp) liangym@stresstest:~/PaddleOCR$ nvcc --version
> nvcc: NVIDIA (R) Cuda compiler driver
> Copyright (c) 2005-2021 NVIDIA Corporation
> Built on Sun_Feb_14_21:12:58_PST_2021
> Cuda compilation tools, release 11.2, V11.2.152
> Build cuda_11.2.r11.2/compiler.29618528_0
> ```

Have you solved it? I also facing the same error.

**Comment by wxj127** [comment]
CUDA error(222), the provided PTX was compiled with an unsupported toolchain..
  [Hint: 'cudaErrorUnsupportedPtxVersion'. This indicates that the provided PTX was compiled with an unsupported toolchain. The most common reason for this, is the PTXwas generated by a compiler newer than what is supportedby the CUDA driver and PTX JIT compiler.] (at ../paddle/fluid/platform/device/gpu/gpu_info.cc:124)

**Comment by wxj127** [comment]
CUDA error(222), the provided PTX was compiled with an unsupported toolchain..
  [Hint: 'cudaErrorUnsupportedPtxVersion'. This indicates that the provided PTX was compiled with an unsupported toolchain. The most common reason for this, is the PTXwas generated by a compiler newer than what is supportedby the CUDA driver and PTX JIT compiler.] (at ../paddle/fluid/platform/device/gpu/gpu_info.cc:124)

**Comment by wxj127** [comment]
我在 执行ocr 的 时候 报错 ，这是我的cuda信息
![image](https://github.com/PaddlePaddle/PaddleOCR/assets/65206810/5b35dca7-b62b-4d53-96bc-bcaff5ee90ae)

**Comment by vviettinh** [comment]
i create new env conda: python3.10
and install : 
+ pip install paddlepaddle-gpu==2.5.1.post116 -f https://www.paddlepaddle.org.cn/whl/linux/mkl/avx/stable.html      in https://aistudio.baidu.com/projectdetail/6611435 
+ pip install "paddleocr>=2.0.1"

And it worked

**Comment by wangqiang9** [comment]
`pip install paddlepaddle-gpu==2.5.0`
