### ISSUE TITLE
paddler 2.7.0.3, paddlepaddle-gpu 2.5.1, ModuleNotFoundError: No module named 'paddle.distributed'

### ISSUE THREAD

**Issue by RedNoseJJN** [PaddlePaddle/PaddleOCR#10953]
hi guys,
I'm now trying to run my python code on linux with gpu, and I import paddleocr in my project.
But when I try to run it, error shows like below:

> Traceback (most recent call last):
  File "/home/ji/test/app.py", line 5, in <module>
    import paddleocr
  File "/home/ji/test/venv/lib/python3.10/site-packages/paddleocr/__init__.py", line 14, in <module>
    from .paddleocr import *
  File "/home/ji/test/venv/lib/python3.10/site-packages/paddleocr/paddleocr.py", line 47, in <module>
    from ppocr.utils.logging import get_logger
  File "/home/ji/test/venv/lib/python3.10/site-packages/paddleocr/ppocr/utils/logging.py", line 23, in <module>
    import paddle.distributed as dist
ModuleNotFoundError: No module named 'paddle.distributed'

What is more interesting is that, few days before, i'm actually using paddlepaddle 2.5.1 instead of paddlpaddle-gpu 2.5.1. After my mentor argued me why not using the gpu version, i uninstalled the paddlepaddle, and the exception occurred. So i'm wondering what can I do to fix this. Dose this mean the paddleocr have to run based on paddlepaddle cpu version? Thx.

**Comment by RedNoseJJN** [comment]
no body answers, but I now fix it, (though don't know how).
I will close this issue.

**Comment by zhangqiqi1228** [comment]
> no body answers, but I now fix it, (though don't know how). I will close this issue.

I faced with the same problem and I have figured out the solution. 
After uninstalling the CPU version, you may need to re-install the GPU version, although you have already installed the GPU version.

**Comment by njauwhr** [comment]
> no body answers, but I now fix it, (though don't know how). I will close this issue.

How did you fix this problem? I also encountered it on my computer
