### ISSUE TITLE
win10系统下python使用GPU推理可能存在显存爆炸的情况

### ISSUE THREAD

**Issue by ChenZhiweiYC96** [PaddlePaddle/PaddleOCR#1102]
# 系统
win10专业版1909
# 语言
python
# CPU
i7 9700
# GPU
2080Ti
# package版本
paddleocr 1.0.1
paddlepaddle 2.0.0rc0/2.0.0b0/1.8.5
CUDA 10.0/10.1
cudnn 7.6.5

# 代码
```
# 模型存放目录
det_full_model_dir = './Tool/inference_model/ch_ppocr_server_v1.1_det_infer/'
rec_full_model_dir = './Tool/inference_model/ch_ppocr_server_v1.1_rec_infer/'

ocr_full = PaddleOCR(
                det_model_dir=det_full_model_dir,
                rec_model_dir=rec_full_model_dir,
                det_max_side_len=750,
                use_gpu=True,
                )
                      
for file_num in range(len(file_list)):
    file_path = file_list[file_num]
    print(file_path)
    # 图片序号
    num = int(file_path[-6:-4])
    result = ocr_full.ocr(file_path)
    text_str_list = []
    for line in result:
        text_str_list.append(line[1][0])

    text_str = '\n'.join(text_str_list)
    with open(Target_filepath+'pic_full_%02d.txt'%num, 'w', encoding='UTF-8', errors='ignore') as f_out:
        f_out.write(text_str)
    # 延时1秒，可以看到显存阶梯式上升，从未下降
    time.sleep(1)
```

# 报错
```
RuntimeError:

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
Not support stack backtrace yet.

----------------------
Error Message Summary:
----------------------
ResourceExhaustedError:

Out of memory error on GPU 0. Cannot allocate 106.144287MB memory on GPU 0, available memory is only 95.565234MB.

Please check whether there is any other process using GPU 0.
1. If yes, please stop them, or start PaddlePaddle on another GPU.
2. If no, please decrease the batch size of your model.

 (at D:\2.0.0-rc0\paddle\paddle\fluid\memory\allocation\cuda_allocator.cc:69)
```

**Comment by tsj123lll** [comment]
我也出现了这个问题，求解决
在自己的电脑上跑 4G显存
RuntimeError: 

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
Windows not support stack backtrace yet.

----------------------
Error Message Summary:
----------------------
ResourceExhaustedError: 

Out of memory error on GPU 0. Cannot allocate 52.617432MB memory on GPU 0, available memory is only 51.075000MB.

Please check whether there is any other process using GPU 0.
1. If yes, please stop them, or start PaddlePaddle on another GPU.
2. If no, please try one of the following suggestions:
   1) Decrease the batch size of your model.
   2) FLAGS_fraction_of_gpu_memory_to_use is 0.50 now, please set it to a higher value but less than 1.0.
      The command is `export FLAGS_fraction_of_gpu_memory_to_use=xxx`.

 at (D:\1.7.2\paddle\paddle\fluid\memory\detail\system_allocator.cc:150)

E1104 19:34:39.485221   776 analysis_predictor.cc:484] Allocate too much memory for the GPU memory pool, assigned 8000 MB
E1104 19:34:39.485221   776 analysis_predictor.cc:487] Try to shink the value by setting AnalysisConfig::EnableGpu(...)
E1104 19:34:40.204434   776 analysis_predictor.cc:484] Allocate too much memory for the GPU memory pool, assigned 8000 MB
E1104 19:34:40.204434   776 analysis_predictor.cc:487] Try to shink the value by setting AnalysisConfig::EnableGpu(...)

Process finished with exit code 1


在实验室用2070跑 有时候可以跑 有时候出现显存爆了的情况
另：是否需要显存8G以上才行

**Comment by ChenZhiweiYC96** [comment]
> 我也出现了这个问题，求解决
> 在自己的电脑上跑 4G显存
> RuntimeError:
> 
> ## C++ Call Stacks (More useful to developers):
> Windows not support stack backtrace yet.
> 
> ## Error Message Summary:
> ResourceExhaustedError:
> 
> Out of memory error on GPU 0. Cannot allocate 52.617432MB memory on GPU 0, available memory is only 51.075000MB.
> 
> Please check whether there is any other process using GPU 0.
> 
> 1. If yes, please stop them, or start PaddlePaddle on another GPU.
> 2. If no, please try one of the following suggestions:
>    
>    1. Decrease the batch size of your model.
>    2. FLAGS_fraction_of_gpu_memory_to_use is 0.50 now, please set it to a higher value but less than 1.0.
>       The command is `export FLAGS_fraction_of_gpu_memory_to_use=xxx`.
> 
> at (D:\1.7.2\paddle\paddle\fluid\memory\detail\system_allocator.cc:150)
> 
> E1104 19:34:39.485221 776 analysis_predictor.cc:484] Allocate too much memory for the GPU memory pool, assigned 8000 MB
> E1104 19:34:39.485221 776 analysis_predictor.cc:487] Try to shink the value by setting AnalysisConfig::EnableGpu(...)
> E1104 19:34:40.204434 776 analysis_predictor.cc:484] Allocate too much memory for the GPU memory pool, assigned 8000 MB
> E1104 19:34:40.204434 776 analysis_predictor.cc:487] Try to shink the value by setting AnalysisConfig::EnableGpu(...)
> 
> Process finished with exit code 1
> 
> 在实验室用2070跑 有时候可以跑 有时候出现显存爆了的情况
> 另：是否需要显存8G以上才行

据说是paddlepaddle2.0正式版会解决，期待一下吧。着急的话可以换Linux系统，我之前在colab上跑了一下，是没这个问题的。
不一定显存得8G以上，看需求，如果图片大、文字密的话，8G也不一定够。

**Comment by tsj123lll** [comment]
> > 我也出现了这个问题，求解决
> > 在自己的电脑上跑 4G显存
> > RuntimeError:
> > ## C++ Call Stacks (More useful to developers):
> > Windows not support stack backtrace yet.
> > ## Error Message Summary:
> > ResourceExhaustedError:
> > Out of memory error on GPU 0. Cannot allocate 52.617432MB memory on GPU 0, available memory is only 51.075000MB.
> > Please check whether there is any other process using GPU 0.
> > 
> > 1. If yes, please stop them, or start PaddlePaddle on another GPU.
> > 2. If no, please try one of the following suggestions:
> >    
> >    1. Decrease the batch size of your model.
> >    2. FLAGS_fraction_of_gpu_memory_to_use is 0.50 now, please set it to a higher value but less than 1.0.
> >       The command is `export FLAGS_fraction_of_gpu_memory_to_use=xxx`.
> > 
> > at (D:\1.7.2\paddle\paddle\fluid\memory\detail\system_allocator.cc:150)
> > E1104 19:34:39.485221 776 analysis_predictor.cc:484] Allocate too much memory for the GPU memory pool, assigned 8000 MB
> > E1104 19:34:39.485221 776 analysis_predictor.cc:487] Try to shink the value by setting AnalysisConfig::EnableGpu(...)
> > E1104 19:34:40.204434 776 analysis_predictor.cc:484] Allocate too much memory for the GPU memory pool, assigned 8000 MB
> > E1104 19:34:40.204434 776 analysis_predictor.cc:487] Try to shink the value by setting AnalysisConfig::EnableGpu(...)
> > Process finished with exit code 1
> > 在实验室用2070跑 有时候可以跑 有时候出现显存爆了的情况
> > 另：是否需要显存8G以上才行
> 
> 据说是paddlepaddle2.0正式版会解决，期待一下吧。着急的话可以换Linux系统，我之前在colab上跑了一下，是没这个问题的。
> 不一定显存得8G以上，看需求，如果图片大、文字密的话，8G也不一定够。

我这边直接电脑跑也跑不起来 我一运行就直接报错了 我看他最后一行意思好像是说要8G  我这边小于显存4G可以跑起来吗 在WINDOWS下

**Comment by ChenZhiweiYC96** [comment]
> > > 我也出现了这个问题，求解决
> > > 在自己的电脑上跑 4G显存
> > > RuntimeError:
> > > ## C++ Call Stacks (More useful to developers):
> > > Windows not support stack backtrace yet.
> > > ## Error Message Summary:
> > > ResourceExhaustedError:
> > > Out of memory error on GPU 0. Cannot allocate 52.617432MB memory on GPU 0, available memory is only 51.075000MB.
> > > Please check whether there is any other process using GPU 0.
> > > 
> > > 1. If yes, please stop them, or start PaddlePaddle on another GPU.
> > > 2. If no, please try one of the following suggestions:
> > >    
> > >    1. Decrease the batch size of your model.
> > >    2. FLAGS_fraction_of_gpu_memory_to_use is 0.50 now, please set it to a higher value but less than 1.0.
> > >       The command is `export FLAGS_fraction_of_gpu_memory_to_use=xxx`.
> > > 
> > > at (D:\1.7.2\paddle\paddle\fluid\memory\detail\system_allocator.cc:150)
> > > E1104 19:34:39.485221 776 analysis_predictor.cc:484] Allocate too much memory for the GPU memory pool, assigned 8000 MB
> > > E1104 19:34:39.485221 776 analysis_predictor.cc:487] Try to shink the value by setting AnalysisConfig::EnableGpu(...)
> > > E1104 19:34:40.204434 776 analysis_predictor.cc:484] Allocate too much memory for the GPU memory pool, assigned 8000 MB
> > > E1104 19:34:40.204434 776 analysis_predictor.cc:487] Try to shink the value by setting AnalysisConfig::EnableGpu(...)
> > > Process finished with exit code 1
> > > 在实验室用2070跑 有时候可以跑 有时候出现显存爆了的情况
> > > 另：是否需要显存8G以上才行
> > 
> > 
> > 据说是paddlepaddle2.0正式版会解决，期待一下吧。着急的话可以换Linux系统，我之前在colab上跑了一下，是没这个问题的。
> > 不一定显存得8G以上，看需求，如果图片大、文字密的话，8G也不一定够。
> 
> 我这边直接电脑跑也跑不起来 我一运行就直接报错了 我看他最后一行意思好像是说要8G 我这边小于显存4G可以跑起来吗 在WINDOWS下

那个8000M是一个参数，如果显卡没有其他计算任务占用的话，可以设置为整个显存的实际大小

**Comment by tsj123lll** [comment]
> > > > 我也出现了这个问题，求解决
> > > > 在自己的电脑上跑 4G显存
> > > > RuntimeError:
> > > > ## C++ Call Stacks (More useful to developers):
> > > > Windows not support stack backtrace yet.
> > > > ## Error Message Summary:
> > > > ResourceExhaustedError:
> > > > Out of memory error on GPU 0. Cannot allocate 52.617432MB memory on GPU 0, available memory is only 51.075000MB.
> > > > Please check whether there is any other process using GPU 0.
> > > > 
> > > > 1. If yes, please stop them, or start PaddlePaddle on another GPU.
> > > > 2. If no, please try one of the following suggestions:
> > > >    
> > > >    1. Decrease the batch size of your model.
> > > >    2. FLAGS_fraction_of_gpu_memory_to_use is 0.50 now, please set it to a higher value but less than 1.0.
> > > >       The command is `export FLAGS_fraction_of_gpu_memory_to_use=xxx`.
> > > > 
> > > > at (D:\1.7.2\paddle\paddle\fluid\memory\detail\system_allocator.cc:150)
> > > > E1104 19:34:39.485221 776 analysis_predictor.cc:484] Allocate too much memory for the GPU memory pool, assigned 8000 MB
> > > > E1104 19:34:39.485221 776 analysis_predictor.cc:487] Try to shink the value by setting AnalysisConfig::EnableGpu(...)
> > > > E1104 19:34:40.204434 776 analysis_predictor.cc:484] Allocate too much memory for the GPU memory pool, assigned 8000 MB
> > > > E1104 19:34:40.204434 776 analysis_predictor.cc:487] Try to shink the value by setting AnalysisConfig::EnableGpu(...)
> > > > Process finished with exit code 1
> > > > 在实验室用2070跑 有时候可以跑 有时候出现显存爆了的情况
> > > > 另：是否需要显存8G以上才行
> > > 
> > > 
> > > 据说是paddlepaddle2.0正式版会解决，期待一下吧。着急的话可以换Linux系统，我之前在colab上跑了一下，是没这个问题的。
> > > 不一定显存得8G以上，看需求，如果图片大、文字密的话，8G也不一定够。
> > 
> > 
> > 我这边直接电脑跑也跑不起来 我一运行就直接报错了 我看他最后一行意思好像是说要8G 我这边小于显存4G可以跑起来吗 在WINDOWS下
> 
> 那个8000M是一个参数，如果显卡没有其他计算任务占用的话，可以设置为整个显存的实际大小

哦哦好的 那GPU2.0版大概啥时候可以出来哦  我看CPU的2.0版是可以下载的 GPU的2.0版好像还不行

**Comment by ChenZhiweiYC96** [comment]
> > > > > 我也出现了这个问题，求解决
> > > > > 在自己的电脑上跑 4G显存
> > > > > RuntimeError:
> > > > > ## C++ Call Stacks (More useful to developers):
> > > > > Windows not support stack backtrace yet.
> > > > > ## Error Message Summary:
> > > > > ResourceExhaustedError:
> > > > > Out of memory error on GPU 0. Cannot allocate 52.617432MB memory on GPU 0, available memory is only 51.075000MB.
> > > > > Please check whether there is any other process using GPU 0.
> > > > > 
> > > > > 1. If yes, please stop them, or start PaddlePaddle on another GPU.
> > > > > 2. If no, please try one of the following suggestions:
> > > > >    
> > > > >    1. Decrease the batch size of your model.
> > > > >    2. FLAGS_fraction_of_gpu_memory_to_use is 0.50 now, please set it to a higher value but less than 1.0.
> > > > >       The command is `export FLAGS_fraction_of_gpu_memory_to_use=xxx`.
> > > > > 
> > > > > at (D:\1.7.2\paddle\paddle\fluid\memory\detail\system_allocator.cc:150)
> > > > > E1104 19:34:39.485221 776 analysis_predictor.cc:484] Allocate too much memory for the GPU memory pool, assigned 8000 MB
> > > > > E1104 19:34:39.485221 776 analysis_predictor.cc:487] Try to shink the value by setting AnalysisConfig::EnableGpu(...)
> > > > > E1104 19:34:40.204434 776 analysis_predictor.cc:484] Allocate too much memory for the GPU memory pool, assigned 8000 MB
> > > > > E1104 19:34:40.204434 776 analysis_predictor.cc:487] Try to shink the value by setting AnalysisConfig::EnableGpu(...)
> > > > > Process finished with exit code 1
> > > > > 在实验室用2070跑 有时候可以跑 有时候出现显存爆了的情况
> > > > > 另：是否需要显存8G以上才行
> > > > 
> > > > 
> > > > 据说是paddlepaddle2.0正式版会解决，期待一下吧。着急的话可以换Linux系统，我之前在colab上跑了一下，是没这个问题的。
> > > > 不一定显存得8G以上，看需求，如果图片大、文字密的话，8G也不一定够。
> > > 
> > > 
> > > 我这边直接电脑跑也跑不起来 我一运行就直接报错了 我看他最后一行意思好像是说要8G 我这边小于显存4G可以跑起来吗 在WINDOWS下
> > 
> > 
> > 那个8000M是一个参数，如果显卡没有其他计算任务占用的话，可以设置为整个显存的实际大小
> 
> 哦哦好的 那GPU2.0版大概啥时候可以出来哦 我看CPU的2.0版是可以下载的 GPU的2.0版好像还不行

我也不是很清楚呀，我也蛮急着用这个的，因为精度确实高，不愿意换别的工具了

**Comment by BeyondYourself** [comment]
建议根据实际的gpu的men调整一下paddleocr.py中这个参数gpu_men：
![image](https://user-images.githubusercontent.com/12640462/98186668-3dcfc680-1f4a-11eb-88a3-1690c5d9053d.png)

**Comment by ChenZhiweiYC96** [comment]
> > > > > 我也出现了这个问题，求解决
> > > > > 在自己的电脑上跑 4G显存
> > > > > RuntimeError:
> > > > > ## C++ Call Stacks (More useful to developers):
> > > > > Windows not support stack backtrace yet.
> > > > > ## Error Message Summary:
> > > > > ResourceExhaustedError:
> > > > > Out of memory error on GPU 0. Cannot allocate 52.617432MB memory on GPU 0, available memory is only 51.075000MB.
> > > > > Please check whether there is any other process using GPU 0.
> > > > > 
> > > > > 1. If yes, please stop them, or start PaddlePaddle on another GPU.
> > > > > 2. If no, please try one of the following suggestions:
> > > > >    
> > > > >    1. Decrease the batch size of your model.
> > > > >    2. FLAGS_fraction_of_gpu_memory_to_use is 0.50 now, please set it to a higher value but less than 1.0.
> > > > >       The command is `export FLAGS_fraction_of_gpu_memory_to_use=xxx`.
> > > > > 
> > > > > at (D:\1.7.2\paddle\paddle\fluid\memory\detail\system_allocator.cc:150)
> > > > > E1104 19:34:39.485221 776 analysis_predictor.cc:484] Allocate too much memory for the GPU memory pool, assigned 8000 MB
> > > > > E1104 19:34:39.485221 776 analysis_predictor.cc:487] Try to shink the value by setting AnalysisConfig::EnableGpu(...)
> > > > > E1104 19:34:40.204434 776 analysis_predictor.cc:484] Allocate too much memory for the GPU memory pool, assigned 8000 MB
> > > > > E1104 19:34:40.204434 776 analysis_predictor.cc:487] Try to shink the value by setting AnalysisConfig::EnableGpu(...)
> > > > > Process finished with exit code 1
> > > > > 在实验室用2070跑 有时候可以跑 有时候出现显存爆了的情况
> > > > > 另：是否需要显存8G以上才行
> > > > 
> > > > 
> > > > 据说是paddlepaddle2.0正式版会解决，期待一下吧。着急的话可以换Linux系统，我之前在colab上跑了一下，是没这个问题的。
> > > > 不一定显存得8G以上，看需求，如果图片大、文字密的话，8G也不一定够。
> > > 
> > > 
> > > 我这边直接电脑跑也跑不起来 我一运行就直接报错了 我看他最后一行意思好像是说要8G 我这边小于显存4G可以跑起来吗 在WINDOWS下
> > 
> > 
> > 那个8000M是一个参数，如果显卡没有其他计算任务占用的话，可以设置为整个显存的实际大小
> 
> 哦哦好的 那GPU2.0版大概啥时候可以出来哦 我看CPU的2.0版是可以下载的 GPU的2.0版好像还不行

目前有一个方法，修改几个参数：
```
# 默认为6
# 降低batch的数量，一次性读入显存的图片数量减少
rec_batch_num=3

# 默认960
# 图片过大可以适当降低长边的像素数
# 如果文字过小可以适当提高这个参数，和rec_batch_num配合起来用，图片越大，rec_batch_num就需要小一些
det_max_side_len=1100

# 密集文字如果检测精度不够，可以降低这个阈值，阈值越低，灵敏度越高
# 不必通过提高图片大小来提升精度，降低阈值也可以提高精度
det_db_box_thresh=0.05
```

通过以上三个参数的配合调整，爆显存的问题基本可以解决了

**Comment by lvguangtao** [comment]
> 建议根据实际的gpu的men调整一下paddleocr.py中这个参数gpu_men：
> ![image](https://user-images.githubusercontent.com/12640462/98186668-3dcfc680-1f4a-11eb-88a3-1690c5d9053d.png)

我的6G显存，设置5G还是会有问题。直接断开了。

**Comment by BeyondYourself** [comment]
之前在Tesla v100上测试，batch_size设置为10就会崩了。感觉这方面还有待优化一下。batch_size一般设置为5左右不会出现崩溃的现象。

**Comment by EricJi001** [comment]
> > 建议根据实际的gpu的men调整一下paddleocr.py中这个参数gpu_men： ![image](https://user-images.githubusercontent.com/12640462/98186668-3dcfc680-1f4a-11eb-88a3-1690c5d9053d.png)
> 
> paddleocr.py里没看到gpu_mem这个参数了

自己加上该行即可
parser.add_argument("--gpu_mem", type=int, default=8000)
