### ISSUE TITLE
OCR连续识别，显存不释放

### ISSUE THREAD

**Issue by zhh8689** [PaddlePaddle/PaddleOCR#11384]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
linux , python3.8.1 , cuda 11.2, A100

- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：

paddlepaddle 2.5.2
paddleocr 2.7.0.3

- 运行指令/Command Code：

from paddleocr import PaddleOCR
ocr = PaddleOCR( lang="ch")
for item in files:
ocr.ocr(item)

在使用GPU，CUDA11.2的设备上，循环进行ocr推理，显存一直上涨，最后爆掉
使用paddle.device.cuda.empty_cache()，显存会有下降，但是实际显存还是在上涨，最后依然会爆掉

- 完整报错/Complete Error Message：

最后报错是显存不足，无法分配空间。杀掉进程后，显存全部释放。
OCR在识别比较多文字的情况下，100张图片左右，16G显存会爆掉
使用paddle.device.cuda.empty_cache()，大概能处理200张左右爆掉

**Comment by gaojuntian** [comment]
请问解决了吗

**Comment by Aunixtoyou** [comment]
我去16G都撑不住，我这2G干脆仍垃圾桶算了。
每次新的图片显存都涨，就是不释放，最多4张图片就g了，离大普了

**Comment by plusboy88** [comment]
是的 我的V100 32GB都扛不住  一个模型占了15GB显存  就算不调用的 显存也一直占着。希望工程师看到能够解答一下  感谢开源项目的奉献 谢谢

**Comment by zhh8689** [comment]
> 我去16G都撑不住，我这2G干脆仍垃圾桶算了。 每次新的图片显存都涨，就是不释放，最多4张图片就g了，离大普了

CPU推理没啥问题，主要问题集中在使用gpu推理的rec模型上面。serving_server的方式目前来看，虽然分配的显存很大，但是不爆显存，使用工具包就不行了

**Comment by zhh8689** [comment]
> 是的 我的V100 32GB都扛不住 一个模型占了15GB显存 就算不调用的 显存也一直占着。希望工程师看到能够解答一下 感谢开源项目的奉献 谢谢

我翻paddle的api跟阅读源码，发现显存泄露发生在paddle的predictor里面。但是没具体阅读paddle框架里面的内容。从paddle的api文档里面，找到了predictor.try_shrink_memory这个方法，使用这个方法可以释放使用后的tensor，但是目前来看，不知道什么原因，会发生有部分图片直接推理就会占满显存。时而发生时而不发生，比较迷惑

**Comment by xixihahaliu** [comment]
所以这个问题现在要怎么解决呀，辛苦大佬了

**Comment by f497196689** [comment]
> > 是的 我的V100 32GB都扛不住 一个模型占了15GB显存 就算不调用的 显存也一直占着。希望工程师看到能够解答一下 感谢开源项目的奉献 谢谢
> 
> 我翻paddle的api跟阅读源码，发现显存泄露发生在paddle的predictor里面。但是没具体阅读paddle框架里面的内容。从paddle的api文档里面，找到了predictor.try_shrink_memory这个方法，使用这个方法可以释放使用后的tensor，但是目前来看，不知道什么原因，会发生有部分图片直接推理就会占满显存。时而发生时而不发生，比较迷惑

在 执行 ocr.ocr(image_path, cls=True) 方法之后执行 paddle.inference.Predictor.try_shrink_memory() 方法会报错，报错信息如下

try_shrink_memory(): incompatible function arguments. The following argument types are supported:
    1. (self: paddle.fluid.libpaddle.PaddleInferPredictor) -> int

**Comment by chopin1998** [comment]
我也想知道， 当想如何正确“关闭”一个ocr对象。。。。 try_shrink_memory()  和上面的兄弟一样的错

**Comment by gaojuntian** [comment]
我将batch调整为1后，显存固定在1390M

**Comment by perrywu1989** [comment]
> 我将batch调整为1后，显存固定在1390M

请问是调整的rec的batch为1吗

**Comment by gaojuntian** [comment]
> > 我将批量调整为1后，显存固定在1390M
> 
> 请问调整的rec的batch为1吗？
嗯嗯

**Comment by dencentding** [comment]
> > 是的 我的V100 32GB都扛不住 一个模型占了15GB显存 就算不调用的 显存也一直占着。希望工程师看到能够解答一下 感谢开源项目的奉献 谢谢
> 
> 我翻paddle的api跟阅读源码，发现显存泄露发生在paddle的predictor里面。但是没具体阅读paddle框架里面的内容。从paddle的api文档里面，找到了predictor.try_shrink_memory这个方法，使用这个方法可以释放使用后的tensor，但是目前来看，不知道什么原因，会发生有部分图片直接推理就会占满显存。时而发生时而不发生，比较迷惑

问题解决了吗？同样的问题，推理有时显存会不释放

**Comment by GreatV** [comment]
可以试试安装 develop 版本的 paddle 框架 @dencentding

**Comment by chelseaztq** [comment]
我解决了，之前安装的是paddle 2.6.0-post 117     后面换成了最新的paddle 3.0.0 b2 cu118版本的（我的显卡驱动最高支持到12.1 paddle官方还有个cu123的 那个没试过） 
 然后之前的现象是 我解析一批pdf shape  各不相同 最大长边应该在2000左右 ，然后我的检测最长边设置的是min  736 ，但是理论上说2000左右的最长边 最大显存开销应该不大，但是很奇怪 ，在推理了好几个不同的pdf后 显存涨到了15个 g左右，
然后我换了paddle3.0.0 b2版本后  先保持min 736不变 然后讲一张4000×4000的图拿进去推理 经过det与rec   观测到显存来到4g左右   ，接下来我根据2.6.0版本paddle 的预测过程一样，推理了相同的几个pdf ，这个时候显存再也没有超过4个g左右了（因为他们的分辨率都比4000×4000低）。
   最后我还做了个实验，当你的ocr是服务的时候（就像我一样 用fastapi  进行算法部署），最好设置最大长边resize  参数为max  具体值根据你显存决定，因为你不知道用户上传的图片分辨率有多大，设置个上限保证显存不会因为图片太大而oom，我测试下来 max设置为2048 在批量推理很多图与pdf后，显存始终在2320左右，再也不会增加或变化了，希望对你有帮助
