### ISSUE TITLE
GPU模式下CUDNN_STATUS_EXECUTION_FAILED错误

### ISSUE THREAD

**Issue by jiucl** [PaddlePaddle/PaddleOCR#11495]
您好，我这边在使用PaddleOCR时，使用CPU模式（--use_gpu false）正常，但是使用GPU模式就发生错误（--use_gpu true），错误栈如下：
Traceback (most recent call last):
  File "C:\Program Files\Python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Program Files\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\Python37\Scripts\paddleocr.exe\__main__.py", line 7, in <module>
  File "C:\Program Files\Python37\lib\site-packages\paddleocr\paddleocr.py", line 769, in main
    cls=args.use_angle_cls)
  File "C:\Program Files\Python37\lib\site-packages\paddleocr\paddleocr.py", line 648, in ocr
    dt_boxes, rec_res, _ = self.__call__(img, cls)
  File "C:\Program Files\Python37\lib\site-packages\paddleocr\tools\infer\predict_system.py", line 71, in __call__
    dt_boxes, elapse = self.text_detector(img)
  File "C:\Program Files\Python37\lib\site-packages\paddleocr\tools\infer\predict_det.py", line 245, in __call__
    self.predictor.run()
OSError: (External) CUDNN error(8), CUDNN_STATUS_EXECUTION_FAILED.
  [Hint: 'CUDNN_STATUS_EXECUTION_FAILED'.  The GPU program failed to execute. This is usually caused by a failure to launch some cuDNN kernel on the GPU, which can occur for multiple reasons.  To correct, check that the hardware, an appropriate version of the driver, and the cuDNN library are correctly installed.  Otherwise, this may indicate an internal error/bug in the library.  ] (at C:\home\workspace\Paddle\paddle\phi\kernels\fusion\gpu\conv_fusion_kernel.cu:582)
  [operator < conv2d_fusion > error]

运行环境如下：
操作系统：Microsoft Windows 11 专业版 22H2  10.0.22621 暂缺 Build 22621
CUDA：10.2
CuDNN：8.7.0.84
paddleocr：2.7.0.2
paddlepaddle-gpu：2.5.2
Python：3.7.9

期望得到您的答复，谢谢

**Comment by adzhua** [comment]
遇到了同样的问题，请问你最后怎么解决的？

**Comment by wwma** [comment]
你好，请问你解决了吗

> 遇到了同样的问题，请问你最后怎么解决的？

**Comment by jiucl** [comment]
我解决了





来自阿里邮箱Android客户端------------------------------------------------------------------
发件人：Ma ***@***.***>
日　期：2024年09月23日 16:03:49
***@***.***>
***@***.***>; State ***@***.***>
主　题：Re: [PaddlePaddle/PaddleOCR] GPU模式下CUDNN_STATUS_EXECUTION_FAILED错误 (Issue #11495)

你好，请问你解决了吗 
遇到了同样的问题，请问你最后怎么解决的？

**Comment by Virtuoso461** [comment]
怎么解决的呀

> 我解决了 来自阿里邮箱Android客户端------------------------------------------------------------------ 发件人：Ma ***@***.***> 日　期：2024年09月23日 16:03:49 ***@***.***> ***@***.***>; State ***@***.***> 主　题：Re: [PaddlePaddle/PaddleOCR] GPU模式下CUDNN_STATUS_EXECUTION_FAILED错误 (Issue #11495) 你好，请问你解决了吗 遇到了同样的问题，请问你最后怎么解决的？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: ***@***.***>

**Comment by jiucl** [comment]
就是严格按照文档的组件版本搭配来安装





来自阿里邮箱Android客户端------------------------------------------------------------------
发件人：Virgil ***@***.***>
日　期：2024年10月14日 09:07:16
***@***.***>
***@***.***>; State ***@***.***>
主　题：Re: [PaddlePaddle/PaddleOCR] GPU模式下CUDNN_STATUS_EXECUTION_FAILED错误 (Issue #11495)

怎么解决的呀 
我解决了 来自阿里邮箱Android客户端------------------------------------------------------------------ 发件人：Ma @.> 日　期：2024年09月23日 16:03:49 @.> @.>; State @.> 主　题：Re: [PaddlePaddle/PaddleOCR] GPU模式下CUDNN_STATUS_EXECUTION_FAILED错误 (Issue #11495) 你好，请问你解决了吗 遇到了同样的问题，请问你最后怎么解决的？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: @.***>
