### ISSUE TITLE
cudaErrorInitializationError  at ../paddle/phi/backends/gpu/cuda/cuda_info.cc:178

### ISSUE THREAD

**Issue by sheiy** [PaddlePaddle/PaddleOCR#12525]
报错日志
```
/usr/lib/python3/dist-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (2.2.1) or chardet (3.0.4) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
[2024-05-28 09:54:24,897] [ WARNING] - The _initialize method in HubModule will soon be deprecated, you can use the __init__() to handle the initialization of the object
[2024-05-28 09:54:30 +0000] [1] [INFO] Starting gunicorn 22.0.0
[2024-05-28 09:54:30 +0000] [1] [INFO] Listening at: http://0.0.0.0:8868 (1)
[2024-05-28 09:54:30 +0000] [1] [INFO] Using worker: sync
[2024-05-28 09:54:30 +0000] [63] [INFO] Booting worker with pid: 63
[2024-05-28 09:54:30 +0000] [65] [INFO] Booting worker with pid: 65
terminate called after throwing an instance of 'phi::enforce::EnforceNotMet'
  what():  (External) CUDA error(3), initialization error. 
  [Hint: 'cudaErrorInitializationError'. The API call failed because the CUDA driver and runtime could not be initialized. ] (at ../paddle/phi/backends/gpu/cuda/cuda_info.cc:178)

[2024-05-28 09:55:13 +0000] [1] [ERROR] Worker (pid:59) exited with code 1
[2024-05-28 09:55:13 +0000] [1] [ERROR] Worker (pid:59) exited with code 1.
[2024-05-28 09:55:13 +0000] [1] [ERROR] Worker (pid:65) was sent code 134!
[2024-05-28 09:55:13 +0000] [98] [INFO] Booting worker with pid: 98
```
Dockerfile
```
FROM  paddlepaddle/paddle:2.6.1-gpu-cuda11.2-cudnn8.2-trt8.0
WORKDIR /ocr
COPY ./PaddleOCR-release-2.7.1.zip /ocr/
RUN unzip PaddleOCR-release-2.7.1.zip
RUN rm -rf ./PaddleOCR-release-2.7.1.zip
WORKDIR /ocr/PaddleOCR-release-2.7.1
RUN pip3 install paddlehub --upgrade -i https://mirror.baidu.com/pypi/simple
RUN pip3 install -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple
RUN pip3 install protobuf==3.20.3 -i https://pypi.tuna.tsinghua.edu.cn/simple

WORKDIR /ocr/PaddleOCR-release-2.7.1/inference
COPY ./ch_PP-OCRv4_det_server_infer.tar /ocr/PaddleOCR-release-2.7.1/inference/
COPY ./ch_PP-OCRv4_rec_server_infer.tar /ocr/PaddleOCR-release-2.7.1/inference/
COPY ./ch_ppocr_mobile_v2.0_cls_infer.tar /ocr/PaddleOCR-release-2.7.1/inference/
RUN tar -xf ./ch_PP-OCRv4_det_server_infer.tar
RUN tar -xf ./ch_PP-OCRv4_rec_server_infer.tar
RUN tar -xf ./ch_ppocr_mobile_v2.0_cls_infer.tar
RUN rm ./ch_PP-OCRv4_det_server_infer.tar
RUN rm ./ch_PP-OCRv4_rec_server_infer.tar
RUN rm ./ch_ppocr_mobile_v2.0_cls_infer.tar

WORKDIR /ocr/PaddleOCR-release-2.7.1/deploy/hubserving/ocr_system
RUN sed -i 's|./inference/ch_PP-OCRv3_det_infer/|./inference/ch_PP-OCRv4_det_server_infer/|g' ./params.py
RUN sed -i 's|./inference/ch_PP-OCRv3_rec_infer/|./inference/ch_PP-OCRv4_rec_server_infer/|g' ./params.py

WORKDIR /ocr/PaddleOCR-release-2.7.1
RUN hub install deploy/hubserving/ocr_system
COPY ./config.json ./
ENV CUDA_VISIBLE_DEVICES=0
ENTRYPOINT ["hub","serving","start","-c","config.json"]
```
config.json配置文件
```
{
    "modules_info": {
        "ocr_system": {
            "init_args": {
                "version": "1.0.0",
                "use_gpu": true
            },
            "predict_args": {
            }
        }
    },
    "port": 8868,
    "use_multiprocess": true, //这里设置成false可以正常识别文字，但是处理请求就变成串行的了
    "workers": 2
}
```
容器启动命令`docker run --gpus "device=4" --name xx-ocr --shm-size=32G -p 8868:8868 镜像ID`
宿主机nvidia-smi输出
<img width="837" alt="image" src="https://github.com/PaddlePaddle/PaddleOCR/assets/12210038/145f1cc6-20b0-47d1-803a-b0312e3d9909">

**Comment by GreatV** [comment]
CUDA 驱动和运行时无法初始化。这可能是由于多个原因导致的，包括 CUDA 驱动安装问题或与 CUDA 相关的库不兼容。

**Comment by GreatV** [comment]
本地可以跑吗

**Comment by sheiy** [comment]
> 本地可以跑吗

@GreatV 本地是mac；直接在测试服务器上docker启的；宿主机只装了Nvidia的驱动；上面qwen1.5是能正常跑的

**Comment by GreatV** [comment]
可以看下 paddlepaddle组织下的同类问题找找思路 https://github.com/search?q=org%3APaddlePaddle+cudaErrorInitializationError&type=issues

**Comment by b4bbuilder** [comment]
Not sure if this will apply or not. I resolved the same error with:

from multiprocessing import Pool, set_start_method
set_start_method('spawn', force=True) at script beginning
