### ISSUE TITLE
kie表格ser训练报错

### ISSUE THREAD

**Issue by icutool** [PaddlePaddle/PaddleOCR#13123]
#### 问题描述 / Problem Description
[文章地址](https://github.com/PaddlePaddle/PaddleOCR/blob/main/doc/doc_ch/kie.md)使用这个kie进行训练表格图片标注训练的时候,当我的标签只有answer和question的时候一切正常,但是我标注很多标签的时候大概有20个标签的时候就会报错,说标签数需要大于0小于7,但是我看文档的身份证图片也不止7个标签,所以想问一下有没有老哥知道是因为啥,是数量的问题还是标签只能是answer question other等
![image](https://github.com/PaddlePaddle/PaddleOCR/assets/58366347/98d5f188-55d7-45b2-91fa-557367878977)

#### 运行环境 / Runtime Environment
- OS: ubuntu18.04
- Paddle:2.6.1
- PaddleOCR:2.7.3

#### 复现代码 / Reproduction Code
python3 tools/train.py -c configs/kie/vi_layoutxlm/ser_vi_layoutxlm_xfund_zh.yml

#### 完整报错 / Complete Error Message
```
LAUNCH INFO 2024-06-18 18:56:12,493 ------------------------- ERROR LOG DETAIL -------------------------
[2024/06/18 18:55:20] ppocr INFO: Initialize indexs of datasets:['train_data/XFUND/zh_train/train.json']
list index out of range
[2024-06-18 18:55:29,400] [    INFO] - tokenizer config file saved in /root/.paddlenlp/models/layoutxlm-base-uncased/tokenizer_config.json
[2024-06-18 18:55:29,400] [    INFO] - Special tokens file saved in /root/.paddlenlp/models/layoutxlm-base-uncased/special_tokens_map.json
[2024/06/18 18:55:29] ppocr INFO: Initialize indexs of datasets:['train_data/XFUND/zh_val/val.json']
[2024-06-18 18:55:30,086] [    INFO] - tokenizer config file saved in /root/.paddlenlp/models/layoutxlm-base-uncased/tokenizer_config.json
[2024-06-18 18:55:30,086] [    INFO] - Special tokens file saved in /root/.paddlenlp/models/layoutxlm-base-uncased/special_tokens_map.json
[2024-06-18 18:55:30,091] [ WARNING] - You are using a model of type layoutlmv2 to instantiate a model of type layoutxlm. This is not supported for all configurations of models and can yield errors.
[2024-06-18 18:55:30,110] [    INFO] - Loading weights file from cache at /root/.paddlenlp/models/vi-layoutxlm-base-uncased/model_state.pdparams
[2024-06-18 18:55:36,468] [    INFO] - Loaded weights file from disk, setting weights to model.
W0618 18:55:36.522583  6041 gpu_resources.cc:119] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 11.7, Runtime API Version: 11.7
W0618 18:55:36.757198  6041 gpu_resources.cc:164] device: 0, cuDNN Version: 8.4.
[2024-06-18 18:55:55,093] [ WARNING] - Some weights of the model checkpoint at vi-layoutxlm-base-uncased were not used when initializing LayoutXLMForTokenClassification: ['visual.pixel_mean', 'visual.pixel_std', 'visual_proj.bias', 'visual_proj.weight']
- This IS expected if you are initializing LayoutXLMForTokenClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing LayoutXLMForTokenClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
[2024-06-18 18:55:55,093] [ WARNING] - Some weights of LayoutXLMForTokenClassification were not initialized from the model checkpoint at vi-layoutxlm-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
[2024/06/18 18:55:55] ppocr INFO: train dataloader has 1 iters
[2024/06/18 18:55:55] ppocr INFO: valid dataloader has 1 iters
[2024/06/18 18:55:55] ppocr INFO: During the training process, after the 0th iteration, an evaluation is run every 19 iterations
W0618 18:56:01.517853  6041 gpu_resources.cc:299] WARNING: device: . The installed Paddle is compiled with CUDNN 8.4, but CUDNN version in your machine is 8.4, which may cause serious incompatible bug. Please recompile or reinstall Paddle with compatible CUDNN version.
Error: ../paddle/phi/kernels/gpu/cross_entropy_kernel.cu:998 Assertion `false` failed. The value of label expected >= 0 and < 7, or == -100, but got 25. Please check label value.
Error: ../paddle/phi/kernels/gpu/cross_entropy_kernel.cu:998 Assertion `false` failed. The value of label expected >= 0 and < 7, or == -100, but got 25. Please check label value.
Error: ../paddle/phi/kernels/gpu/cross_entropy_kernel.cu:998 Assertion `false` failed. The value of label expected >= 0 and < 7, or == -100, but got 25. Please check label value.
Error: ../paddle/phi/kernels/gpu/cross_entropy_kernel.cu:998 Assertion `false` failed. The value of label expected >= 0 and < 7, or == -100, but got 25. Please check label value.
Error: ../paddle/phi/kernels/gpu/cross_entropy_kernel.cu:998 Assertion `false` failed. The value of label expected >= 0 and < 7, or == -100, but got 25. Please check label value.
Error: ../paddle/phi/kernels/gpu/cross_entropy_kernel.cu:998 Assertion `false` failed. The value of label expected >= 0 and < 7, or == -100, but got 25. Please check label value.
Error: ../paddle/phi/kernels/gpu/cross_entropy_kernel.cu:998 Assertion `false` failed. The value of label expected >= 0 and < 7, or == -100, but got 25. Please check label value.
Traceback (most recent call last):
  File "/opt/temp/PaddleOCR/PaddleOCR-main/tools/train.py", line 255, in <module>
    main(config, device, logger, vdl_writer, seed)
  File "/opt/temp/PaddleOCR/PaddleOCR-main/tools/train.py", line 208, in main
    program.train(
  File "/opt/temp/PaddleOCR/PaddleOCR-main/tools/program.py", line 344, in train
    loss = loss_class(preds, batch)
  File "/root/anaconda3/envs/paddle261/lib/python3.9/site-packages/paddle/nn/layer/layers.py", line 1429, in __call__
    return self.forward(*inputs, **kwargs)
  File "/opt/temp/PaddleOCR/PaddleOCR-main/ppocr/losses/vqa_token_layoutlm_loss.py", line 51, in forward
    loss = self.loss_class(active_output, active_label)
  File "/root/anaconda3/envs/paddle261/lib/python3.9/site-packages/paddle/nn/layer/layers.py", line 1429, in __call__
    return self.forward(*inputs, **kwargs)
  File "/root/anaconda3/envs/paddle261/lib/python3.9/site-packages/paddle/nn/layer/loss.py", line 411, in forward
    ret = paddle.nn.functional.cross_entropy(
  File "/root/anaconda3/envs/paddle261/lib/python3.9/site-packages/paddle/nn/functional/loss.py", line 2898, in cross_entropy
    if paddle.count_nonzero(is_ignore) > 0:  # ignore label
  File "/root/anaconda3/envs/paddle261/lib/python3.9/site-packages/paddle/base/dygraph/tensor_patch_methods.py", line 849, in __bool__
    return self.__nonzero__()
  File "/root/anaconda3/envs/paddle261/lib/python3.9/site-packages/paddle/base/dygraph/tensor_patch_methods.py", line 846, in __nonzero__
    return bool(np.array(self) > 0)
  File "/root/anaconda3/envs/paddle261/lib/python3.9/site-packages/paddle/base/dygraph/tensor_patch_methods.py", line 874, in __array__
    array = self.numpy(False)
OSError: (External) CUDA error(719), unspecified launch failure. 
  [Hint: 'cudaErrorLaunchFailure'. An exception occurred on the device while executing a kernel. Common causes include dereferencing an invalid device pointerand accessing out of bounds shared memory. Less common cases can be system specific - more information about these cases canbe found in the system specific user guide. This leaves the process in an inconsistent state and any further CUDA work willreturn the same error. To continue using CUDA, the process must be terminated and relaunched.] (at ../paddle/phi/backends/gpu/cuda/cuda_info.cc:272)

.cu:998 Assertion `false` failed. The value of label expected >= 0 and < 7, or == -100, but got 25. Please check label value.
Error: ../paddle/phi/kernels/gpu/cross_entropy_kernel.cu:998 Assertion `false` failed. The value of label expected >= 0 and < 7, or == -100, but got 25. Please check label value.
Error: ../paddle/phi/kernels/gpu/cross_entropy_kernel.cu:998 Assertion `false` failed. The value of label expected >= 0 and < 7, or == -100, but got 25. Please check label value.
Error: ../paddle/phi/kernels/gpu/cross_entropy_kernel.cu:998 Assertion `false` failed. The value of label expected >= 0 and < 7, or == -100, but got 25. Please check label value.
Traceback (most recent call last):
  File "/opt/temp/PaddleOCR/PaddleOCR-main/tools/train.py", line 255, in <module>
    main(config, device, logger, vdl_writer, seed)
  File "/opt/temp/PaddleOCR/PaddleOCR-main/tools/train.py", line 208, in main
    program.train(
  File "/opt/temp/PaddleOCR/PaddleOCR-main/tools/program.py", line 344, in train
    loss = loss_class(preds, batch)
  File "/root/anaconda3/envs/paddle261/lib/python3.9/site-packages/paddle/nn/layer/layers.py", line 1429, in __call__
    return self.forward(*inputs, **kwargs)
  File "/opt/temp/PaddleOCR/PaddleOCR-main/ppocr/losses/vqa_token_layoutlm_loss.py", line 51, in forward
    loss = self.loss_class(active_output, active_label)
LAUNCH INFO 2024-06-18 18:56:12,494 Exit code 1
  File "/root/anaconda3/envs/paddle261/lib/python3.9/site-packages/paddle/nn/layer/layers.py", line 1429, in __call__
    return self.forward(*inputs, **kwargs)
  File "/root/anaconda3/envs/paddle261/lib/python3.9/site-packages/paddle/nn/layer/loss.py", line 411, in forward
    ret = paddle.nn.functional.cross_entropy(
  File "/root/anaconda3/envs/paddle261/lib/python3.9/site-packages/paddle/nn/functional/loss.py", line 2898, in cross_entropy
    if paddle.count_nonzero(is_ignore) > 0:  # ignore label
  File "/root/anaconda3/envs/paddle261/lib/python3.9/site-packages/paddle/base/dygraph/tensor_patch_methods.py", line 849, in __bool__
    return self.__nonzero__()
  File "/root/anaconda3/envs/paddle261/lib/python3.9/site-packages/paddle/base/dygraph/tensor_patch_methods.py", line 846, in __nonzero__
    return bool(np.array(self) > 0)
  File "/root/anaconda3/envs/paddle261/lib/python3.9/site-packages/paddle/base/dygraph/tensor_patch_methods.py", line 874, in __array__
    array = self.numpy(False)
OSError: (External) CUDA error(719), unspecified launch failure. 
  [Hint: 'cudaErrorLaunchFailure'. An exception occurred on the device while executing a kernel. Common causes include dereferencing an invalid device pointerand accessing out of bounds shared memory. Less common cases can be system specific - more information about these cases canbe found in the system specific user guide. This leaves the process in an inconsistent state and any further CUDA work willreturn the same error. To continue using CUDA, the process must be terminated and relaunched.] (at ../paddle/phi/backends/gpu/cuda/cuda_info.cc:272)
```

**Comment by DoManhQuang** [comment]
same issues :(

**Comment by icutool** [comment]
解决了  修改configs/kie/vi_layoutxlm/ser_vi_layoutxlm_xfund_zh.yml文件的num_classes值
![image](https://github.com/PaddlePaddle/PaddleOCR/assets/58366347/9c4567e0-792f-4ed6-a26c-06adde79d9d8)

**Comment by qdhonker** [comment]
这个值 怎么改，改多少
