### ISSUE TITLE
ch_PP-OCRv4_server_rec高精度模型包运行失败ExternalError: CUDNN error(9), CUDNN_STATUS_NOT_SUPPORTED

### ISSUE THREAD

**Issue by Xnollis** [PaddlePaddle/PaddleOCR#13778]
### 🔎 Search before asking

- [X] I have searched the PaddleOCR [Docs](https://paddlepaddle.github.io/PaddleOCR/) and found no similar bug report.
- [X] I have searched the PaddleOCR [Issues](https://github.com/PaddlePaddle/PaddleOCR/issues) and found no similar bug report.
- [X] I have searched the PaddleOCR [Discussions](https://github.com/PaddlePaddle/PaddleOCR/discussions) and found no similar bug report.

### 🐛 Bug (问题描述)

我尝试自己手工下载了ch_PP-OCRv4_server_rec高精度模型包（以及DET模型包），解压并替换原有的位于“.paddleocr”文件夹中的`ch_PP-OCRv4_rec`文件夹下的`inference.pdmodel`等三个文件之后，

执行命令`paddleocr --image_dir frame_1.png --use_gpu True`会导致程序报错退出：

`ExternalError: CUDNN error(9), CUDNN_STATUS_NOT_SUPPORTED.
      [Hint: 'CUDNN_STATUS_NOT_SUPPORTED'.  The functionality requested is not presently supported by cuDNN.  ] (at C:\home\workspace\Paddle\paddle\phi\kernels\fusion\gpu\fused_conv2d_add_act_kernel.cu:610)
      [operator < fused_conv2d_add_act > error]`

但如果运行参数改为`--use_gpu False`，则可以正常得到识别结果。

请问这个问题如何解决？如何正常使用ch_PP-OCRv4_server_rec高精度模型？

### 🏃‍♂️ Environment (运行环境)

运行环境：
OS：windows10 x64
Python 3.10
paddle包：paddlepaddle_gpu-2.6.1，paddleocr-2.8.1

CUDA检测命令：
python -c "import paddle; print(paddle.version.cuda())"
11.8
python -c "import paddle; print(paddle.version.cudnn())"
8.6.0

### 🌰 Minimal Reproducible Example (最小可复现问题的Demo)

首先要正常安装paddleocr-2.8.1，并能够正常使用paddleocr程序以及默认的`ch_PP-OCRv4_rec`模型来成功地进行识别。
然后：
1.从模型库下载 ch_PP-OCRv4_server_det 和 ch_PP-OCRv4_server_rec 高精度模型文件，
2.解压并替换原有的位于“.paddleocr/whl/rec/ch”文件夹中的`ch_PP-OCRv4_rec`文件夹下的`inference.pdmodel`等三个文件（det模型文件也同样执行解压替换操作）
3.执行命令`paddleocr --image_dir frame_1.png --use_gpu True`  ,frame_1.png是某个待识别处理的图片。
4.程序报告异常并退出
`ExternalError: CUDNN error(9), CUDNN_STATUS_NOT_SUPPORTED.
      [Hint: 'CUDNN_STATUS_NOT_SUPPORTED'.  The functionality requested is not presently supported by cuDNN.  ] (at C:\home\workspace\Paddle\paddle\phi\kernels\fusion\gpu\fused_conv2d_add_act_kernel.cu:610)
      [operator < fused_conv2d_add_act > error]`

**Comment by Xnollis** [comment]
我从官方网址 https://developer.nvidia.com/cuda-toolkit-archive 分别安装了 CUDA11.7和CUDA11.8，
然后从官方网址 https://developer.download.nvidia.com/compute/cudnn/redist/cudnn/windows-x86_64/ 下载并安装了最新的cudnn组件cudnn-windows-x86_64-8.9.7.29_cuda11

通过使用此回复中的方法（ https://github.com/PaddlePaddle/PaddleOCR/discussions/13768#discussioncomment-10484969 ）
无论如何排列组合，paddleocr 程序都无法正确执行，得到的出错信息都是一样的。
如果方便的话，请给出可以正常运行`paddleocr` 程序的cuda-toolkit版本号与cudnn版本号

**Comment by Xnollis** [comment]
已解决！（ https://github.com/PaddlePaddle/PaddleOCR/discussions/13768#discussioncomment-10488025 ）

需要显卡驱动的大版本号 与CUDA运行时库的大版本号保持一致，比如都是12或都是11。 
然后从官网下载最新的cuDNN-8.9.7组件（ https://developer.download.nvidia.com/compute/cudnn/redist/cudnn/windows-x86_64/ ），解压后放到自己程序所在的目录即可。

通过运行下面这个命令，可以看到Driver API Version 和 Runtime API Version。
`python -c "import paddle; paddle.utils.run_check()"`
后得到以下信息：
`Running verify PaddlePaddle program ...
I0829 22:05:53.175015 10208 program_interpreter.cc:212] New Executor is Running.
W0829 22:05:53.176012 10208 gpu_resources.cc:119] Please NOTE: device: 0, GPU Compute Capability: 7.5, "Driver API Version": 12.2, "Runtime API Version": 12.0
W0829 22:05:53.180001 10208 gpu_resources.cc:164] device: 0, cuDNN Version: 8.9.
I0829 22:05:53.862905 10208 interpreter_util.cc:624] Standalone Executor is Used.
PaddlePaddle works well on 1 GPU.
PaddlePaddle is installed successfully! Let's start deep learning with PaddlePaddle now.`
