### ISSUE TITLE
CUDNN_STATUS_INTERNAL_ERROR  

### ISSUE THREAD

**Issue by ulanbator** [PaddlePaddle/PaddleOCR#1488]
环境：cudnn=7.6 cuda=10.2 paddlepaddle-gpu=2.0.0rc1
执行命令：CUDA_VISIBLE_DEVICES=3 python3 tools/train.py -c configs/det/det_r18_vd_db_v1.1.yml -o Global.pretrain_weights=./pretrain_models/ResNet18_vd_pretrained
报错结果：Traceback (most recent call last):
  File "tools/train.py", line 135, in <module>
    main()
  File "tools/train.py", line 75, in main
    exe.run(startup_program)
  File "/home/zhengfang3/anaconda3/envs/paddleocr/lib/python3.6/site-packages/paddle/fluid/executor.py", line 1108, in run
    six.reraise(*sys.exc_info())
  File "/home/zhengfang3/anaconda3/envs/paddleocr/lib/python3.6/site-packages/six.py", line 703, in reraise
    raise value
  File "/home/zhengfang3/anaconda3/envs/paddleocr/lib/python3.6/site-packages/paddle/fluid/executor.py", line 1106, in run
    return_merged=return_merged)
  File "/home/zhengfang3/anaconda3/envs/paddleocr/lib/python3.6/site-packages/paddle/fluid/executor.py", line 1236, in _run_impl
    use_program_cache=use_program_cache)
  File "/home/zhengfang3/anaconda3/envs/paddleocr/lib/python3.6/site-packages/paddle/fluid/executor.py", line 1326, in _run_program
    [fetch_var_name])
OSError: (External)  Cudnn error, CUDNN_STATUS_INTERNAL_ERROR  (at /paddle/paddle/fluid/platform/device_context.h:210)

**Comment by tink2123** [comment]
1. 动态图加载预训练模型的字段是  `-o Global.pretrained_model` 启动命令需要修改一下
2. `CUDNN_STATUS_INTERNAL_ERROR` 有可能是显存不足导致的，可以减小训练 batch size 试一下

**Comment by ulanbator** [comment]
已解决，谢谢。
