### ISSUE TITLE
out of memory

### ISSUE THREAD

**Issue by MapleWan** [PaddlePaddle/PaddleOCR#1543]
Out of memory error on GPU 0. Cannot allocate 2.071839GB memory on GPU 0, available memory is only 1.171448GB.

nvidia-smi状态如下

![image](https://user-images.githubusercontent.com/27999089/102783232-957ca100-43d5-11eb-9792-90ff79a317ab.png)

我该如何解决这个问题呢？使用的docker容器， GPU all权限

**Comment by MapleWan** [comment]
![image](https://user-images.githubusercontent.com/27999089/102787003-5e10f300-43db-11eb-830c-83c423cf357c.png)
具体的报错信息补充 
图片（1.46M）的分辨率是 4940*7021是会出现这种问题 
图片（208kb）分辨率为480*680的时候，是可以处理成功的
请问对图片分辨率有什么要求吗？

**Comment by CSU-FulChou** [comment]
我也遇到了这个问题，小尺寸的图片可以运行， 图片到800kb左右就开始报错 out of memory。 然而我的显存完全没有被用到，不知道是为什么。使用的是GPU 版本的paddle
希望得到解答，谢谢

**Comment by LDOUBLEV** [comment]
1. 这个参数改小一点：https://github.com/PaddlePaddle/PaddleOCR/blob/45f647db3f567f78de1506e596c26785dddd8436/tools/infer/utility.py#L36
2. 设置环境变量：export FLAGS_allocator_strategy=auto_growth  或者 export FLAGS_fraction_of_gpu_memory_to_use=0.

**Comment by CSU-FulChou** [comment]
> 1. 这个参数改小一点：https://github.com/PaddlePaddle/PaddleOCR/blob/45f647db3f567f78de1506e596c26785dddd8436/tools/infer/utility.py#L36
> 2. 设置环境变量：export FLAGS_allocator_strategy=auto_growth  或者 export FLAGS_fraction_of_gpu_memory_to_use=0.

您好，我安装您的建议去做了。
我这边发现的现象还是说， 可能是图片太大了。 在模型加载的时候已经占了 一部分GPU， 然后就不够 大图片全部加载进去GPU了， 32g的V100 最后提升还差个2g左右的显存。 图片的大小是1.2M 左右。 请问这个现象是合理的吗？

**Comment by LDOUBLEV** [comment]
不是图片太大的问题，你更新下PaddleOCR的最新代码再试下，昨天更新了动态图分支预测的接口

**Comment by LDOUBLEV** [comment]
在代码中设置了环境变量，在T4GPU上测试有效限制GPU显存占用，供参考：https://github.com/PaddlePaddle/PaddleOCR/pull/1553

**Comment by CSU-FulChou** [comment]
> 在代码中设置了环境变量，在T4GPU上测试有效限制GPU显存占用，供参考：#1553

非常感谢，问题已经解决。能够成功predict 大的图片

**Comment by soxunyi** [comment]
only for branch 2.0++

**Comment by soxunyi** [comment]
only for branch 2.0+
