### ISSUE TITLE
H100 运行GPU 3.0 版本报错，CUDA error (/paddle/third_party/flashattn/csrc/flash_attn/src/flash_fwd_launch_template.h:56): no kernel image is available for execution on the device

### ISSUE THREAD

**Issue by tao-xiaoxin** [PaddlePaddle/PaddleOCR#15814]
### 🔎 Search before asking

- [x] I have searched the PaddleOCR [Docs](https://paddlepaddle.github.io/PaddleOCR/) and found no similar bug report.
- [x] I have searched the PaddleOCR [Issues](https://github.com/PaddlePaddle/PaddleOCR/issues) and found no similar bug report.
- [x] I have searched the PaddleOCR [Discussions](https://github.com/PaddlePaddle/PaddleOCR/discussions) and found no similar bug report.

### 🐛 Bug (问题描述)

GPU 3.0 版本在H100 运行出错，内容如下：
~~~
CUDA error (/paddle/third_party/flashattn/csrc/flash_attn/src/flash_fwd_launch_template.h:56): no kernel image is available for execution on the device
~~~

### 🏃‍♂️ Environment (运行环境)

nvcc 版本如下：
~~~
nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Wed_Sep_21_10:33:58_PDT_2022
Cuda compilation tools, release 11.8, V11.8.89
Build cuda_11.8.r11.8/compiler.31833905_0

~~~
Python 版本：3.10

就是通过如下命令安装的：
~~~
python -m pip install paddlepaddle-gpu==3.0.0 -i https://www.paddlepaddle.org.cn/packages/stable/cu118/
~~~

### 🌰 Minimal Reproducible Example (最小可复现问题的Demo)

~~~
paddleocr pp_structurev3 -i https://paddle-model-ecology.bj.bcebos.com/paddlex/imgs/demo_image/pp_structure_v3_demo.png
~~~

**Comment by tao-xiaoxin** [comment]
完整错误如下：
~~~bash
(paddle_env) root@notebook-1750212602-fymgl-7ccdb88b9-bj5q2:/gwm-tmp/PaddleOCR# python ocr_server.py 
🚀 Initializing PaddleOCR with H100 compatibility settings...
/opt/conda/envs/paddle_env/lib/python3.10/site-packages/paddle/utils/cpp_extension/extension_utils.py:711: UserWarning: No ccache found. Please be aware that recompiling all source files may be required. You can download and install ccache from: https://github.com/ccache/ccache/blob/master/doc/INSTALL.md
  warnings.warn(warning_message)
Creating model: ('PP-LCNet_x1_0_doc_ori', None)
Using official model (PP-LCNet_x1_0_doc_ori), the model files will be automatically downloaded and saved in /root/.paddlex/official_models.
Creating model: ('UVDoc', None)
Using official model (UVDoc), the model files will be automatically downloaded and saved in /root/.paddlex/official_models.
Creating model: ('PP-DocBlockLayout', None)
Using official model (PP-DocBlockLayout), the model files will be automatically downloaded and saved in /root/.paddlex/official_models.
Creating model: ('PP-DocLayout_plus-L', None)
Using official model (PP-DocLayout_plus-L), the model files will be automatically downloaded and saved in /root/.paddlex/official_models.
Creating model: ('PP-LCNet_x1_0_textline_ori', None)
Using official model (PP-LCNet_x1_0_textline_ori), the model files will be automatically downloaded and saved in /root/.paddlex/official_models.
Creating model: ('PP-OCRv5_server_det', None)
Using official model (PP-OCRv5_server_det), the model files will be automatically downloaded and saved in /root/.paddlex/official_models.
Creating model: ('PP-OCRv5_server_rec', None)
Using official model (PP-OCRv5_server_rec), the model files will be automatically downloaded and saved in /root/.paddlex/official_models.
Creating model: ('PP-OCRv4_server_seal_det', None)
Using official model (PP-OCRv4_server_seal_det), the model files will be automatically downloaded and saved in /root/.paddlex/official_models.
Creating model: ('PP-OCRv5_server_rec', None)
Using official model (PP-OCRv5_server_rec), the model files will be automatically downloaded and saved in /root/.paddlex/official_models.
Creating model: ('PP-LCNet_x1_0_table_cls', None)
Using official model (PP-LCNet_x1_0_table_cls), the model files will be automatically downloaded and saved in /root/.paddlex/official_models.
Creating model: ('SLANeXt_wired', None)
Using official model (SLANeXt_wired), the model files will be automatically downloaded and saved in /root/.paddlex/official_models.
Creating model: ('SLANet_plus', None)
Using official model (SLANet_plus), the model files will be automatically downloaded and saved in /root/.paddlex/official_models.
Creating model: ('RT-DETR-L_wired_table_cell_det', None)
Using official model (RT-DETR-L_wired_table_cell_det), the model files will be automatically downloaded and saved in /root/.paddlex/official_models.
Creating model: ('RT-DETR-L_wireless_table_cell_det', None)
Using official model (RT-DETR-L_wireless_table_cell_det), the model files will be automatically downloaded and saved in /root/.paddlex/official_models.
Creating model: ('PP-FormulaNet_plus-L', None)
Using official model (PP-FormulaNet_plus-L), the model files will be automatically downloaded and saved in /root/.paddlex/official_models.
Creating model: ('PP-Chart2Table', None)
Using official model (PP-Chart2Table), the model files will be automatically downloaded and saved in /root/.paddlex/official_models.
CUDA error (/paddle/third_party/flashattn/csrc/flash_attn/src/flash_fwd_launch_template.h:56): no kernel image is available for execution on the device
~~~

**Comment by fffsbx** [comment]
大佬 请问怎么解决的 我也遇到一样的问题

**Comment by tao-xiaoxin** [comment]
> 大佬 请问怎么解决的 我也遇到一样的问题

删掉自动下载的模型,使用如下命令安装: 

```
 python -m pip install paddlepaddle-gpu==3.1.0 -i https://www.paddlepaddle.org.cn/packages/stable/cu126/
```

**Comment by fffsbx** [comment]
我的CUDA是12.4升级不了 所以还是会报这个问题

**Comment by tao-xiaoxin** [comment]
> 我的CUDA是12.4升级不了 所以还是会报这个问题

首先删除这个目录缓存: `/root/.paddlex/`，然后租一台GPU 服务器，然后试着跑起来，跑起来之后把模型打包压缩传过去，或许就解决了

**Comment by tao-xiaoxin** [comment]
> 我的CUDA是12.4升级不了 所以还是会报这个问题

模型缓存目录就是`/root/.paddlex/`

**Comment by brunodoamaral** [comment]
I'm having the same issue using the docker version (ccr-2vdh3abv-pub.cnc.bj.baidubce.com/paddlex/hps:paddlex3.1-gpu) and running with paddlex_hps_layout_parsing_sdk.
