### ISSUE TITLE
华为NPU环境同一个图片版面分析多次推理结果不一样

### ISSUE THREAD

**Issue by Sage520** [PaddlePaddle/PaddleOCR#16242]
### 🔎 Search before asking

- [x] I have searched the PaddleOCR [Docs](https://paddlepaddle.github.io/PaddleOCR/) and found no similar bug report.
- [x] I have searched the PaddleOCR [Issues](https://github.com/PaddlePaddle/PaddleOCR/issues) and found no similar bug report.
- [x] I have searched the PaddleOCR [Discussions](https://github.com/PaddlePaddle/PaddleOCR/discussions) and found no similar bug report.

### 🐛 Bug (问题描述)

华为NPU环境同一个图片版面分析多次推理结果不一样，控制台偶尔会输出 Resized image size (960x18605) exceeds max_side_limit of 4000. Resizing to fit within limit 提示，但是我的图片分辨率只有568*840。

### 🏃‍♂️ Environment (运行环境)

```bash
OS: Ubuntu 22.04.4 LTS
NPU: 910B4 32G显存
NPU驱动版本: 24.1.rc2.b030
镜像：根据官网多硬件NPU步骤构建 https://paddlepaddle.github.io/PaddleOCR/latest/version3.x/other_devices_support/paddlepaddle_install_NPU.html
依赖版本：
paddle-custom-npu        3.0.0.dev20250527
paddle2onnx              1.3.1
paddleocr                3.0.2
paddlepaddle             3.0.0.dev20250527
paddlex                  3.0.2
```

### 🌰 Minimal Reproducible Example (最小可复现问题的Demo)

引擎初始化
```python
def load_layout_engine(device: str = 'gpu:0'):
    # 最大 resize 960 限制分辨率，防止显存溢出
    return PPStructureV3(
        device=device,
        enable_hpi=False,
        text_det_limit_type='max',
        text_det_limit_side_len=960,
        text_recognition_model_dir=REC_MODEL_DIR,
        text_detection_model_dir=DET_MODEL_DIR,
        doc_orientation_classify_model_name="PP-LCNet_x1_0_doc_ori",
        doc_orientation_classify_model_dir=f"{OCR_BASE_DIR}/PP-LCNet_x1_0_doc_ori",
        doc_unwarping_model_dir=f"{OCR_BASE_DIR}/UVDoc",
        textline_orientation_model_dir=f"{OCR_BASE_DIR}/PP-LCNet_x1_0_textline_ori",
        use_doc_orientation_classify=True, # 通过 use_doc_orientation_classify 参数指定不使用文档方向分类模型
        use_doc_unwarping=True, # 通过 use_doc_unwarping 参数指定不使用文本图像矫正模型
        use_textline_orientation=True, # 通过 use_textline_orientation 参数指定不使用文本行方向分类模型
        layout_detection_model_dir=f"{OCR_BASE_DIR}/PP-DocLayout_plus-L",
        region_detection_model_dir=f"{OCR_BASE_DIR}/PP-DocBlockLayout",
        table_classification_model_dir=f"{OCR_BASE_DIR}/PP-LCNet_x1_0_table_cls",
        wired_table_structure_recognition_model_name="SLANeXt_wired",
        wired_table_structure_recognition_model_dir=f"{OCR_BASE_DIR}/SLANeXt_wired",
        wireless_table_structure_recognition_model_name="SLANeXt_wireless",
        wireless_table_structure_recognition_model_dir=f"{OCR_BASE_DIR}/SLANeXt_wireless",
        wired_table_cells_detection_model_dir=f"{OCR_BASE_DIR}/RT-DETR-L_wired_table_cell_det",
        wireless_table_cells_detection_model_dir=f"{OCR_BASE_DIR}/RT-DETR-L_wireless_table_cell_det",
        table_orientation_classify_model_dir=None,
        # 是否加载并使用表格识别子产线
        use_table_recognition=True,
        # 是否加载并使用文档区域检测子产线
        use_region_detection=True,
        seal_text_detection_model_dir=f"{OCR_BASE_DIR}/PP-OCRv4_server_seal_det",
        seal_text_recognition_model_dir=REC_MODEL_DIR,
        use_seal_recognition=True,
        use_formula_recognition=False,
        use_chart_recognition=False,
    )
```

AP接口
```python
@app.post("/layout")
async def layout(request: Request, file: UploadFile = File(...)) -> Response:
    check_layout_enabled()

    file_byte = await file.read()
    if not file_byte:
        return fail('file_byte is empty')

    layout_engine = getattr(request.app, "layout_engine")
    nparr = np.frombuffer(file_byte, np.uint8)
    img = cv2.imdecode(nparr, cv2.IMREAD_COLOR)
    '''
    use_e2e_wired_table_rec_model
    是否启用有线表端到端表格识别模式，启用则不使用单元格检测模型，只使用表格结构识别模型。	
    '''
    layout_res = layout_engine.predict(img)
    layout_res = layout_res[0]

    res = dict(markdown = '', layout_data = [], ocr_data = [], markdown_images = {})
    res['markdown'] = layout_res.markdown['markdown_texts']
    markdown_images = layout_res.markdown['markdown_images']
    res['markdown_images'] = image_to_base64_dict(markdown_images)
    layout_json = layout_res.json.get('res', {})
    res['layout_data'] = layout_json['parsing_res_list']
    ocr_data = ocr_res_merge(layout_json['overall_ocr_res'])
    ocr_data = ocr_res_handle(ocr_data)
    res['ocr_data'] = ocr_data
```

**Comment by Sage520** [comment]
# 补充一下测试图片和出现的多种结果
<img width="568" height="840" alt="Image" src="https://github.com/user-attachments/assets/5563ed63-cd1c-41d4-9dc1-adc62a28c5a7" />

<img width="715" height="299" alt="Image" src="https://github.com/user-attachments/assets/456b51f5-fcb1-4aae-aef5-4e5e7a5a5417" />

<img width="713" height="299" alt="Image" src="https://github.com/user-attachments/assets/0306c906-0bb6-4bb6-b654-c43a25c4d161" />

**Comment by a31413510** [comment]
收到，我们复现分析一下

**Comment by a31413510** [comment]
建议这个最新稳定版本，修复了部分推理问题
python -m pip install paddlepaddle==3.1.1 -i https://www.paddlepaddle.org.cn/packages/stable/cpu/
python -m pip install paddle-custom-npu==3.1.1 -i https://www.paddlepaddle.org.cn/packages/stable/npu/

**Comment by Sage520** [comment]
> 建议这个最新稳定版本，修复了部分推理问题 python -m pip install paddlepaddle==3.1.1 -i https://www.paddlepaddle.org.cn/packages/stable/cpu/ python -m pip install paddle-custom-npu==3.1.1 -i https://www.paddlepaddle.org.cn/packages/stable/npu/

好的，我尝试一下在继续跟进

**Comment by Sage520** [comment]
更新后问题解决，确实是版本问题
