### ISSUE TITLE
PP-StructureV3 华为昇腾910B 报错 (CL error, the error code is : 500001.)

### ISSUE THREAD

**Issue by tao-xiaoxin** [PaddlePaddle/PaddleOCR#16965]
### 🔎 Search before asking

- [x] I have searched the PaddleOCR [Docs](https://paddlepaddle.github.io/PaddleOCR/) and found no similar bug report.
- [x] I have searched the PaddleOCR [Issues](https://github.com/PaddlePaddle/PaddleOCR/issues) and found no similar bug report.
- [x] I have searched the PaddleOCR [Discussions](https://github.com/PaddlePaddle/PaddleOCR/discussions) and found no similar bug report.

### 🐛 Bug (问题描述)

```

root@pm-a206:~# python demo.py 
Creating model: ('PP-LCNet_x1_0_doc_ori', None)
Model files already exist. Using cached files. To redownload, please delete the directory manually: `/root/.paddlex/official_models/PP-LCNet_x1_0_doc_ori`.
I1105 14:40:01.075873    38 init.cc:238] ENV [CUSTOM_DEVICE_ROOT]=/usr/local/lib/python3.10/dist-packages/paddle_custom_device
I1105 14:40:01.075919    38 init.cc:146] Try loading custom device libs from: [/usr/local/lib/python3.10/dist-packages/paddle_custom_device]
I1105 14:40:01.633749    38 custom_device_load.cc:51] Succeed in loading custom runtime in lib: /usr/local/lib/python3.10/dist-packages/paddle_custom_device/libpaddle-custom-npu.so
I1105 14:40:01.633798    38 custom_device_load.cc:58] Skipped lib [/usr/local/lib/python3.10/dist-packages/paddle_custom_device/libpaddle-custom-npu.so]: no custom engine Plugin symbol in this lib.
I1105 14:40:01.636844    38 custom_kernel.cc:68] Succeed in loading 359 custom kernel(s) from loaded lib(s), will be used like native ones.
I1105 14:40:01.636998    38 init.cc:158] Finished in LoadCustomDevice with libs_path: [/usr/local/lib/python3.10/dist-packages/paddle_custom_device]
I1105 14:40:01.637033    38 init.cc:244] CustomDevice: npu, visible devices count: 2
Creating model: ('UVDoc', None)
Model files already exist. Using cached files. To redownload, please delete the directory manually: `/root/.paddlex/official_models/UVDoc`.
Creating model: ('PP-DocBlockLayout', None)
Model files already exist. Using cached files. To redownload, please delete the directory manually: `/root/.paddlex/official_models/PP-DocBlockLayout`.
Creating model: ('PP-DocLayout_plus-L', None)
Model files already exist. Using cached files. To redownload, please delete the directory manually: `/root/.paddlex/official_models/PP-DocLayout_plus-L`.
Creating model: ('PP-LCNet_x1_0_textline_ori', None)
Model files already exist. Using cached files. To redownload, please delete the directory manually: `/root/.paddlex/official_models/PP-LCNet_x1_0_textline_ori`.
Creating model: ('PP-OCRv5_server_det', None)
Model files already exist. Using cached files. To redownload, please delete the directory manually: `/root/.paddlex/official_models/PP-OCRv5_server_det`.
Creating model: ('PP-OCRv5_server_rec', None)
Model files already exist. Using cached files. To redownload, please delete the directory manually: `/root/.paddlex/official_models/PP-OCRv5_server_rec`.
Creating model: ('PP-LCNet_x1_0_table_cls', None)
Model files already exist. Using cached files. To redownload, please delete the directory manually: `/root/.paddlex/official_models/PP-LCNet_x1_0_table_cls`.
Creating model: ('SLANeXt_wired', None)
Model files already exist. Using cached files. To redownload, please delete the directory manually: `/root/.paddlex/official_models/SLANeXt_wired`.
Creating model: ('SLANet_plus', None)
Model files already exist. Using cached files. To redownload, please delete the directory manually: `/root/.paddlex/official_models/SLANet_plus`.
Creating model: ('RT-DETR-L_wired_table_cell_det', None)
Model files already exist. Using cached files. To redownload, please delete the directory manually: `/root/.paddlex/official_models/RT-DETR-L_wired_table_cell_det`.
Creating model: ('RT-DETR-L_wireless_table_cell_det', None)
Model files already exist. Using cached files. To redownload, please delete the directory manually: `/root/.paddlex/official_models/RT-DETR-L_wireless_table_cell_det`.
Creating model: ('PP-FormulaNet_plus-L', None)
Model files already exist. Using cached files. To redownload, please delete the directory manually: `/root/.paddlex/official_models/PP-FormulaNet_plus-L`.
Creating model: ('PP-Chart2Table', None)
Model files already exist. Using cached files. To redownload, please delete the directory manually: `/root/.paddlex/official_models/PP-Chart2Table`.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Loading configuration file /root/.paddlex/official_models/PP-Chart2Table/config.json
Loading weights file /root/.paddlex/official_models/PP-Chart2Table/model_state.pdparams
Loaded weights file from disk, setting weights to model.
All model checkpoint weights were used when initializing PPChart2TableInference.

All the weights of PPChart2TableInference were initialized from the model checkpoint at /root/.paddlex/official_models/PP-Chart2Table.
If your task is similar to the task the model of the checkpoint was trained on, you can already use PPChart2TableInference for predictions without further training.
Loading configuration file /root/.paddlex/official_models/PP-Chart2Table/generation_config.json
Connecting to https://paddle-model-ecology.bj.bcebos.com/paddlex/imgs/demo_image/pp_structure_v3_demo.png ...
Downloading pp_structure_v3_demo.png ...
[==================================================] 100.00%
Traceback (most recent call last):
  File "/root/demo.py", line 15, in <module>
    output = pipeline.predict(input=input_file)
  File "/usr/local/lib/python3.10/dist-packages/paddleocr/_pipelines/pp_structurev3.py", line 250, in predict
    return list(
  File "/usr/local/lib/python3.10/dist-packages/paddlex/inference/pipelines/_parallel.py", line 129, in predict
    yield from self._pipeline.predict(
  File "/usr/local/lib/python3.10/dist-packages/paddlex/inference/pipelines/layout_parsing/pipeline_v2.py", line 1008, in predict
    doc_preprocessor_results = list(
  File "/usr/local/lib/python3.10/dist-packages/paddlex/inference/pipelines/_parallel.py", line 129, in predict
    yield from self._pipeline.predict(
  File "/usr/local/lib/python3.10/dist-packages/paddlex/inference/pipelines/doc_preprocessor/pipeline.py", line 175, in predict
    output_imgs = [
  File "/usr/local/lib/python3.10/dist-packages/paddlex/inference/pipelines/doc_preprocessor/pipeline.py", line 175, in <listcomp>
    output_imgs = [
  File "/usr/local/lib/python3.10/dist-packages/paddlex/inference/models/base/predictor/base_predictor.py", line 273, in __call__
    yield from self.apply(input, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/paddlex/inference/models/base/predictor/base_predictor.py", line 330, in apply
    prediction = self.process(batch_data, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/paddlex/inference/models/image_unwarping/predictor.py", line 89, in process
    batch_preds = self.infer(x=x)
  File "/usr/local/lib/python3.10/dist-packages/paddlex/inference/models/common/static_infer.py", line 297, in __call__
    pred = self.infer(x)
  File "/usr/local/lib/python3.10/dist-packages/paddlex/inference/models/common/static_infer.py", line 260, in __call__
    self.predictor.run()
OSError: In user code:


    ExternalError:  ACL error, the error code is : 500001.  (at /paddle/backends/npu/kernels/funcs/npu_op_runner.cc:453)
      [operator < pd_kernel.phi_kernel > error]
```

### 🏃‍♂️ Environment (运行环境)

```
os: 银河麒麟V10 && 华为昇腾910B2
paddle-custom-npu        3.2.0
paddle2onnx              1.3.1
paddleocr                3.3.1
paddlepaddle             3.2.1
paddlex                  3.3.6

```

### 🌰 Minimal Reproducible Example (最小可复现问题的Demo)

为更快的帮您定位问题，推荐您用以下模板反馈：

1、出现问题时，您做了哪些操作？

首先我启动了docker 容器命令如下:
```
docker run --rm -it --name paddle-npu-dev \
  --privileged --network=host --shm-size=128G -w /root \
  -v "$(pwd)":/root \
  -v /usr/local/Ascend/driver:/usr/local/Ascend/driver \
  -v /usr/local/bin/npu-smi:/usr/local/bin/npu-smi \
  -v /usr/local/dcmi:/usr/local/dcmi \
  -e ASCEND_RT_VISIBLE_DEVICES="6,7" \
  ccr-2vdh3abv-pub.cnc.bj.baidubce.com/device/paddle-npu:cann80RC2-ubuntu20-npu-base-aarch64-gcc84 \
  /bin/bash
```
容器内执行了如下命令:
```
pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple
python -m pip install --upgrade pip && python -m pip install paddlepaddle==3.2.1 -i https://www.paddlepaddle.org.cn/packages/stable/cpu/ && \
    python -m pip install paddle-custom-npu==3.2.0 -i https://www.paddlepaddle.org.cn/packages/stable/npu/ && \
    python -m pip install "paddleocr[all]" && python -m pip install -r requirements.txt 

source /usr/local/Ascend/ascend-toolkit/set_env.sh
source /usr/local/Ascend/nnal/atb/set_env.sh
```
主要代码如下:
```
mport os

os.environ['FLAGS_npu_jit_compile'] = 'false'
os.environ['FLAGS_npu_scale_aclnn'] = 'True'
os.environ['FLAGS_npu_split_aclnn'] = 'True'
os.environ['FLAGS_use_stride_kernel'] = '0'

from pathlib import Path
from paddleocr import PPStructureV3

input_file = "https://paddle-model-ecology.bj.bcebos.com/paddlex/imgs/demo_image/pp_structure_v3_demo.png"
output_path = Path("./output")

pipeline = PPStructureV3(device="npu:0")
output = pipeline.predict(input=input_file)

markdown_list = []
markdown_images = []

for res in output:
    md_info = res.markdown
    markdown_list.append(md_info)
    markdown_images.append(md_info.get("markdown_images", {}))

markdown_texts = pipeline.concatenate_markdown_pages(markdown_list)

mkd_file_path = output_path / f"{Path(input_file).stem}.md"
mkd_file_path.parent.mkdir(parents=True, exist_ok=True)

with open(mkd_file_path, "w", encoding="utf-8") as f:
    f.write(markdown_texts)

for item in markdown_images:
    if item:
        for path, image in item.items():
            file_path = output_path / path
            file_path.parent.mkdir(parents=True, exist_ok=True)
            image.save(file_path)
```
然后运行`python demo.py ` 就报错如下

```

root@pm-a206:~# python demo.py 
Creating model: ('PP-LCNet_x1_0_doc_ori', None)
Model files already exist. Using cached files. To redownload, please delete the directory manually: `/root/.paddlex/official_models/PP-LCNet_x1_0_doc_ori`.
I1105 14:40:01.075873    38 init.cc:238] ENV [CUSTOM_DEVICE_ROOT]=/usr/local/lib/python3.10/dist-packages/paddle_custom_device
I1105 14:40:01.075919    38 init.cc:146] Try loading custom device libs from: [/usr/local/lib/python3.10/dist-packages/paddle_custom_device]
I1105 14:40:01.633749    38 custom_device_load.cc:51] Succeed in loading custom runtime in lib: /usr/local/lib/python3.10/dist-packages/paddle_custom_device/libpaddle-custom-npu.so
I1105 14:40:01.633798    38 custom_device_load.cc:58] Skipped lib [/usr/local/lib/python3.10/dist-packages/paddle_custom_device/libpaddle-custom-npu.so]: no custom engine Plugin symbol in this lib.
I1105 14:40:01.636844    38 custom_kernel.cc:68] Succeed in loading 359 custom kernel(s) from loaded lib(s), will be used like native ones.
I1105 14:40:01.636998    38 init.cc:158] Finished in LoadCustomDevice with libs_path: [/usr/local/lib/python3.10/dist-packages/paddle_custom_device]
I1105 14:40:01.637033    38 init.cc:244] CustomDevice: npu, visible devices count: 2
Creating model: ('UVDoc', None)
Model files already exist. Using cached files. To redownload, please delete the directory manually: `/root/.paddlex/official_models/UVDoc`.
Creating model: ('PP-DocBlockLayout', None)
Model files already exist. Using cached files. To redownload, please delete the directory manually: `/root/.paddlex/official_models/PP-DocBlockLayout`.
Creating model: ('PP-DocLayout_plus-L', None)
Model files already exist. Using cached files. To redownload, please delete the directory manually: `/root/.paddlex/official_models/PP-DocLayout_plus-L`.
Creating model: ('PP-LCNet_x1_0_textline_ori', None)
Model files already exist. Using cached files. To redownload, please delete the directory manually: `/root/.paddlex/official_models/PP-LCNet_x1_0_textline_ori`.
Creating model: ('PP-OCRv5_server_det', None)
Model files already exist. Using cached files. To redownload, please delete the directory manually: `/root/.paddlex/official_models/PP-OCRv5_server_det`.
Creating model: ('PP-OCRv5_server_rec', None)
Model files already exist. Using cached files. To redownload, please delete the directory manually: `/root/.paddlex/official_models/PP-OCRv5_server_rec`.
Creating model: ('PP-LCNet_x1_0_table_cls', None)
Model files already exist. Using cached files. To redownload, please delete the directory manually: `/root/.paddlex/official_models/PP-LCNet_x1_0_table_cls`.
Creating model: ('SLANeXt_wired', None)
Model files already exist. Using cached files. To redownload, please delete the directory manually: `/root/.paddlex/official_models/SLANeXt_wired`.
Creating model: ('SLANet_plus', None)
Model files already exist. Using cached files. To redownload, please delete the directory manually: `/root/.paddlex/official_models/SLANet_plus`.
Creating model: ('RT-DETR-L_wired_table_cell_det', None)
Model files already exist. Using cached files. To redownload, please delete the directory manually: `/root/.paddlex/official_models/RT-DETR-L_wired_table_cell_det`.
Creating model: ('RT-DETR-L_wireless_table_cell_det', None)
Model files already exist. Using cached files. To redownload, please delete the directory manually: `/root/.paddlex/official_models/RT-DETR-L_wireless_table_cell_det`.
Creating model: ('PP-FormulaNet_plus-L', None)
Model files already exist. Using cached files. To redownload, please delete the directory manually: `/root/.paddlex/official_models/PP-FormulaNet_plus-L`.
Creating model: ('PP-Chart2Table', None)
Model files already exist. Using cached files. To redownload, please delete the directory manually: `/root/.paddlex/official_models/PP-Chart2Table`.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Loading configuration file /root/.paddlex/official_models/PP-Chart2Table/config.json
Loading weights file /root/.paddlex/official_models/PP-Chart2Table/model_state.pdparams
Loaded weights file from disk, setting weights to model.
All model checkpoint weights were used when initializing PPChart2TableInference.

All the weights of PPChart2TableInference were initialized from the model checkpoint at /root/.paddlex/official_models/PP-Chart2Table.
If your task is similar to the task the model of the checkpoint was trained on, you can already use PPChart2TableInference for predictions without further training.
Loading configuration file /root/.paddlex/official_models/PP-Chart2Table/generation_config.json
Connecting to https://paddle-model-ecology.bj.bcebos.com/paddlex/imgs/demo_image/pp_structure_v3_demo.png ...
Downloading pp_structure_v3_demo.png ...
[==================================================] 100.00%
Traceback (most recent call last):
  File "/root/demo.py", line 15, in <module>
    output = pipeline.predict(input=input_file)
  File "/usr/local/lib/python3.10/dist-packages/paddleocr/_pipelines/pp_structurev3.py", line 250, in predict
    return list(
  File "/usr/local/lib/python3.10/dist-packages/paddlex/inference/pipelines/_parallel.py", line 129, in predict
    yield from self._pipeline.predict(
  File "/usr/local/lib/python3.10/dist-packages/paddlex/inference/pipelines/layout_parsing/pipeline_v2.py", line 1008, in predict
    doc_preprocessor_results = list(
  File "/usr/local/lib/python3.10/dist-packages/paddlex/inference/pipelines/_parallel.py", line 129, in predict
    yield from self._pipeline.predict(
  File "/usr/local/lib/python3.10/dist-packages/paddlex/inference/pipelines/doc_preprocessor/pipeline.py", line 175, in predict
    output_imgs = [
  File "/usr/local/lib/python3.10/dist-packages/paddlex/inference/pipelines/doc_preprocessor/pipeline.py", line 175, in <listcomp>
    output_imgs = [
  File "/usr/local/lib/python3.10/dist-packages/paddlex/inference/models/base/predictor/base_predictor.py", line 273, in __call__
    yield from self.apply(input, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/paddlex/inference/models/base/predictor/base_predictor.py", line 330, in apply
    prediction = self.process(batch_data, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/paddlex/inference/models/image_unwarping/predictor.py", line 89, in process
    batch_preds = self.infer(x=x)
  File "/usr/local/lib/python3.10/dist-packages/paddlex/inference/models/common/static_infer.py", line 297, in __call__
    pred = self.infer(x)
  File "/usr/local/lib/python3.10/dist-packages/paddlex/inference/models/common/static_infer.py", line 260, in __call__
    self.predictor.run()
OSError: In user code:


    ExternalError:  ACL error, the error code is : 500001.  (at /paddle/backends/npu/kernels/funcs/npu_op_runner.cc:453)
      [operator < pd_kernel.phi_kernel > error]
```

**Comment by tao-xiaoxin** [comment]
我又换了一个镜像
```
 docker run --rm -it --name paddle-npu-dev -v /mnt/nvme0n1/app_data/project/paddle:/root \
    --privileged --network=host --shm-size=128G -w=/root \
    -v /usr/local/Ascend/driver:/usr/local/Ascend/driver \
    -v /usr/local/bin/npu-smi:/usr/local/bin/npu-smi \
    -v /usr/local/dcmi:/usr/local/dcmi \
    -e ASCEND_RT_VISIBLE_DEVICES="0,1,2,3,4,5,6,7" \
    ccr-2vdh3abv-pub.cnc.bj.baidubce.com/device/paddle-npu:cann80T113-ubuntu20-npu-910b-base-$(uname -m)-gcc84 /bin/bash
```
报错如下:
```
root@pm-a206:~# python demo.py 
Creating model: ('PP-LCNet_x1_0_doc_ori', None)
Model files already exist. Using cached files. To redownload, please delete the directory manually: `/root/.paddlex/official_models/PP-LCNet_x1_0_doc_ori`.
I1105 16:24:18.967692  4910 init.cc:238] ENV [CUSTOM_DEVICE_ROOT]=/usr/local/lib/python3.10/dist-packages/paddle_custom_device
I1105 16:24:18.967743  4910 init.cc:146] Try loading custom device libs from: [/usr/local/lib/python3.10/dist-packages/paddle_custom_device]
I1105 16:24:19.212930  4910 custom_device_load.cc:51] Succeed in loading custom runtime in lib: /usr/local/lib/python3.10/dist-packages/paddle_custom_device/libpaddle-custom-npu.so
I1105 16:24:19.212989  4910 custom_device_load.cc:58] Skipped lib [/usr/local/lib/python3.10/dist-packages/paddle_custom_device/libpaddle-custom-npu.so]: no custom engine Plugin symbol in this lib.
I1105 16:24:19.216123  4910 custom_kernel.cc:68] Succeed in loading 359 custom kernel(s) from loaded lib(s), will be used like native ones.
I1105 16:24:19.216279  4910 init.cc:158] Finished in LoadCustomDevice with libs_path: [/usr/local/lib/python3.10/dist-packages/paddle_custom_device]
I1105 16:24:19.216310  4910 init.cc:244] CustomDevice: npu, visible devices count: 8
Creating model: ('UVDoc', None)
Model files already exist. Using cached files. To redownload, please delete the directory manually: `/root/.paddlex/official_models/UVDoc`.
Creating model: ('PP-DocBlockLayout', None)
Model files already exist. Using cached files. To redownload, please delete the directory manually: `/root/.paddlex/official_models/PP-DocBlockLayout`.


--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::framework::ThreadPoolTempl<paddle::framework::StlThreadEnvironment>::WorkerLoop(int)
1   paddle::framework::PirInterpreter::RunInstructionBaseAsync(unsigned long)
2   paddle::framework::PirInterpreter::RunInstructionBase(paddle::framework::InstructionBase*)
3   paddle::framework::PhiKernelInstruction::Run()
4   phi::KernelImpl<void (*)(phi::CustomContext const&, paddle::experimental::IntArrayBase<phi::DenseTensor> const&, paddle::experimental::ScalarBase<phi::DenseTensor> const&, phi::DataType, phi::DenseTensor*), &(void custom_kernel::FullKernel<float, phi::CustomContext>(phi::CustomContext const&, paddle::experimental::IntArrayBase<phi::DenseTensor> const&, paddle::experimental::ScalarBase<phi::DenseTensor> const&, phi::DataType, phi::DenseTensor*))>::Compute(phi::KernelContext*)
5   void custom_kernel::FullKernel<float, phi::CustomContext>(phi::CustomContext const&, paddle::experimental::IntArrayBase<phi::DenseTensor> const&, paddle::experimental::ScalarBase<phi::DenseTensor> const&, phi::DataType, phi::DenseTensor*)
6   aclnnInplaceFillScalarGetWorkspaceSize
7   l0op::ViewCopy(aclTensor const*, aclTensor const*, aclOpExecutor*)
8   l0op::CheckViewCopyParams(aclTensor const*, aclTensor const*)
9   aclTensor::GetDataType() const

----------------------
Error Message Summary:
----------------------
FatalError: `Segmentation fault` is detected by the operating system.
  [TimeInfo: *** Aborted at 1762331060 (unix time) try "date -d @1762331060" if you are using GNU date ***]
  [SignalInfo: *** SIGSEGV (@0x132e) received by PID 4910 (TID 0xfff873fff1e0) from PID 4910 ***]

Segmentation fault (core dumped)
```

**Comment by tao-xiaoxin** [comment]
然后我有换了paddle 版本也不行：
~~~
oot@pm-a206:~# # 注意需要先安装飞桨 cpu 版本
root@pm-a206:~# python -m pip install paddlepaddle==3.0.0.dev20250527 -i https://www.paddlepaddle.org.cn/packages/nightly/cpu
python -m pip install paddle-custom-npu==3.0.0.dev20250527 -i https://www.paddlepaddle.org.cn/packages/nightly/npuLooking in indexes: https://www.paddlepaddle.org.cn/packages/nightly/cpu
Collecting paddlepaddle==3.0.0.dev20250527
  Downloading https://paddle-whl.bj.bcebos.com/nightly/cpu/paddlepaddle/paddlepaddle-3.0.0.dev20250527-cp310-cp310-linux_aarch64.whl (92.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 92.2/92.2 MB 8.3 MB/s  0:00:11
Requirement already satisfied: httpx in /usr/local/lib/python3.10/dist-packages (from paddlepaddle==3.0.0.dev20250527) (0.28.1)
Requirement already satisfied: numpy>=1.21 in /usr/local/lib/python3.10/dist-packages (from paddlepaddle==3.0.0.dev20250527) (1.26.4)
Requirement already satisfied: protobuf>=3.20.2 in /usr/local/lib/python3.10/dist-packages (from paddlepaddle==3.0.0.dev20250527) (5.29.3)
Requirement already satisfied: Pillow in /usr/local/lib/python3.10/dist-packages (from paddlepaddle==3.0.0.dev20250527) (11.1.0)
Requirement already satisfied: decorator in /usr/local/lib/python3.10/dist-packages (from paddlepaddle==3.0.0.dev20250527) (5.1.1)
Requirement already satisfied: opt-einsum==3.3.0 in /usr/local/lib/python3.10/dist-packages (from paddlepaddle==3.0.0.dev20250527) (3.3.0)
Requirement already satisfied: networkx in /usr/local/lib/python3.10/dist-packages (from paddlepaddle==3.0.0.dev20250527) (3.4.2)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.10/dist-packages (from paddlepaddle==3.0.0.dev20250527) (4.12.2)
Requirement already satisfied: anyio in /usr/local/lib/python3.10/dist-packages (from httpx->paddlepaddle==3.0.0.dev20250527) (4.8.0)
Requirement already satisfied: certifi in /usr/lib/python3/dist-packages (from httpx->paddlepaddle==3.0.0.dev20250527) (2019.11.28)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.10/dist-packages (from httpx->paddlepaddle==3.0.0.dev20250527) (1.0.7)
Requirement already satisfied: idna in /usr/lib/python3/dist-packages (from httpx->paddlepaddle==3.0.0.dev20250527) (2.8)
Requirement already satisfied: h11<0.15,>=0.13 in /usr/local/lib/python3.10/dist-packages (from httpcore==1.*->httpx->paddlepaddle==3.0.0.dev20250527) (0.14.0)
Requirement already satisfied: exceptiongroup>=1.0.2 in /usr/local/lib/python3.10/dist-packages (from anyio->httpx->paddlepaddle==3.0.0.dev20250527) (1.2.2)
Requirement already satisfied: sniffio>=1.1 in /usr/local/lib/python3.10/dist-packages (from anyio->httpx->paddlepaddle==3.0.0.dev20250527) (1.3.1)
Installing collected packages: paddlepaddle
  Attempting uninstall: paddlepaddle
    Found existing installation: paddlepaddle 3.2.1
    Uninstalling paddlepaddle-3.2.1:
      Successfully uninstalled paddlepaddle-3.2.1
Successfully installed paddlepaddle-3.0.0.dev20250527
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager, possibly rendering your system unusable. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv. Use the --root-user-action option if you know what you are doing and want to suppress this warning.
root@pm-a206:~# python -m pip install paddle-custom-npu==3.0.0.dev20250527 -i https://www.paddlepaddle.org.cn/packages/nightly/npu
Looking in indexes: https://www.paddlepaddle.org.cn/packages/nightly/npu
Collecting paddle-custom-npu==3.0.0.dev20250527
  Downloading https://paddle-whl.bj.bcebos.com/nightly/npu/paddle-custom-npu/paddle_custom_npu-3.0.0.dev20250527-cp310-cp310-linux_aarch64.whl (5.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.4/5.4 MB 91.9 MB/s  0:00:00
Installing collected packages: paddle-custom-npu
  Attempting uninstall: paddle-custom-npu
    Found existing installation: paddle-custom-npu 3.2.0
    Uninstalling paddle-custom-npu-3.2.0:
      Successfully uninstalled paddle-custom-npu-3.2.0
Successfully installed paddle-custom-npu-3.0.0.dev20250527
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager, possibly rendering your system unusable. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv. Use the --root-user-action option if you know what you are doing and want to suppress this warning.
root@pm-a206:~# python -c "import paddle; paddle.utils.run_check()"
I1105 16:28:51.499001  7130 init.cc:238] ENV [CUSTOM_DEVICE_ROOT]=/usr/local/lib/python3.10/dist-packages/paddle_custom_device
I1105 16:28:51.499051  7130 init.cc:146] Try loading custom device libs from: [/usr/local/lib/python3.10/dist-packages/paddle_custom_device]
I1105 16:28:51.734123  7130 custom_device_load.cc:51] Succeed in loading custom runtime in lib: /usr/local/lib/python3.10/dist-packages/paddle_custom_device/libpaddle-custom-npu.so
I1105 16:28:51.734179  7130 custom_device_load.cc:58] Skipped lib [/usr/local/lib/python3.10/dist-packages/paddle_custom_device/libpaddle-custom-npu.so]: no custom engine Plugin symbol in this lib.
I1105 16:28:51.736300  7130 custom_kernel.cc:68] Succeed in loading 359 custom kernel(s) from loaded lib(s), will be used like native ones.
I1105 16:28:51.736506  7130 init.cc:158] Finished in LoadCustomDevice with libs_path: [/usr/local/lib/python3.10/dist-packages/paddle_custom_device]
I1105 16:28:51.736547  7130 init.cc:244] CustomDevice: npu, visible devices count: 8
Running verify PaddlePaddle program ... 
I1105 16:28:52.329660  7130 pir_interpreter.cc:1490] New Executor is Running ...
I1105 16:28:52.332337  7130 pir_interpreter.cc:1513] pir interpreter is running by multi-thread mode ...


--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::framework::ThreadPoolTempl<paddle::framework::StlThreadEnvironment>::WorkerLoop(int)
1   paddle::framework::PirInterpreter::RunInstructionBaseAsync(unsigned long)
2   paddle::framework::PirInterpreter::RunInstructionBase(paddle::framework::InstructionBase*)
3   paddle::framework::PhiKernelInstruction::Run()
4   phi::KernelImpl<void (*)(phi::CustomContext const&, paddle::experimental::IntArrayBase<phi::DenseTensor> const&, paddle::experimental::ScalarBase<phi::DenseTensor> const&, phi::DataType, phi::DenseTensor*), &(void custom_kernel::FullKernel<float, phi::CustomContext>(phi::CustomContext const&, paddle::experimental::IntArrayBase<phi::DenseTensor> const&, paddle::experimental::ScalarBase<phi::DenseTensor> const&, phi::DataType, phi::DenseTensor*))>::Compute(phi::KernelContext*)
5   void custom_kernel::FullKernel<float, phi::CustomContext>(phi::CustomContext const&, paddle::experimental::IntArrayBase<phi::DenseTensor> const&, paddle::experimental::ScalarBase<phi::DenseTensor> const&, phi::DataType, phi::DenseTensor*)
6   aclnnInplaceFillScalarGetWorkspaceSize
7   l0op::ViewCopy(aclTensor const*, aclTensor const*, aclOpExecutor*)
8   l0op::CheckViewCopyParams(aclTensor const*, aclTensor const*)
9   aclTensor::GetDataType() const

----------------------
Error Message Summary:
----------------------
FatalError: `Segmentation fault` is detected by the operating system.
  [TimeInfo: *** Aborted at 1762331332 (unix time) try "date -d @1762331332" if you are using GNU date ***]
  [SignalInfo: *** SIGSEGV (@0x1bda) received by PID 7130 (TID 0xfffba7fff1e0) from PID 7130 ***]

Segmentation fault (core dumped)
~~~

**Comment by tao-xiaoxin** [comment]
当前环境如下：
```
root@pm-a206:~# pip list | grep paddle 
paddle-custom-npu        3.0.0.dev20250527
paddle2onnx              1.3.1
paddleocr                3.3.1
paddlepaddle             3.0.0.dev20250527
paddlex                  3.3.6                /root/PaddleX
```
硬件信息如下：
~~~
root@pm-a206:~# npu-smi info
+------------------------------------------------------------------------------------------------+
| npu-smi 24.1.0.3                 Version: 24.1.0.3                                             |
+---------------------------+---------------+----------------------------------------------------+
| NPU   Name                | Health        | Power(W)    Temp(C)           Hugepages-Usage(page)|
| Chip                      | Bus-Id        | AICore(%)   Memory-Usage(MB)  HBM-Usage(MB)        |
+===========================+===============+====================================================+
| 0     910B2               | OK            | 94.5        40                0    / 0             |
| 0                         | 0000:C1:00.0  | 0           0    / 0          3590 / 65536         |
+===========================+===============+====================================================+
| 1     910B2               | OK            | 93.1        40                0    / 0             |
| 0                         | 0000:01:00.0  | 0           0    / 0          3457 / 65536         |
+===========================+===============+====================================================+
| 2     910B2               | OK            | 95.7        40                0    / 0             |
| 0                         | 0000:C2:00.0  | 0           0    / 0          3458 / 65536         |
+===========================+===============+====================================================+
| 3     910B2               | OK            | 93.4        41                0    / 0             |
| 0                         | 0000:02:00.0  | 0           0    / 0          3456 / 65536         |
+===========================+===============+====================================================+
| 4     910B2               | OK            | 96.0        40                0    / 0             |
| 0                         | 0000:81:00.0  | 0           0    / 0          3457 / 65536         |
+===========================+===============+====================================================+
| 5     910B2               | OK            | 97.0        41                0    / 0             |
| 0                         | 0000:41:00.0  | 0           0    / 0          3458 / 65536         |
+===========================+===============+====================================================+
| 6     910B2               | OK            | 94.4        40                0    / 0             |
| 0                         | 0000:82:00.0  | 0           0    / 0          3583 / 65536         |
+===========================+===============+====================================================+
| 7     910B2               | OK            | 99.3        42                0    / 0             |
| 0                         | 0000:42:00.0  | 0           0    / 0          3458 / 65536         |
+===========================+===============+====================================================+
+---------------------------+---------------+----------------------------------------------------+
| NPU     Chip              | Process id    | Process name             | Process memory(MB)      |
+===========================+===============+====================================================+
| 0       0                 | 730315        |                          | 109                     |
+===========================+===============+====================================================+
| 1       0                 | 730305        |                          | 113                     |
+===========================+===============+====================================================+
| 2       0                 | 730300        |                          | 113                     |
+===========================+===============+====================================================+
| 3       0                 | 730329        |                          | 113                     |
+===========================+===============+====================================================+
| 4       0                 | 730335        |                          | 113                     |
+===========================+===============+====================================================+
| 5       0                 | 730307        |                          | 113                     |
+===========================+===============+====================================================+
| 6       0                 | 730325        |                          | 109                     |
+===========================+===============+====================================================+
| 7       0                 | 730320        |                          | 113                     |
+================
~~~

**Comment by tao-xiaoxin** [comment]
然后我又换了一个docker 镜像，又出现了和刚开始同样的错误：
~~~
[root@pm-a206 paddle]# # 考如下命令启动容器，ASCEND_RT_VISIBLE_DEVICES 可指定可见的 NPU 卡号
[root@pm-a206 paddle]# docker run --rm -it --name paddle-npu-dev -v $(pwd):/work \
>     --privileged --network=host --shm-size=128G -w=/work \
>     -v /usr/local/Ascend/driver:/usr/local/Ascend/driver \
>     -v /usr/local/bin/npu-smi:/usr/local/bin/npu-smi \
>     -v /usr/local/dcmi:/usr/local/dcmi \
>     -e ASCEND_RT_VISIBLE_DEVICES="0,1,2,3,4,5,6,7" \
>     ccr-2vdh3abv-pub.cnc.bj.baidubce.com/device/paddle-npu:cann800-ubuntu20-npu-910b-base-$(uname -m)-gcc84 /bin/bash
root@pm-a206:/work# # 先安装飞桨 CPU 安装包
root@pm-a206:/work# pip install paddlepaddle -i https://www.paddlepaddle.org.cn/packages/nightly/cpu

# 再安装飞桨 NPU 插件包
pip install paddle-custom-npu -i https://www.paddlepaddle.org.cn/packages/nightly/npuLooking in indexes: https://www.paddlepaddle.org.cn/packages/nightly/cpu
Collecting paddlepaddle
  Downloading https://paddle-whl.bj.bcebos.com/nightly/cpu/paddlepaddle/paddlepaddle-3.3.0.dev20251104-cp310-cp310-linux_aarch64.whl (90.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 90.3/90.3 MB 8.3 MB/s eta 0:00:00
Requirement already satisfied: httpx in /usr/local/lib/python3.10/dist-packages (from paddlepaddle) (0.28.1)
Requirement already satisfied: numpy>=1.21 in /usr/local/lib/python3.10/dist-packages (from paddlepaddle) (2.1.3)
Requirement already satisfied: protobuf>=3.20.2 in /usr/local/lib/python3.10/dist-packages (from paddlepaddle) (5.29.3)
Requirement already satisfied: Pillow in /usr/local/lib/python3.10/dist-packages (from paddlepaddle) (11.1.0)
Requirement already satisfied: opt-einsum==3.3.0 in /usr/local/lib/python3.10/dist-packages (from paddlepaddle) (3.3.0)
Requirement already satisfied: networkx in /usr/local/lib/python3.10/dist-packages (from paddlepaddle) (3.4.2)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.10/dist-packages (from paddlepaddle) (4.12.2)
Collecting safetensors>=0.6.0 (from paddlepaddle)
  Downloading https://paddle-whl.bj.bcebos.com/nightly/cpu/safetensors/safetensors-0.6.2-cp38-abi3-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (473 kB)
Requirement already satisfied: anyio in /usr/local/lib/python3.10/dist-packages (from httpx->paddlepaddle) (4.8.0)
Requirement already satisfied: certifi in /usr/lib/python3/dist-packages (from httpx->paddlepaddle) (2019.11.28)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.10/dist-packages (from httpx->paddlepaddle) (1.0.7)
Requirement already satisfied: idna in /usr/lib/python3/dist-packages (from httpx->paddlepaddle) (2.8)
Requirement already satisfied: h11<0.15,>=0.13 in /usr/local/lib/python3.10/dist-packages (from httpcore==1.*->httpx->paddlepaddle) (0.14.0)
Requirement already satisfied: exceptiongroup>=1.0.2 in /usr/local/lib/python3.10/dist-packages (from anyio->httpx->paddlepaddle) (1.2.2)
Requirement already satisfied: sniffio>=1.1 in /usr/local/lib/python3.10/dist-packages (from anyio->httpx->paddlepaddle) (1.3.1)
Installing collected packages: safetensors, paddlepaddle
Successfully installed paddlepaddle-3.3.0.dev20251104 safetensors-0.6.2
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager, possibly rendering your system unusable. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv. Use the --root-user-action option if you know what you are doing and want to suppress this warning.
root@pm-a206:/work# 
root@pm-a206:/work# # 再安装飞桨 NPU 插件包
root@pm-a206:/work# pip install paddle-custom-npu -i https://www.paddlepaddle.org.cn/packages/nightly/npu
Looking in indexes: https://www.paddlepaddle.org.cn/packages/nightly/npu
Collecting paddle-custom-npu
  Downloading https://paddle-whl.bj.bcebos.com/nightly/npu/paddle-custom-npu/paddle_custom_npu-3.0.0.dev20251104-cp310-cp310-linux_aarch64.whl (5.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.4/5.4 MB 3.4 MB/s eta 0:00:00
Requirement already satisfied: pandas>=1.4.3 in /usr/local/lib/python3.10/dist-packages (from paddle-custom-npu) (2.2.3)
Requirement already satisfied: numpy>=1.22.4 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.4.3->paddle-custom-npu) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.4.3->paddle-custom-npu) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.4.3->paddle-custom-npu) (2025.1)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.4.3->paddle-custom-npu) (2025.1)
Requirement already satisfied: six>=1.5 in /usr/lib/python3/dist-packages (from python-dateutil>=2.8.2->pandas>=1.4.3->paddle-custom-npu) (1.14.0)
Installing collected packages: paddle-custom-npu
Successfully installed paddle-custom-npu-3.0.0.dev20251104
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager, possibly rendering your system unusable. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv. Use the --root-user-action option if you know what you are doing and want to suppress this warning.
root@pm-a206:/work# # 检查当前安装版本
root@pm-a206:/work# python -c "import paddle_custom_device; paddle_custom_device.npu.version()"
I1105 17:22:34.707051    28 init.cc:238] ENV [CUSTOM_DEVICE_ROOT]=/usr/local/lib/python3.10/dist-packages/paddle_custom_device
I1105 17:22:34.707099    28 init.cc:146] Try loading custom device libs from: [/usr/local/lib/python3.10/dist-packages/paddle_custom_device]
I1105 17:22:35.378541    28 custom_device_load.cc:51] Succeed in loading custom runtime in lib: /usr/local/lib/python3.10/dist-packages/paddle_custom_device/libpaddle-custom-npu.so
I1105 17:22:35.378595    28 custom_device_load.cc:58] Skipped lib [/usr/local/lib/python3.10/dist-packages/paddle_custom_device/libpaddle-custom-npu.so]: no custom engine Plugin symbol in this lib.
I1105 17:22:35.380762    28 custom_kernel.cc:68] Succeed in loading 359 custom kernel(s) from loaded lib(s), will be used like native ones.
I1105 17:22:35.380935    28 init.cc:158] Finished in LoadCustomDevice with libs_path: [/usr/local/lib/python3.10/dist-packages/paddle_custom_device]
I1105 17:22:35.380971    28 init.cc:244] CustomDevice: npu, visible devices count: 8
version: 3.0.0.dev20251104
commit: f4fb86db780d40a7d434155a638f05abf59708b9
custom_op commit: f4fb86db780d40a7d434155a638f05abf59708b9
cann: 8.0.0
root@pm-a206:/work# # 飞桨基础健康检查
root@pm-a206:/work# python -c "import paddle; paddle.utils.run_check()"
I1105 17:22:45.072770   293 init.cc:238] ENV [CUSTOM_DEVICE_ROOT]=/usr/local/lib/python3.10/dist-packages/paddle_custom_device
I1105 17:22:45.072820   293 init.cc:146] Try loading custom device libs from: [/usr/local/lib/python3.10/dist-packages/paddle_custom_device]
I1105 17:22:45.749735   293 custom_device_load.cc:51] Succeed in loading custom runtime in lib: /usr/local/lib/python3.10/dist-packages/paddle_custom_device/libpaddle-custom-npu.so
I1105 17:22:45.749792   293 custom_device_load.cc:58] Skipped lib [/usr/local/lib/python3.10/dist-packages/paddle_custom_device/libpaddle-custom-npu.so]: no custom engine Plugin symbol in this lib.
I1105 17:22:45.752956   293 custom_kernel.cc:68] Succeed in loading 359 custom kernel(s) from loaded lib(s), will be used like native ones.
I1105 17:22:45.753113   293 init.cc:158] Finished in LoadCustomDevice with libs_path: [/usr/local/lib/python3.10/dist-packages/paddle_custom_device]
I1105 17:22:45.753147   293 init.cc:244] CustomDevice: npu, visible devices count: 8
Running verify PaddlePaddle program ... 
/usr/local/lib/python3.10/dist-packages/paddle/pir/math_op_patch.py:240: UserWarning: Tensor do not have 'place' interface for pir graph mode, try not to use it. None will be returned.
  warnings.warn(
I1105 17:22:46.386406   293 pir_interpreter.cc:1524] New Executor is Running ...
I1105 17:22:46.389787   293 pir_interpreter.cc:1547] pir interpreter is running by multi-thread mode ...
/usr/local/lib/python3.10/dist-packages/paddle/utils/install_check.py:109: UserWarning: The API 'paddle.nn.Linear' may behave differently from its PyTorch counterpart. Refer to the compatibility guide for details:
https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/guides/model_convert/convert_from_pytorch/pytorch_api_mapping_cn.html#api
  linear = paddle.nn.Linear(
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.10/dist-packages/paddle/utils/install_check.py", line 274, in run_check
    _run_dygraph_single(use_cuda, use_xpu, use_custom, custom_device_name)
  File "/usr/local/lib/python3.10/dist-packages/paddle/utils/install_check.py", line 120, in _run_dygraph_single
    opt.step()
  File "/usr/local/lib/python3.10/dist-packages/paddle/base/dygraph/base.py", line 389, in __impl__
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/paddle/base/wrapped_decorator.py", line 50, in wrapper
    return decorated(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/paddle/base/framework.py", line 742, in __impl__
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/paddle/optimizer/adam.py", line 526, in step
    optimize_ops = self._apply_optimize(
  File "/usr/local/lib/python3.10/dist-packages/paddle/optimizer/optimizer.py", line 1699, in _apply_optimize
    optimize_ops = self._create_optimization_pass(
  File "/usr/local/lib/python3.10/dist-packages/paddle/optimizer/optimizer.py", line 1368, in _create_optimization_pass
    self._append_optimize_op(
  File "/usr/local/lib/python3.10/dist-packages/paddle/optimizer/adam.py", line 387, in _append_optimize_op
    _, _, _, _, _, _, _ = _C_ops.adam_(
OSError: (External)  ACL error, the error code is : 500001.  (at /paddle/backends/npu/kernels/funcs/npu_op_runner.cc:456)

root@pm-a206:/work# pip list | grep paddle 
paddle-custom-npu      3.0.0.dev20251104
paddle2onnx            1.3.1
paddlepaddle           3.3.0.dev20251104
root@pm-a206:/work# 
~~~

**Comment by tao-xiaoxin** [comment]
已解决，安装这个指定版本依赖包即可：
~~~
python -m pip install numpy==1.26.4
python -m pip install opencv-python==3.4.18.65
~~~
