### ISSUE TITLE
根据官方快速安装后（docker），无法运行style-text

### ISSUE THREAD

**Issue by sjtugzx** [PaddlePaddle/PaddleOCR#1734]
OSError: (External)  Cuda error(35), CUDA driver version is insufficient for CUDA runtime version.
  [Advise: This indicates that the installed NVIDIA CUDA driver is older than the CUDA runtime library. This is not a supported configuration.Users should install an updated NVIDIA display driver to allow the application to run.] (at /paddle/paddle/fluid/platform/gpu_info.cc:78)
  [Hint: If you need C++ stacktraces for debugging, please set `FLAGS_call_stack_level=2`.]
  [operator < gaussian_random > error]

![image](https://user-images.githubusercontent.com/20066885/104449417-8b675000-55d9-11eb-99d9-d8ed762c9159.png)

![image](https://user-images.githubusercontent.com/20066885/104449446-96ba7b80-55d9-11eb-862e-c55c35fba7b4.png)

cuda-10.1版本是完全可以在目前driver版本上跑的
请问应该怎么处理

**Comment by littletomatodonkey** [comment]
你好，卸载paddle之后，重装一下呢？版本是paddlepaddle-gpu==2.0.0rc1

**Comment by sjtugzx** [comment]
> 你好，卸载paddle之后，重装一下呢？版本是paddlepaddle-gpu==2.0.0rc1

已经重装了3-4此，这个问题一直无法解决，我本机安装的cuda版本10.1 （nvcc -V），通过conda更改python虚拟环境cudatoolkit，cudnn （适配硬件driver） 仍无法解决。我不是很确定这个更新后的style-text是不是真的能用

**Comment by TingquanGao** [comment]
运行代码`python`进入python环境，然后运行以下代码检查paddle安装情况：
```
import paddle
paddle.fluid.install_check.run_check()
```
怀疑是Paddle版本不兼容问题。

**Comment by sjtugzx** [comment]
> 运行代码`python`进入python环境，然后运行以下代码检查paddle安装情况：
> 
> ```python
> import paddle
> paddle.fluid.install_check.run_check()
> ```
> 
> 怀疑是Paddle版本不兼容问题。

你好，这个看起来确实有问题。
![image](https://user-images.githubusercontent.com/20066885/104451850-14cc5180-55dd-11eb-8ae5-5adebb2da46b.png)

但是我在安装paddlepaddle-gpu的时候是按照快速安装指南操作的“ pip install paddlepaddle-gpu==2.0.0rc1 -i https://mirror.baidu.com/pypi/simple”

**Comment by LDOUBLEV** [comment]
你用的是哪一个docker image呢，创建docker容器用的命令是什么，发来看下吧

**Comment by sjtugzx** [comment]
> 你用的是哪一个docker image呢，创建docker容器用的命令是什么，发来看下吧，建议用下面的指令创建docker：
> 
> ```
> sudo nvidia-docker run --name ppocr -v $PWD:/paddle --shm-size=64G --network=host -it paddlepaddle/paddle:latest-dev-cuda10.1-cudnn7-gcc82 /bin/bash
> ```
> 
> --shm-size=64G 是共享内存大小，建议大于等于8G

你好使用的是目前官网提供的指令“sudo nvidia-docker run --name ppocr -v $PWD:/paddle --shm-size=64G --network=host -it paddlepaddle/paddle:latest-dev-cuda10.1-cudnn7-gcc82 /bin/bash”

**Comment by TingquanGao** [comment]
可以提供一下GCC版本吗？可以使用以下命令：
```shell
gcc --version
```

**Comment by sjtugzx** [comment]
> 可以提供一下GCC版本吗？可以使用以下命令：
> 
> ```shell
> gcc --version
> ```
gcc (GCC) 8.2.0

**Comment by LDOUBLEV** [comment]
你留个邮箱，我把我的paddle whl包发你试试

**Comment by sjtugzx** [comment]
> 你留个邮箱，我把我的paddle whl包发你试试

troykuo@outlook.com
THX

**Comment by sjtugzx** [comment]
大家好，目前问题解决了。通过卸载指南提供的paddlepaddle-gpu
![image](https://user-images.githubusercontent.com/20066885/104454883-7a224180-55e1-11eb-89a1-42c13f7533ae.png)
在百度社区搜索paddlepaddle-gpu后，根据如下指令重装paddlepaddle-gpu后不再报错
![image](https://user-images.githubusercontent.com/20066885/104454967-98883d00-55e1-11eb-87d2-d6f23e513d15.png)

[http://ai.baidu.com/forum/topic/show/980081](url)

**Comment by LDOUBLEV** [comment]
你试下能否用GPU，paddlepaddle=2.0.0rc1可能是CPU版本

**Comment by sjtugzx** [comment]
> 你试下能否用GPU，paddlepaddle=2.0.0rc1可能是CPU版本

CPU版本可以使用，GPU版本不能使用还是报runtime的错。而且按装了您给我发送的gpu版本的paddlepaddle仍然报错不能使用。

**Comment by Kraken000** [comment]
您好，请问解决这个问题了吗？
我也同样报的这个错误
系统版本 Red Hat Enterprise Linux Server release 7.7 (Maipo) 
NVIDIA Driver 版本 418.88 
paddle版本 2.0.0rc1

 [Advise: This indicates that the installed NVIDIA CUDA driver is older than the CUDA runtime library. This is not a supported configuration.Users should install an updated NVIDIA display driver to allow the application to run.] (at /paddle/paddle/fluid/platform/gpu_info.cc:78)

**Comment by suparek** [comment]
> > 你试下能否用GPU，paddlepaddle=2.0.0rc1可能是CPU版本
> 
> CPU版本可以使用，GPU版本不能使用还是报runtime的错。而且按装了您给我发送的gpu版本的paddlepaddle仍然报错不能使用。

我也是报一样的错误，请问题主解决了吗？

**Comment by suparek** [comment]
> > > 你试下能否用GPU，paddlepaddle=2.0.0rc1可能是CPU版本
> > 
> > 
> > CPU版本可以使用，GPU版本不能使用还是报runtime的错。而且按装了您给我发送的gpu版本的paddlepaddle仍然报错不能使用。
> 
> 我也是报一样的错误，请问题主解决了吗？

我用的 CUDA Version 10.1.243

**Comment by sjtugzx** [comment]
> > > 你试下能否用GPU，paddlepaddle=2.0.0rc1可能是CPU版本
> > 
> > 
> > CPU版本可以使用，GPU版本不能使用还是报runtime的错。而且按装了您给我发送的gpu版本的paddlepaddle仍然报错不能使用。
> 
> 我也是报一样的错误，请问题主解决了吗？

没有解决

**Comment by kealennieh** [comment]
请问这个问题有进展了么？我这边也报同样的问题。谢谢

**Comment by kealennieh** [comment]
这个问题可能是宿主机的driver比较低的原因，我降低了cuda版本，从10.1降到10.0，并且采用官方安装方法 python -m pip install paddlepaddle-gpu==2.0.1.post100 -f https://paddlepaddle.org.cn/whl/mkl/stable.html 以后，就没有出现这个问题了～
