### ISSUE TITLE
PaddleOCR-VL (PaddleOCRVL) hangs indefinitely on GPU — infinite `ioctl` loop in VRAM allocator

### ISSUE THREAD

**Issue by lbm364dl** [PaddlePaddle/PaddleOCR#17693]
### 🔎 Search before asking

- [x] I have searched the PaddleOCR [Docs](https://paddlepaddle.github.io/PaddleOCR/) and found no similar bug report.
- [x] I have searched the PaddleOCR [Issues](https://github.com/PaddlePaddle/PaddleOCR/issues) and found no similar bug report.
- [x] I have searched the PaddleOCR [Discussions](https://github.com/PaddlePaddle/PaddleOCR/discussions) and found no similar bug report.

### 🐛 Bug (问题描述)

I had this problem and was able to solve it. I don't really know if this is an issue, but I wanted to create it in case it happens to another person. Since I'm not very familiar with what happened, apologies for AI usage. The rest of the text below is an AI generated report based on my feedback.

### Bug Description

When running `PaddleOCRVL` with `device="gpu:0"`, the inference call (`pipeline.predict(...)`) **hangs indefinitely**. The process never completes and shows 0% GPU utilization in `nvidia-smi`. No error or timeout is raised.

Using `strace` on the stuck Python process reveals an **infinite loop** of the same `ioctl` call:

```
ioctl(9, _IOC(_IOC_READ|_IOC_WRITE, 0x46, 0x2a, 0x20), 0x7ffd08752fa0) = 0
ioctl(9, _IOC(_IOC_READ|_IOC_WRITE, 0x46, 0x2a, 0x20), 0x7ffd08752fa0) = 0
ioctl(9, _IOC(_IOC_READ|_IOC_WRITE, 0x46, 0x2a, 0x20), 0x7ffd08752fa0) = 0
... (repeats forever)
```

This `ioctl` corresponds to NVIDIA's `NV_ESC_RM_CONTROL` — the PaddlePaddle memory allocator is stuck in an infinite retry loop trying to allocate or grow GPU memory.

### Root Cause

PaddlePaddle's default GPU memory allocator strategy (`auto_growth`) appears to enter an infinite retry loop when interacting with certain GPU driver/hardware combinations. The allocator repeatedly issues `ioctl` calls to the NVIDIA kernel module to request VRAM but never succeeds or gives up.

### Workaround / Fix

Setting the environment variable **before** importing PaddlePaddle:

```python
import os
os.environ["FLAGS_allocator_strategy"] = "naive_best_fit"
```

Or from the shell:

```bash
export FLAGS_allocator_strategy=naive_best_fit
python my_script.py
```

This switches PaddlePaddle to the `naive_best_fit` allocator which pre-allocates GPU memory in large chunks instead of growing incrementally, completely avoiding the infinite `ioctl` loop.

**With this fix, inference completes normally** — model initialization takes ~2 seconds and inference ~14–50 seconds depending on image size (previously it would hang forever).

### 🏃‍♂️ Environment (运行环境)

| Component | Version |
|---|---|
| **OS** | Ubuntu 24.04.2 LTS |
| **Kernel** | 6.14.0-37-generic |
| **GPU** | NVIDIA RTX A2000 12 GB |
| **NVIDIA Driver** | 580.126.09 |
| **CUDA (PaddlePaddle build)** | 12.6 |
| **cuDNN** | 9.5.1 |
| **PaddlePaddle** | 3.3.0 (GPU, CUDA 12.6) |
| **PaddleOCR** | 3.4.0 |
| **PaddleX** | 3.4.1 |
| **Python** | 3.10 |

### 🌰 Minimal Reproducible Example (最小可复现问题的Demo)

1. Set up the environment described below
2. Run the following minimal script **without** the workaround:

```python
import os
# os.environ["FLAGS_allocator_strategy"] = "naive_best_fit"  # <-- uncomment to fix

os.environ["PADDLE_PDX_DISABLE_MODEL_SOURCE_CHECK"] = "True"

import paddle
from paddleocr import PaddleOCRVL

print(f"PaddlePaddle {paddle.__version__}, CUDA: {paddle.is_compiled_with_cuda()}, GPUs: {paddle.device.cuda.device_count()}")

pipeline = PaddleOCRVL(device="gpu:0")
print("Model loaded, starting inference...")

output = pipeline.predict("any_image.png")  # <-- hangs here forever
print("Done")  # <-- never reached
```

3. Observe the process hangs at inference. Attach `strace`:
   ```bash
   sudo strace -p <PID>
   ```
   You will see the infinite `ioctl` loop shown above.

4. Uncomment the `FLAGS_allocator_strategy` line and re-run — inference completes normally.

**Comment by scyyh11** [comment]
Thanks for the detailed trace, this is the same root cause as #17640.

 With the default allocator strategy (auto_growth), memory pools are isolated per CUDA stream. When `use_queues=True` (the default), `_worker_cv` and `_worker_vlm` run GPU inference concurrently on separate CUDA streams. When one stream triggers OOM, its RetryAllocator waits for memory to be freed, but memory freed by the other stream is invisible to it. The ioctl loop you captured is the RetryAllocator repeatedly polling the driver for memory that will never arrive.

Your workaround of `AGS_allocator_strategy=naive_best_fit` is correct, that strategy uses a single shared pool with no per-stream isolation.

A fix is on the way.

**Comment by chengzeyi** [comment]
We hit what looks like the same hang in production and can add a data point that may help narrow it down: **in our environment the hang correlates with the pipeline version, not just the allocator.**

### What we saw

`PaddleOCRVL.predict()` hangs forever — 100% CPU on one core, 0% GPU utilization, no error, no timeout. The model loads fine (~8.7 GB resident) and the hang happens during autoregressive decode. `py-spy dump --native` on the stuck thread:

```
Thread (active): "Thread-4 (_worker_vlm)"
    0x… (libcuda.so.570.133.20)   ← several frames
    cudaLaunchKernel (libcudart.so.12)
    phi::EmbeddingKernel<phi::dtype::bfloat16, phi::GPUContext> (libphi_gpu.so)
    paddle::experimental::embedding (libphi_core.so)
    embedding (paddle/nn/functional/input.py:336)
    forward (paddlex/inference/models/doc_vlm/modeling/paddleocr_vl/_paddleocr_vl.py:668)
    greedy_search (paddlex/inference/models/common/transformers/generation/utils.py:1284)
    generate (paddlex/inference/models/doc_vlm/modeling/paddleocr_vl/_paddleocr_vl.py:817)
    _paddleocr_vl_run_vl_recognition_batches (paddlex/inference/pipelines/paddleocr_vl/pipeline.py:518)
    _worker_vlm (paddlex/inference/pipelines/paddleocr_vl/pipeline.py:1124)
```

Two dumps 20s apart were byte-identical (same line, same frame), i.e. it is stuck inside a single kernel launch rather than looping through decode steps — consistent with your `ioctl` retry-loop finding.

### The pipeline-version correlation

Same image, same input, same H100, same `paddleocr==3.7.0` / `paddlex==3.7.2` / `paddlepaddle-gpu==3.2.1` (cu126). The only variable is `pipeline_version`:

| `pipeline_version` | VL model | Result |
|---|---|---|
| `v1.6` (current default) | PaddleOCR-VL-1.6 | hung in 6 of 8 runs |
| `v1.5` | PaddleOCR-VL-1.5 | hung (1 run) |
| `v1` | PaddleOCR-VL-0.9B | passed 3/3, ~10 s each |

It is **nondeterministic**, which cost us a lot of time. Two of the eight v1.6 runs did complete normally (~10 s), and an older build of the same image had been serving v1.6 fine for days before this started. We initially misattributed the hang to one of our own recent changes because of exactly this — a "known-good" build hung too once we ran it enough times. So a single successful run doesn't clear a version; it needs repetition.

Pinning `PaddleOCRVL(pipeline_version="v1", ...)` has been stable in production since.

### Why this mattered operationally

The VL weights are downloaded at runtime and the default version is not pinned, so when the upstream default moved to VL-1.6 our workers started hanging **without any change on our side**. Jobs then sat until the platform's execution timeout. If the hang is genuinely allocator-related, it would be useful to know why the newer VL models trigger it so much more readily — larger embedding tensors and a different allocation pattern would be my guess, but I haven't verified that.

We have not tested your `FLAGS_allocator_strategy=naive_best_fit` workaround (we resolved it by pinning `v1`), so I can't confirm whether it also rescues v1.6. If someone tries that combination it would be a useful data point for the maintainers.

### Environment

- `paddleocr==3.7.0`, `paddlex==3.7.2`, `paddlepaddle-gpu==3.2.1` (cu126), Python 3.12
- Base image `nvidia/cuda:12.6.1-cudnn-devel-ubuntu22.04`, driver 570.133.20
- H100 80GB (also reproduced on other card types)
