### ISSUE TITLE
批量图片预测时operator < rnn > error

### ISSUE THREAD

**Issue by aaferrero** [PaddlePaddle/PaddleOCR#2423]
批量图片预测时候，经常会报这个错误，这个有什么办法解决么，环境：python3.7 cuda10.0 nvidia geforce1080 8G，paddlepaddle-gpu 2,0,0 windows 10
报错信息：
Traceback (most recent call last):
  File "E:/fanxi_wu/programs/wrapper_drink_ocr_v3/pp_ocr/tools/infer/classify_modules.py", line 2302, in <module>
    classify_modules.get_ksf_detect_areas(ori_img, image_name, module_name=module_name)
  File "E:/fanxi_wu/programs/wrapper_drink_ocr_v3/pp_ocr/tools/infer/classify_modules.py", line 2112, in get_ksf_detect_areas
    content_imgs, crop_imgs_dict, image_name=file_name)
  File "E:/fanxi_wu/programs/wrapper_drink_ocr_v3/pp_ocr/tools/infer/classify_modules.py", line 1542, in get_content_result
    rec_res, elapse = copy.deepcopy(self.text_recognizer(img_crop_list))
  File "E:\fanxi_wu\programs\wrapper_drink_ocr_v3\pp_ocr_1\tools_2\infer\predict_rec.py", line 117, in __call__
    self.predictor.run()
OSError: In user code:

    File "tools/export_model.py", line 75, in <module>
      main()
    File "tools/export_model.py", line 70, in main
      paddle.jit.save(model, save_path)
    File "<decorator-gen-60>", line 2, in save
      
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
      return wrapped_func(*args, **kwargs)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/base.py", line 38, in __impl__
      return func(*args, **kwargs)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/jit.py", line 680, in save
      concrete_program = static_func.concrete_program
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 461, in concrete_program
      concrete_program, _ = self.get_concrete_program(*input_spec)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 401, in get_concrete_program
      concrete_program, partial_program_layer = self._program_cache[cache_key]
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 684, in __getitem__
      self._caches[item] = self._build_once(item)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 675, in _build_once
      class_instance=cache_key.class_instance)
    File "<decorator-gen-58>", line 2, in from_func_spec
      
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
      return wrapped_func(*args, **kwargs)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/base.py", line 38, in __impl__
      return func(*args, **kwargs)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 625, in from_func_spec
      outputs = static_func(*inputs)
    File "/tmp/tmpqk3xmm2v.py", line 22, in forward
      false_fn_1, (x,), (x,), (x,))
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 210, in convert_ifelse
      return _run_py_ifelse(pred, true_fn, false_fn, true_args, false_args)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 235, in _run_py_ifelse
      return true_fn(*true_args) if pred else false_fn(*false_args)
    File "/paddle/code/gry/PaddleOCR_pub/ppocr/modeling/architectures/base_model.py", line 76, in forward
      x = self.neck(x)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 884, in __call__
      outputs = self.forward(*inputs, **kwargs)
    File "/tmp/tmpmf6_4ac7.py", line 14, in forward
      (x,), (x,))
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 210, in convert_ifelse
      return _run_py_ifelse(pred, true_fn, false_fn, true_args, false_args)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 235, in _run_py_ifelse
      return true_fn(*true_args) if pred else false_fn(*false_args)
    File "/paddle/code/gry/PaddleOCR_pub/ppocr/modeling/necks/rnn.py", line 91, in forward
      x = self.encoder(x)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 884, in __call__
      outputs = self.forward(*inputs, **kwargs)
    File "/paddle/code/gry/PaddleOCR_pub/ppocr/modeling/necks/rnn.py", line 45, in forward
      x, _ = self.lstm(x)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 884, in __call__
      outputs = self.forward(*inputs, **kwargs)
    File "/usr/local/lib/python3.7/site-packages/paddle/nn/layer/rnn.py", line 1035, in forward
      return self._cudnn_impl(inputs, initial_states, sequence_length)
    File "/usr/local/lib/python3.7/site-packages/paddle/nn/layer/rnn.py", line 1012, in _cudnn_impl
      type="rnn", inputs=inputs, outputs=outputs, attrs=attrs)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/layer_object_helper.py", line 52, in append_op
      stop_gradient=stop_gradient)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/framework.py", line 2849, in append_op
      attrs=kwargs.get("attrs", None))
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/framework.py", line 1934, in __init__
      for frame in traceback.extract_stack():

    ExternalError:  Cudnn error, CUDNN_STATUS_INTERNAL_ERROR  (at D:\v2.0.0\paddle\paddle\fluid\operators\rnn_op.cu.cc:420)
      [operator < rnn > error]

**Comment by tink2123** [comment]
单独预测报错的这张图可以吗？

**Comment by zouwen198317** [comment]
我也是这个问题

**Comment by miaozi0714** [comment]
楼主解决了吗

**Comment by zouwen198317** [comment]
没有，不知道什么问题



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: miaozi0714 ***@***.***&gt;
发送时间: 2022年1月18日 09:03
收件人: PaddlePaddle/PaddleOCR ***@***.***&gt;
抄送: zouwen198317 ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [PaddlePaddle/PaddleOCR] 批量图片预测时operator < rnn &gt; error (#2423)





 
楼主解决了吗
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by LFeightyFour** [comment]
我出现了类似的问题，已解决
发现paddleocr调用gpu连续预测图像时，需要cuda版本和显卡版本对应
点击nvidia控制面板，点击系统信息->组件，查看推荐的cuda版本
我的有问题的主机的显卡是1080ti，推荐的是11.1，而我之前安装的是10.1，我以为高性能显卡兼容低版本，没关系
事实上之前使用paddledetection时，配合cuda10.1调用gpu预测也没有问题，但是在换用了cuda11.1后，paddleocr使用gpu连续预测失败的问题就解决了

我能注意到这个，是因为我幸运的有台主机，推荐cuda版本和我安装的刚好一致，都是10.1，可以一直预测不报错

**Comment by zouwen198317** [comment]
我的连续跑 ,开始没有问题,但后面 不知道什么时候就报错, 内存 32G  显卡 1070 8G  应该是够的吧

**Comment by LFeightyFour** [comment]
我的和你一样，也是连续跑，一段时间（大概两分钟以内）后报错，我的问题在于安装的cuda版本和系统推荐的不一致，nvidia控制面板里提示的是11.1版本，我装的是10.1，你可以看看是不是这个问题

**Comment by LFeightyFour** [comment]
你是1070的显卡，nvidia面板推荐的cuda应该不止10.0

**Comment by zouwen198317** [comment]
我的目前已经升级到10.1&nbsp; 时不时还是出现这个问题,&nbsp;不玩这个了,&nbsp;直接pytorch




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleOCR"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月20日(星期三) 下午2:31
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleOCR] 批量图片预测时operator < rnn &gt; error (#2423)





 
你是1070的显卡，nvidia面板推荐的cuda应该不止10.0
