### ISSUE TITLE
Single GPU Multiprocessing with PaddlePaddleOCR and pytorch

### ISSUE THREAD

**Issue by cpene1** [PaddlePaddle/PaddleOCR#3070]
Hi!

First of all, thank you for such a powerful tool! It helped me so much so far!

I was trying to go a bit more in depth and use as many resources as I can, therefore I looked into multiprocessing. I tried to implement the following straightforward method from the official aws-samples repo:
[https://github.com/aws-samples/parallelize-ml-inference/blob/master/src/ml-inference/parallize_inference_pool.py](Parallize Inference Pool)

Based on my experience, it should work out of the box. However, it seems that the line 160 from tools/infer/utility.py does not go through:
https://github.com/PaddlePaddle/PaddleOCR/blob/e58c5e574cbb923f955020cba6796ea424a0c783/tools/infer/utility.py#L160

The model does not get instantiated for some reason. I get the following error:
```
Process ForkPoolWorker-1:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 109, in worker
    initializer(*initargs)
  File "multiprocess.py", line 22, in init_worker
    model = TextE2E(args)
  File "[...]/tools/infer/predict_e2e.py", line 80, in __init__
    self.predictor, self.input_tensor, self.output_tensors = utility.create_predictor(
  File "[...]/tools/infer/utility.py", line 162, in create_predictor
    predictor = inference.create_predictor(config)
OSError: (External)  Cuda error(3), initialization error.
  [Advise: The API call failed because the CUDA driver and runtime could not be initialized. ] (at /paddle/paddle/fluid/platform/gpu_info.cc:308)
```

To be clear, I am trying the case for only 1 GPU and only 1 process. So in theory, it should act exactly the same as a normal inference run.

Do you have any advice? Thanks in advance for your support!

PS: I used the PGNet inference model. I've used it before and it runs perfectly on my machine.

**Comment by cpene1** [comment]
**UPDATE**

**Single gpu multi-process**

I found the same Issue, but it's not in English unfortunately and I didn't quite get the solution. Could you perhaps give me some indications?

https://github.com/PaddlePaddle/PaddleDetection/issues/2241

**Comment by cpene1** [comment]
**SOLUTION**

I got it working by doing 2 things:
1) use torch.multiprocessing instead of multiprocessing
2) At the beginning of your file:
`torch.multiprocessing.set_start_method('spawn')`

This should solve the problem.
Furthermore, if you get a `RuntimeError: context has already been set` , it's a very easy fix by moving the set_start_method('spawn') method to the beginning of your `if __name__ == '__main__':`. Check this:
https://github.com/pytorch/pytorch/issues/3492#issuecomment-341965218

**Comment by daiwt** [comment]
I met the same problem, and I tried to move all my imports of paddle into the function of subprocesses (like `func` in `pool.map(func, my_list)`), and it worked.

I guess that CUDA is initialized in the current process when `paddle.inference` is imported, so importing paddle after subprocess started can be a solution.

**Comment by nilecui** [comment]
我也想问如何释放内存

**Comment by yurinapoleon** [comment]
所以模型本身是不支持并行的？只是用spawn的方式生成了多个模型，到子进程里再import其实也是一个意思

**Comment by cainmagi** [comment]
To all,

I found another way to solve this issue, especially when you do not want to install the heavy `torch`.

Install the following package:
```sh
pip install multiprocess
```

After that, replacing all `multiprocessing` usages with `multiprocess`,

```diff
import multiprocessing as mproc
import multiprocess as mproc
```

and use the `spawn` method to get the subprocess:

```python
ctx = mproc.get_context("spawn")  # The editor may complain on this line, but it works in run time.
proc = ctx.Process(target=test)
```

### Why this method works

To my knowledge, `multiprocess` uses `dill` rather than `pickle` to provide a better serialization method for the `spawn` mode compared to `multiprocessing` in the STL.

### Will it cause memory leakage issue?

I think it will not. I have used the following script to test it. The script contains two tests:

1. The first test will create the OCR model in the subprocess and finalize the process for 10 times. 
2. The second test will keep a single process and create and delete the OCR model in the subprocess for 10 times.

During this process, I do not inspect any incremental occupation on the GPU memory.

```python
import numpy as np
from PIL import Image
from paddleocr import PaddleOCR


def test1():
    model = PaddleOCR(
        use_angle_cls=True,
        lang="en",
        ocr_version="PP-OCRv4",
        use_gpu=True,
        use_space_char=True,
        # use_dilation=True,
        det_model_dir="models/en_PP-OCRv3_det_infer",
        rec_model_dir="models/en_PP-OCRv4_rec_infer",
        cls_model_dir="models/ch_ppocr_mobile_v2.0_cls_infer",
    )
    with Image.open("image.webp") as imobj:
        imobj = imobj.convert("RGB")
        # imobj = imobj.rotate(90, expand=True)
        results = model.ocr(np.asarray(imobj)[..., ::-1], det=True, rec=True, cls=True)
        results = results[0]
        print(len(results))
        print(results[0])


def test2():
    for i in range(10):
        model = PaddleOCR(
            use_angle_cls=True,
            lang="en",
            ocr_version="PP-OCRv4",
            use_gpu=True,
            use_space_char=True,
            # use_dilation=True,
            det_model_dir="models/en_PP-OCRv3_det_infer",
            rec_model_dir="models/en_PP-OCRv4_rec_infer",
            cls_model_dir="models/ch_ppocr_mobile_v2.0_cls_infer",
        )
        with Image.open("image.webp") as imobj:
            imobj = imobj.convert("RGB")
            # imobj = imobj.rotate(90, expand=True)
            results = model.ocr(np.asarray(imobj)[..., ::-1], det=True, rec=True, cls=True)
            results = results[0]
            print(len(results))
            print(results[0])
        del model


if __name__ == "__main__":
    import multiprocess as mproc

    ctx = mproc.get_context("spawn")
    for i in range(10):
        proc = ctx.Process(target=test1)
        proc.start()
        proc.join()
    proc = ctx.Process(target=test2)
    proc.start()
    proc.join()
    print("Finish")
```
