### ISSUE TITLE
pdserving显存溢出

### ISSUE THREAD

**Issue by steinvenic** [PaddlePaddle/PaddleOCR#3144]
`hubserving`版正常，`pdserving`版，测试了两张卡都有显存溢出的情况

搜了下相关问题，很多说已经修复了，也有像#3139 改一下`batch_size_per_card `参数，可我还是没有解决，请大佬帮忙看一下。下面的`Dockerfile`可以直接构建并运行的，相关的预测文件及三方库已经在仓库里面了。
运行：
```
wget https://gitee.com/steinven/paddle-ocr_hubserving/raw/master/deploy/pdserving/docker/gpu/Dockerfile

docker build -t pdserving_ocr_gpu:v1 .

docker run -itd --network=host --gpus all --name myocr pdserving_ocr_gpu:v1
```

`Dockerfile`：
```
# Version: 2.0.0
FROM registry.baidubce.com/paddlepaddle/paddle:2.1.0-gpu-cuda10.2-cudnn7

# PaddleOCR base on Python3.7
RUN pip3.7 install --upgrade pip -i https://mirror.baidu.com/pypi/simple \
    && pip3.7 install paddle-serving-server-gpu==0.6.1.post101 -i https://mirror.baidu.com/pypi/simple \
    && pip3.7 install paddle-serving-app==0.6.1 -i https://mirror.baidu.com/pypi/simple \
    && git clone https://gitee.com/steinven/paddle-ocr_hubserving /PaddleOCR \
    && pip3.7 install /PaddleOCR/deploy/pdserving/paddle_serving_client-0.0.0-cp37-none-any.whl \
    && pip3.7 install -r /PaddleOCR/requirements.txt -i https://mirror.baidu.com/pypi/simple \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /PaddleOCR

ENTRYPOINT ["sh","deploy/pdserving/docker/gpu/entrypoint.sh"]
```

config.yml：

```
#rpc端口, rpc_port和http_port不允许同时为空。当rpc_port为空且http_port不为空时，会自动将rpc_port设置为http_port+1
rpc_port: 18091

#http端口, rpc_port和http_port不允许同时为空。当rpc_port可用且http_port为空时，不自动生成http_port
http_port: 9998

#worker_num, 最大并发数。当build_dag_each_worker=True时, 框架会创建worker_num个进程，每个进程内构建grpcSever和DAG
##当build_dag_each_worker=False时，框架会设置主线程grpc线程池的max_workers=worker_num
worker_num: 10

#build_dag_each_worker, False，框架在进程内创建一条DAG；True，框架会每个进程内创建多个独立的DAG
build_dag_each_worker: False

dag:
    #op资源类型, True, 为线程模型；False，为进程模型
    is_thread_op: False

    #重试次数
    retry: 10

    #使用性能分析, True，生成Timeline性能数据，对性能有一定影响；False为不使用
    use_profile: False
    
    tracer:
        interval_s: 10
op:
    det:
        #并发数，is_thread_op=True时，为线程并发；否则为进程并发
        concurrency: 8

        #当op配置没有server_endpoints时，从local_service_conf读取本地服务配置
        local_service_conf:
            #client类型，包括brpc, grpc和local_predictor.local_predictor不启动Serving服务，进程内预测
            client_type: local_predictor

            #det模型路径
            model_config: ./ppocr_det_mobile_2.0_serving

            #Fetch结果列表，以client_config中fetch_var的alias_name为准
            fetch_list: ["save_infer_model/scale_0.tmp_1"]

            #计算硬件ID，当devices为""或不写时为CPU预测；当devices为"0", "0,1,2"时为GPU预测，表示使用的GPU卡
            devices: "0"
            
            ir_optim: True
    rec:
        #并发数，is_thread_op=True时，为线程并发；否则为进程并发
        concurrency: 4

        #超时时间, 单位ms
        timeout: -1
 
        #Serving交互重试次数，默认不重试
        retry: 1

        #当op配置没有server_endpoints时，从local_service_conf读取本地服务配置
        local_service_conf:

            #client类型，包括brpc, grpc和local_predictor。local_predictor不启动Serving服务，进程内预测
            client_type: local_predictor

            #rec模型路径
            model_config: ./ppocr_rec_mobile_2.0_serving

            #Fetch结果列表，以client_config中fetch_var的alias_name为准
            fetch_list: ["save_infer_model/scale_0.tmp_1"]  

            #计算硬件ID，当devices为""或不写时为CPU预测；当devices为"0", "0,1,2"时为GPU预测，表示使用的GPU卡
            devices: "0"
            
            ir_optim: True

```

log:
```
I0621 15:53:01.537859   108 naive_executor.cc:98] ---  skip [feed], feed -> x
I0621 15:53:01.540813   224 analysis_predictor.cc:595] ======= optimize end =======
I0621 15:53:01.541018   108 naive_executor.cc:98] ---  skip [relu_2.tmp_0], fetch -> fetch
I0621 15:53:01.545846   224 naive_executor.cc:98] ---  skip [feed], feed -> x
I0621 15:53:01.548678   138 analysis_predictor.cc:595] ======= optimize end =======
I0621 15:53:01.549124   224 naive_executor.cc:98] ---  skip [save_infer_model/scale_0.tmp_0], fetch -> fetch
I0621 15:53:01.552489   138 naive_executor.cc:98] ---  skip [feed], feed -> x
I0621 15:53:01.555160   138 naive_executor.cc:98] ---  skip [relu_2.tmp_0], fetch -> fetch
web_service.py:49: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
  data = np.fromstring(data, np.uint8)
W0621 15:53:27.114626   148 device_context.cc:404] Please NOTE: device: 0, GPU Compute Capability: 3.5, Driver API Version: 11.3, Runtime API Version: 10.2
W0621 15:53:27.117723   148 device_context.cc:422] device: 0, cuDNN Version: 7.6.
W0621 15:53:28.229934   224 device_context.cc:404] Please NOTE: device: 0, GPU Compute Capability: 3.5, Driver API Version: 11.3, Runtime API Version: 10.2
W0621 15:53:28.239130   224 device_context.cc:422] device: 0, cuDNN Version: 7.6.
W0621 15:53:29.734676   224 rnn_op.cu.cc:404] If the memory space of the Input WeightList is not continuous, less efficient calculation will be called. Please call flatten_parameters() to make the input memory continuous.
web_service.py:49: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
  data = np.fromstring(data, np.uint8)
W0621 15:53:32.247582   125 device_context.cc:404] Please NOTE: device: 0, GPU Compute Capability: 3.5, Driver API Version: 11.3, Runtime API Version: 10.2
W0621 15:53:32.491379   125 device_context.cc:422] device: 0, cuDNN Version: 7.6.
web_service.py:49: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
  data = np.fromstring(data, np.uint8)
web_service.py:49: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
  data = np.fromstring(data, np.uint8)
W0621 15:54:53.653043   148 operator.cc:242] conv2d_fusion raises an exception paddle::memory::allocation::BadAlloc, ResourceExhaustedError: 

Out of memory error on GPU 0. Cannot allocate 20.250244MB memory on GPU 0, 1.943970GB memory has been allocated and available memory is only 8.312500MB.

Please check whether there is any other process using GPU 0.
1. If yes, please stop them, or start PaddlePaddle on another GPU.
2. If no, please decrease the batch size of your model. 

 (at /paddle/paddle/fluid/memory/allocation/cuda_allocator.cc:79)
W0621 15:54:53.967124   172 device_context.cc:404] Please NOTE: device: 0, GPU Compute Capability: 3.5, Driver API Version: 11.3, Runtime API Version: 10.2
W0621 15:54:56.768239   172 device_context.cc:422] device: 0, cuDNN Version: 7.6.
web_service.py:49: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
  data = np.fromstring(data, np.uint8)
```

**Comment by steinvenic** [comment]
已经解决，原来是并发数默认设置的较大，自己的小显卡受不住。可以分别改成2、1后，使用正常。文件路径`/PaddleOCR/deploy/pdserving/config.yml`
```
det:
    #并发数，is_thread_op=True时，为线程并发；否则为进程并发
    concurrency: 2
    ...
rec:
    #并发数，is_thread_op=True时，为线程并发；否则为进程并发
    concurrency: 1
    ...
```

**Comment by thomaszheng** [comment]
默认的配置在v100-32g上是可以正常执行的，在p4-8g上就会报这个错。也只有通过调整并发数解决

**Comment by cool3rzZ** [comment]
之前有台p4按照默认就没问题，最近新换了台p4就报显存溢出，很怪
