### ISSUE TITLE
multiprocessing多个Process跑在同一张卡上失败

### ISSUE THREAD

**Issue by NLPOR** [PaddlePaddle/PaddleOCR#3165]
**因为我一个进程跑不满单GPU，所以想再起多个进程跑在同一张GPU上，使用multiprocessing时报如下错，求大佬指导**
大致的脚本，不是实际的
def fun():
        from paddleocr import PaddleOCR
        model=PaddleOCR(use_gpu=True)
from multiprocessing import Process
for _ in range(2):
        p=Process(target=fun)
        p.start()

### 报错信息如下：
Process Process-3:
Traceback (most recent call last):
File "/root/anaconda3/envs/paddle_rec/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
self.run()
File "/root/anaconda3/envs/paddle_rec/lib/python3.6/multiprocessing/process.py", line 93, in run
self._target(*self._args, **self._kwargs)
File "", line 5, in init
File "/root/anaconda3/envs/paddle_rec/lib/python3.6/site-packages/paddleocr/paddleocr.py", line 221, in init
super().init(postprocess_params)
File "/root/anaconda3/envs/paddle_rec/lib/python3.6/site-packages/paddleocr/tools/infer/predict_system.py", line 41, in init
self.text_detector = predict_det.TextDetector(args)
File "/root/anaconda3/envs/paddle_rec/lib/python3.6/site-packages/paddleocr/tools/infer/predict_det.py", line 80, in init
utility.create_predictor(args, mode="det")
File "/root/anaconda3/envs/paddle_rec/lib/python3.6/site-packages/paddleocr/tools/infer/utility.py", line 144, in create_predictor
predictor = create_paddle_predictor(config)
paddle.fluid.core_avx.EnforceNotMet:

### C++ Call Stacks (More useful to developers):
0 std::string paddle::platform::GetTraceBackString<char const*>(char const*&&, char const*, int)
1 paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int)
2 paddle::platform::SetDeviceId(int)
3 paddle::AnalysisConfig::fraction_of_gpu_memory_for_pool() const
4 std::unique_ptr<paddle::PaddlePredictor, std::default_deletepaddle::PaddlePredictor > paddle::CreatePaddlePredictor<paddle::AnalysisConfig, (paddle::PaddleEngineKind)2>(paddle::AnalysisConfig const&)
5 std::unique_ptr<paddle::PaddlePredictor, std::default_deletepaddle::PaddlePredictor > paddle::CreatePaddlePredictorpaddle::AnalysisConfig(paddle::AnalysisConfig const&)

### Error Message Summary:
ExternalError: Cuda error(3), initialization error.
[Advise: The API call failed because the CUDA driver and runtime could not be initialized. ] at (/paddle/paddle/fluid/platform/gpu_info.cc:212)

**我可以多次执行python script.py来起多进程执行上述代码，但是不能通过multiprocessing的Process方法来起多进程请问是什么原因？？？求指导**

**Comment by LDOUBLEV** [comment]
把模型初始化放在多进程外面试试

**Comment by NLPOR** [comment]
实际代码是这样的，还是不行哦，我起用Process起一个进程都报错
`def fun(text_sys, img):
      rec_res, dt_boxes = text_sys(img)

def main():
      img = cv2.imread(img_path)
      text_sys = TextSystem(args)   # 模型初始化的东西都在这里面
      from multiprocessing import Process
      for _ in range(1):
            p = Process(target=fun, args=(text_sys, img))
            p.start()
`
一样的挂，报同样的错。。。。。求大佬指导

**Comment by ranchlai** [comment]
GPU模式下，目前不支持multiprocessing.Process以及multiprocessing.Pool等的多进程方式。

**Comment by NLPOR** [comment]
这样啊，那意思是GPU模式下只能通过subprocess的方式起子进程咯？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleOCR"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月24日(星期四) 晚上6:54
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleOCR] multiprocessing多个Process跑在同一张卡上失败 (#3165)





 
GPU模式下，目前不支持multiprocessing.Process以及multiprocessing.Pool等的多进程方式。

**Comment by NLPOR** [comment]
已解决

**Comment by sallenhandong** [comment]
> 已解决

你好，怎么解决的，现在我是用flask部署接口，有好的方式嘛

**Comment by ZhangChaoZhong** [comment]
> 
> 
> 已解决

你好，请问下怎么解决？可以发下代码吗？

**Comment by NLPOR** [comment]
把所有跟paddle相关的库的导入全都放在子进程中，不要放在父进程import就可以了，或者采用上面的那样做成服务的形式




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleOCR"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月24日(星期四) 晚上6:54
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleOCR] multiprocessing多个Process跑在同一张卡上失败 (#3165)





 
GPU模式下，目前不支持multiprocessing.Process以及multiprocessing.Pool等的多进程方式。
