### ISSUE TITLE
Error: Failed to find dynamic library: libcublas.so ( libcublas.so: cannot open shared object file: No such file or directory )

### ISSUE THREAD

**Issue by chenyangMl** [PaddlePaddle/PaddleOCR#41]
您好，按照文档操作出现如下错误
运行环境 docker-ubuntu 18.04 + cuda10.0 + python3.6.9 + paddle-gpu(1.7.2.post97)
运行命令 export PYTHONPATH=. && python3 tools/infer/predict_system.py --image_dir="./doc/imgs/11.jpg" --det_model_dir="./inference/det/"  --rec_model_dir="./inference/rec/"

出现如下错误
Error: Failed to find dynamic library: libcublas.so ( libcublas.so: cannot open shared object file: No such file or directory ) 
 Please specify its path correctly using following ways: 
 Method. set environment variable LD_LIBRARY_PATH on Linux or DYLD_LIBRARY_PATH on Mac OS. 
 For instance, issue command: export LD_LIBRARY_PATH=... 
 Note: After Mac OS 10.11, using the DYLD_LIBRARY_PATH is impossible unless System Integrity Protection (SIP) is disabled. at (/paddle/paddle/fluid/platform/dynload/dynamic_loader.cc:177)

**Comment by dyning** [comment]
你机器是cuda10的版本，用的是cuda9的paddle，更新下docker环境就好了，
如果您的机器安装的是CUDA10，请运行以下命令创建容器
sudo nvidia-docker run --name ppocr -v $PWD:/paddle --network=host -it hub.baidubce.com/paddlepaddle/paddle:latest-gpu-cuda10.0-cudnn7-dev /bin/bash

**Comment by LDOUBLEV** [comment]
找不到libcublas.so的解决方案可以参考：https://blog.csdn.net/Grit_007/article/details/85000297
