### ISSUE TITLE
批量预测到一定数量就报下面的错了,改了det_batch_num和det_max_side_len两个参数治标不治本

### ISSUE THREAD

**Issue by miaozi0714** [PaddlePaddle/PaddleOCR#5247]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：win10 + cuda 10.2 + cuDnn 7.6
- 版本号/Version：Paddle：2.0.1  PaddleOCR：gpu版2.1.1 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：
In user code:

    File "tools/export_model.py", line 75, in <module>
      main()
    File "tools/export_model.py", line 70, in main
      paddle.jit.save(model, save_path)
    File "<decorator-gen-60>", line 2, in save

    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
      return wrapped_func(*args, **kwargs)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/base.py", line 38, in __impl__
      return func(*args, **kwargs)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/jit.py", line 680, in save
      concrete_program = static_func.concrete_program
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 461, in concrete_program
      concrete_program, _ = self.get_concrete_program(*input_spec)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 401, in get_concrete_program
      concrete_program, partial_program_layer = self._program_cache[cache_key]
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 684, in __getitem__
      self._caches[item] = self._build_once(item)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 675, in _build_once
      class_instance=cache_key.class_instance)
    File "<decorator-gen-58>", line 2, in from_func_spec

    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
      return wrapped_func(*args, **kwargs)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/base.py", line 38, in __impl__
      return func(*args, **kwargs)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 625, in from_func_spec
      outputs = static_func(*inputs)
    File "/tmp/tmpvk13f38i.py", line 22, in forward
      false_fn_1, (x,), (x,), (x,))
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 210, in convert_ifelse
      return _run_py_ifelse(pred, true_fn, false_fn, true_args, false_args)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 235, in _run_py_ifelse
      return true_fn(*true_args) if pred else false_fn(*false_args)
    File "/paddle/code/gry/PaddleOCR_pub/ppocr/modeling/architectures/base_model.py", line 76, in forward
      x = self.neck(x)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 884, in __call__
      outputs = self.forward(*inputs, **kwargs)
    File "/tmp/tmp64xgd4nq.py", line 14, in forward
      (x,), (x,))
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 210, in convert_ifelse
      return _run_py_ifelse(pred, true_fn, false_fn, true_args, false_args)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 235, in _run_py_ifelse
      return true_fn(*true_args) if pred else false_fn(*false_args)
    File "/paddle/code/gry/PaddleOCR_pub/ppocr/modeling/necks/rnn.py", line 91, in forward
      x = self.encoder(x)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 884, in __call__
      outputs = self.forward(*inputs, **kwargs)
    File "/paddle/code/gry/PaddleOCR_pub/ppocr/modeling/necks/rnn.py", line 45, in forward
      x, _ = self.lstm(x)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 884, in __call__
      outputs = self.forward(*inputs, **kwargs)
    File "/usr/local/lib/python3.7/site-packages/paddle/nn/layer/rnn.py", line 1035, in forward
      return self._cudnn_impl(inputs, initial_states, sequence_length)
    File "/usr/local/lib/python3.7/site-packages/paddle/nn/layer/rnn.py", line 1012, in _cudnn_impl
      type="rnn", inputs=inputs, outputs=outputs, attrs=attrs)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/layer_object_helper.py", line 52, in append_op
      stop_gradient=stop_gradient)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/framework.py", line 2849, in append_op
      attrs=kwargs.get("attrs", None))
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/framework.py", line 1934, in __init__
      for frame in traceback.extract_stack():

    ExternalError: CUDNN error(4), CUDNN_STATUS_INTERNAL_ERROR.
      [Hint: 'CUDNN_STATUS_INTERNAL_ERROR'.  An internal cuDNN operation failed.  ] (at ..\paddle/fluid/operators/rnn_op.cu.cc:621)
      [operator < rnn > error]

**Comment by tink2123** [comment]
麻烦贴下详细的运行命令吧

**Comment by miaozi0714** [comment]
PaddleOCR(det_max_side_len=680, cls_batch_num=10, det_batch_num=10, rec_batch_num=10, gpu_mem=1000, use_angle_cls=True, lang="ch", use_gpu = True, det_model_dir = "model/det", rec_model_dir = "model/rec/ch", cls_model_dir="model/cls")

**Comment by miaozi0714** [comment]
> PaddleOCR(det_max_side_len=680, cls_batch_num=10, det_batch_num=10, rec_batch_num=10, gpu_mem=1000, use_angle_cls=True, lang="ch", use_gpu = True, det_model_dir = "model/det", rec_model_dir = "model/rec/ch", cls_model_dir="model/cls")

1

**Comment by LFeightyFour** [comment]
我出现了同样的问题，已解决
发现paddleocr调用gpu连续预测图像时，需要cuda版本和显卡版本对应
点击nvidia控制面板，点击系统信息->组件，查看推荐的cuda版本
我的有问题的主机的显卡是1080ti，推荐的是11.1，而我之前安装的是10.1，我以为高性能显卡兼容低版本，没关系
事实上之前使用paddledetection时，配合cuda10.1调用gpu预测也没有问题，但是在换用了cuda11.1后，paddleocr使用gpu连续预测失败的问题就解决了

我能注意到这个，是因为我幸运的有台主机，推荐cuda版本和我安装的刚好一致，都是10.1，可以一直预测不报错
