### ISSUE TITLE
paddleOCR ExternalError: CUDNN error(4), CUDNN_STATUS_INTERNAL_ERROR

### ISSUE THREAD

**Issue by sqy2022** [PaddlePaddle/PaddleOCR#5933]
我对官方的demo稍微进行改造，让他一直进行预测，然后就报下面的错误，我已经在两台GPU机器上运行都报这个错误 :

from paddleocr import PaddleOCR, draw_ocr
import cv2
import time

ocr = PaddleOCR(use_angle_cls=True)
img_path = './1111.jpg'
img = cv2.imread(img_path)

while True:
    result = ocr.ocr(img, cls=True)
    for line in result:
        print(line)

运行一两次可以，但是当运行几次后，就报下面的错误
Traceback (most recent call last):
  File "E:/work/ocr_test/test/main2.py", line 13, in <module>
    result = ocr.ocr(img, cls=True)
  File "D:\conda\envs\ocr\lib\site-packages\paddleocr\paddleocr.py", line 383, in ocr
    dt_boxes, rec_res = self.__call__(img, cls)
  File "D:\conda\envs\ocr\lib\site-packages\paddleocr\tools\infer\predict_system.py", line 89, in __call__
    rec_res, elapse = self.text_recognizer(img_crop_list)
  File "D:\conda\envs\ocr\lib\site-packages\paddleocr\tools\infer\predict_rec.py", line 360, in __call__
    self.predictor.run()
OSError: In user code:

    File "tools/export_model_dist.py", line 102, in <module>
      main()
    File "tools/export_model_dist.py", line 87, in main
      save_model(student, infer_shape, save_path, logger)
    File "tools/export_model_dist.py", line 41, in save_model
      paddle.jit.save(model, save_path)
    File "<decorator-gen-60>", line 2, in save
      
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
      return wrapped_func(*args, **kwargs)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/base.py", line 39, in __impl__
      return func(*args, **kwargs)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/jit.py", line 681, in save
      inner_input_spec)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 488, in concrete_program_specify_input_spec
      *desired_input_spec)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 402, in get_concrete_program
      concrete_program, partial_program_layer = self._program_cache[cache_key]
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 711, in __getitem__
      self._caches[item] = self._build_once(item)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 702, in _build_once
      class_instance=cache_key.class_instance)
    File "<decorator-gen-58>", line 2, in from_func_spec
      
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
      return wrapped_func(*args, **kwargs)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/base.py", line 39, in __impl__
      return func(*args, **kwargs)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 652, in from_func_spec
      outputs = static_func(*inputs)
    File "/paddle/temp/tmp_cx6_gup.py", line 38, in forward
      false_fn_2, (out_dict, x), (x,), (x,))
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 210, in convert_ifelse
      return _run_py_ifelse(pred, true_fn, false_fn, true_args, false_args)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 235, in _run_py_ifelse
      return true_fn(*true_args) if pred else false_fn(*false_args)
    File "/paddle/code/gry/icode/baidu/personal-code/PaddleOCR/ppocr/modeling/architectures/base_model.py", line 81, in forward
      x = self.neck(x)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 902, in __call__
      outputs = self.forward(*inputs, **kwargs)
    File "/paddle/temp/tmp69oc_vec.py", line 14, in forward
      (x,), (x,))
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 210, in convert_ifelse
      return _run_py_ifelse(pred, true_fn, false_fn, true_args, false_args)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 235, in _run_py_ifelse
      return true_fn(*true_args) if pred else false_fn(*false_args)
    File "/paddle/code/gry/icode/baidu/personal-code/PaddleOCR/ppocr/modeling/necks/rnn.py", line 92, in forward
      x = self.encoder(x)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 902, in __call__
      outputs = self.forward(*inputs, **kwargs)
    File "/paddle/code/gry/icode/baidu/personal-code/PaddleOCR/ppocr/modeling/necks/rnn.py", line 45, in forward
      x, _ = self.lstm(x)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 902, in __call__
      outputs = self.forward(*inputs, **kwargs)
    File "/usr/local/lib/python3.7/site-packages/paddle/nn/layer/rnn.py", line 1047, in forward
      return self._cudnn_impl(inputs, initial_states, sequence_length)
    File "/usr/local/lib/python3.7/site-packages/paddle/nn/layer/rnn.py", line 1024, in _cudnn_impl
      type="rnn", inputs=inputs, outputs=outputs, attrs=attrs)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/layer_object_helper.py", line 52, in append_op
      stop_gradient=stop_gradient)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/framework.py", line 3027, in append_op
      attrs=kwargs.get("attrs", None))
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/framework.py", line 2107, in __init__
      for frame in traceback.extract_stack():

    ExternalError: CUDNN error(4), CUDNN_STATUS_INTERNAL_ERROR. 
      [Hint: 'CUDNN_STATUS_INTERNAL_ERROR'.  An internal cuDNN operation failed.  ] (at ..\paddle/fluid/operators/rnn_op.cu.cc:621)
      [operator < rnn > error]

哪位大牛指点一下迷津！

我的环境
(ocr) E:\work\ocr_test\PaddleOCR>conda list
# packages in environment at D:\conda\envs\ocr:
#
# Name                    Version                   Build  Channel      
astor                     0.8.1                    pypi_0    pypi       
babel                     2.9.1                    pypi_0    pypi       
bce-python-sdk            0.8.64                   pypi_0    pypi       
bzip2                     1.0.8                h8ffe710_4    conda-forge
ca-certificates           2021.10.8            h5b45459_0    conda-forge
cachetools                5.0.0                    pypi_0    pypi       
certifi                   2021.10.8                pypi_0    pypi
cfgv                      3.3.1                    pypi_0    pypi
charset-normalizer        2.0.12                   pypi_0    pypi
click                     8.1.2                    pypi_0    pypi
colorama                  0.4.4                    pypi_0    pypi
cssselect                 1.1.0                    pypi_0    pypi
cssutils                  2.4.0                    pypi_0    pypi
cycler                    0.11.0                   pypi_0    pypi
cython                    0.29.28                  pypi_0    pypi
decorator                 5.1.1                    pypi_0    pypi
distlib                   0.3.4                    pypi_0    pypi
et-xmlfile                1.1.0                    pypi_0    pypi
filelock                  3.6.0                    pypi_0    pypi
flake8                    4.0.1                    pypi_0    pypi
flask                     2.0.3                    pypi_0    pypi
flask-babel               2.0.0                    pypi_0    pypi
fonttools                 4.31.2                   pypi_0    pypi
future                    0.18.2                   pypi_0    pypi
identify                  2.4.12                   pypi_0    pypi
idna                      3.3                      pypi_0    pypi
imageio                   2.16.1                   pypi_0    pypi
imgaug                    0.4.0                    pypi_0    pypi
iopath                    0.1.9                    pypi_0    pypi
itsdangerous              2.1.2                    pypi_0    pypi
jinja2                    3.1.1                    pypi_0    pypi
kiwisolver                1.4.2                    pypi_0    pypi
layoutparser              0.0.0                    pypi_0    pypi
libffi                    3.4.2                h8ffe710_5    conda-forge
libzlib                   1.2.11            h8ffe710_1014    conda-forge
lmdb                      1.3.0                    pypi_0    pypi
lxml                      4.8.0                    pypi_0    pypi
markupsafe                2.1.1                    pypi_0    pypi
matplotlib                3.5.1                    pypi_0    pypi
mccabe                    0.6.1                    pypi_0    pypi
networkx                  2.7.1                    pypi_0    pypi
nodeenv                   1.6.0                    pypi_0    pypi
numpy                     1.22.3                   pypi_0    pypi
opencv-contrib-python     4.4.0.46                 pypi_0    pypi
opencv-python             4.5.5.64                 pypi_0    pypi
openpyxl                  3.0.9                    pypi_0    pypi
openssl                   3.0.2                h8ffe710_1    conda-forge
packaging                 21.3                     pypi_0    pypi
paddleocr                 2.4.0.4                  pypi_0    pypi
paddlepaddle-gpu          2.2.2                    pypi_0    pypi
pandas                    1.4.2                    pypi_0    pypi
pillow                    9.1.0                    pypi_0    pypi
pip                       22.0.4             pyhd8ed1ab_0    conda-forge
platformdirs              2.5.1                    pypi_0    pypi
portalocker               2.4.0                    pypi_0    pypi
pre-commit                2.18.1                   pypi_0    pypi
premailer                 3.10.0                   pypi_0    pypi
protobuf                  3.20.0                   pypi_0    pypi
pyclipper                 1.3.0.post2              pypi_0    pypi
pycodestyle               2.8.0                    pypi_0    pypi
pycryptodome              3.14.1                   pypi_0    pypi
pyflakes                  2.4.0                    pypi_0    pypi
toml                      0.10.2                   pypi_0    pypi
tqdm                      4.64.0                   pypi_0    pypi
ucrt                      10.0.20348.0         h57928b3_0    conda-forge
urllib3                   1.26.9                   pypi_0    pypi
vc                        14.2                 hb210afc_6    conda-forge
virtualenv                20.14.0                  pypi_0    pypi
visualdl                  2.2.3                    pypi_0    pypi
vs2015_runtime            14.29.30037          h902a5da_6    conda-forge
werkzeug                  2.1.0                    pypi_0    pypi
wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
xz                        5.2.5                h62dcd97_1    conda-forge

(ocr) E:\work\ocr_test\PaddleOCR>python
Python 3.8.13 | packaged by conda-forge | (default, Mar 25 2022, 05:59:00) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> 
Windows 10 专业版 64位系统

**Comment by LFeightyFour** [comment]
我也出现了这样的问题，连续一直预测时就会出现

**Comment by LFeightyFour** [comment]
我的问题已解决

**Comment by LFeightyFour** [comment]
我的问题已解决
发现paddleocr调用gpu连续预测单张图像时，需要cuda版本和显卡版本对应
点击nvidia控制面板，点击系统信息->组件，查看推荐的cuda版本
我的有问题的主机的显卡是1080ti，推荐的是11.1，而我之前安装的是10.1，我以为高性能显卡兼容低版本，没关系
事实上之前使用paddledetection时，配合cuda10.1调用gpu预测也没有问题，但是在换用了cuda11.1后，paddleocr使用gpu连续预测失败的问题就解决了

我能注意到这个，是因为我幸运的有台主机，推荐cuda版本和我安装的刚好一致，都是10.1，可以一直预测不报错

**Comment by putdoor** [comment]
不妨指定GPU试试：export CUDA_VISIBLE_DEVICES=1

**Comment by lizhq** [comment]
export CUDA_VISIBLE_DEVICES=1

**Comment by lizhq** [comment]
export CUDA_VISIBLE_DEVICES=1  这个可以 , 初步定为框架对多个GPU 指定两个以上有些问题

**Comment by 694578908** [comment]
我设置的batch_size_per_card: 4 


Traceback (most recent call last):
  File "E:/PaddleOCR-release-2.7.1/tools/train.py", line 228, in <module>
    main(config, device, logger, vdl_writer, seed)
  File "E:/PaddleOCR-release-2.7.1/tools/train.py", line 203, in main
    amp_custom_white_list, amp_dtype)
  File "E:\PaddleOCR-release-2.7.1\tools\program.py", line 337, in train
    post_result = post_process_class(preds, batch[1])
  File "E:\PaddleOCR-release-2.7.1\ppocr\postprocess\db_postprocess.py", line 229, in __call__
    src_h, src_w, ratio_h, ratio_w = shape_list[batch_index]
ValueError: too many values to unpack (expected 4)
我问下这个是怎么回事？
