### ISSUE TITLE
8000 iter报错 “Cudnn error”

### ISSUE THREAD

**Issue by zwy4896** [PaddlePaddle/PaddleOCR#613]
训练SRN模型，用的默认yml文件，总是会在8000个iter报错 “Cudnn error”，请问这可能是什么原因导致的？该如何解决？
ExternalError:  Cudnn error, CUDNN_STATUS_EXECUTION_FAILED  at (/paddle/paddle/fluid/operators/conv_cudnn_op.cu:300)
  [operator < conv2d > error]

**Comment by tink2123** [comment]
请问你的cuda版本和cudnn版本是？可以先尝试升级cudnn至7.6+

**Comment by zwy4896** [comment]
@tink2123 cuda版本是9.0，cudnn版本是7.6.5

**Comment by tink2123** [comment]
应该是环境问题导致的，请问您是在docker里训练的嘛？是否方便在docker环境里训练模型呢？

**Comment by yjmm10** [comment]
我也发现这个问题，按照paddleocr快速配置的说明配置，我本地cuda是9.0 cudnn 原先是7.0.3，后来改成7.6.5，也会出现这个问题。
请教一个conda的问题，conda装的cuda9.0，cudnn7.6.5，环境变量要怎么修改呢，我直接跑python预测，也出现了cudnn版本不一样，想请教一下。

**Comment by WenmuZhou** [comment]
import paddle.fluid 
paddle.fluid.install_check.run_check()

这两句话会输出这个吗
Your Paddle Fluid is installed successfully!

**Comment by zwy4896** [comment]
@WenmuZhou 这个是可以正常输出的
![image](https://user-images.githubusercontent.com/25102200/91413574-e9d7a000-e87d-11ea-9dbb-03a8d8f3e40d.png)

**Comment by chen-del** [comment]
文件在推理时突然出现这种报错，
 Otherwise, this may indicate an internal error/bug in the library.  ] (at /paddle/paddle/fluid/operators/conv_cudnn_op.cu:349)
  [operator < conv2d > error]
