### ISSUE TITLE
Paddle无法申请显存,Out of memory error on GPU 0

### ISSUE THREAD

**Issue by phybrain** [PaddlePaddle/PaddleOCR#6197]
Out of memory error on GPU 0. Cannot allocate 512.000000B memory on GPU 6, available memory is only 0.000000B.

显卡正常，无进程，跑起来没有申请到显存

- 系统环境/System Environment：
ubuntu,显卡2080ti,cuda10.2
- 版本号/Version：Paddle：2..0.2  PaddleOCR： 问题相关组件/Related components：tools/predict*.py
- 运行指令/Command Code：
python3 tools/infer/predict_det.py --image_dir="./doc/imgs/00018069.jpg" --det_model_dir="./pretrain_models/ch_PP-OCRv2_det_infer/"
- 完整报错/Complete Error Message：
Traceback (most recent call last):
  File "tools/infer/predict_det.py", line 258, in <module>
    text_detector = TextDetector(args)
  File "tools/infer/predict_det.py", line 107, in __init__
    args, 'det', logger)
  File "/PaddleOCR/tools/infer/utility.py", line 307, in create_predictor
    predictor = inference.create_predictor(config)
RuntimeError: ResourceExhaustedError:

Out of memory error on GPU 0. Cannot allocate 2.250000kB memory on GPU 0, 127.994262TB memory has been allocated and available memory is only 0.000000B.

**Comment by phybrain** [comment]
> 你好，先试下paddle.utils.run_check()，看下是否ok，另外就是注意看下当前使用的显卡是否有其他任务的占用（nvidia-smi）

解决了, paddle隐藏进程没kill掉，kill 了就释放了显存

**Comment by ruibeite** [comment]
> > 你好，先试下paddle.utils.run_check()，看下是否ok，另外就是注意看下当前使用的显卡是否有其他任务的占用（nvidia-smi）
> 
> 解决了, paddle隐藏进程没kill掉，kill 了就释放了显存

请问具体怎么弄呢，我也遇到这个问题，我用 ‘[ch_PP-OCRv3_det_cml.yml]这个配置文件来训练就会提示‘Out of memory error on GPU 0.，用det_mv3_db.yml就能正常训练

**Comment by littletomatodonkey** [comment]
确定当前显卡没在用的话，可以尝试减小batch size
