### ISSUE TITLE
请问在使用官方预训练模型进行微调时报错：OSError: (External) CUBLAS error(7). 是什么原因呢？  

### ISSUE THREAD

**Issue by delrictwax** [PaddlePaddle/PaddleOCR#6436]
- 系统环境/System Environment：ubuntu18.04 , cuda11.4, cudnn7.4
- 版本号/Version：Paddle：gpu2.3.0-post112   PaddleOCR ：-release 2.5 问题相关组件/Related components：
- 运行指令/Command Code：nohup python3 tools/train.py -c configs/rec/ch_PP-OCRv2/ch_PP-OCRv2_rec_distillation.yml &
- 完整报错/Complete Error Message：

配置文件：[ch_PP-OCRv2_rec_distillation.yml]，预训练模型：[ch_PP-OCRv2_rec_train.tar]
运行如下命令时报错：

Traceback (most recent call last):
  File "/home/chengpengfei/PaddleOCR-release-2.5/tools/train.py", line 189, in <module>
    main(config, device, logger, vdl_writer)
  File "/home/chengpengfei/PaddleOCR-release-2.5/tools/train.py", line 121, in main
    model = build_model(config['Architecture'])
  File "/home/chengpengfei/PaddleOCR-release-2.5/ppocr/modeling/architectures/__init__.py", line 31, in build_model
    arch = getattr(mod, name)(config)
  File "/home/chengpengfei/PaddleOCR-release-2.5/ppocr/modeling/architectures/distillation_model.py", line 47, in __init__
    model = BaseModel(model_config)
  File "/home/chengpengfei/PaddleOCR-release-2.5/ppocr/modeling/architectures/base_model.py", line 50, in __init__
    self.backbone = build_backbone(config["Backbone"], model_type)
  File "/home/chengpengfei/PaddleOCR-release-2.5/ppocr/modeling/backbones/__init__.py", line 63, in build_backbone
    module_class = eval(module_name)(**config)
  File "/home/chengpengfei/PaddleOCR-release-2.5/ppocr/modeling/backbones/rec_mv1_enhance.py", line 116, in __init__
    self.conv1 = ConvBNLayer(
  File "/home/chengpengfei/PaddleOCR-release-2.5/ppocr/modeling/backbones/rec_mv1_enhance.py", line 46, in __init__
    self._conv = Conv2D(
  File "/home/chengpengfei/anaconda3/lib/python3.9/site-packages/paddle/nn/layer/conv.py", line 644, in __init__
    super(Conv2D, self).__init__(
  File "/home/chengpengfei/anaconda3/lib/python3.9/site-packages/paddle/nn/layer/conv.py", line 133, in __init__
    self.weight = self.create_parameter(
  File "/home/chengpengfei/anaconda3/lib/python3.9/site-packages/paddle/fluid/dygraph/layers.py", line 423, in create_parameter
    return self._helper.create_parameter(temp_attr, shape, dtype, is_bias,
  File "/home/chengpengfei/anaconda3/lib/python3.9/site-packages/paddle/fluid/layer_helper_base.py", line 376, in create_parameter
    return self.main_program.global_block().create_parameter(
  File "/home/chengpengfei/anaconda3/lib/python3.9/site-packages/paddle/fluid/framework.py", line 3572, in create_parameter
    initializer(param, self)
  File "/home/chengpengfei/anaconda3/lib/python3.9/site-packages/paddle/fluid/initializer.py", line 774, in __call__
    out_var = _C_ops.gaussian_random(
OSError: (External) CUBLAS error(7). 
  [Hint: 'CUBLAS_STATUS_INVALID_VALUE'.  An unsupported value or parameter was passed to the function (a negative vector size, for example). To correct: ensure that all the parameters being passed have valid values. ] (at /paddle/paddle/phi/backends/gpu/gpu_context.cc:424)
  [operator < gaussian_random > error]

**Comment by andyjpaddle** [comment]
好像是paddle的问题，可以先确保paddle安装正确

**Comment by lushi22** [comment]
请问一下，cuda11.4也是兼容11.2的吗？

**Comment by delrictwax** [comment]
> 请问一下，cuda11.4也是兼容11.2的吗？
我这个问题确实是cuda和cudnn版本不兼容的原因，所以我后面是又安装了cuda11.2以及对应的cudnn版本，运行paddle的时候指定调用11.2和相匹配的cudnn就可以正常运行了
