### ISSUE TITLE
paddleocr kie训练报错

### ISSUE THREAD

**Issue by slightly0** [PaddlePaddle/PaddleOCR#7549]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：Windows10
- 版本号/Version：x86_64 
- Paddle：paddlepaddle-gpu2.3.2 
- PaddleOCR： 2.6
- 问题相关组件/Related components：configs/kie/vi_layoutxlm/ser_vi_layoutxlm_xfund_zh.yml
- 运行指令/Command Code：通过VScode运行，训练模型过程中报错
- 完整报错/Complete Error Message：
- Error: ../paddle/phi/kernels/funcs/elementwise_functor.h:545 Assertion `b != 0` failed. InvalidArgumentError: Integer division by zero encountered in (floor) divide. Please check the input value.
Error: ../paddle/phi/kernels/funcs/elementwise_functor.h:545 Assertion `b != 0` failed. InvalidArgumentError: Integer division by zero encountered in (floor) divide. Please check the input value.
Error: ../paddle/phi/kernels/funcs/elementwise_functor.h:545 Assertion `b != 0` failed. InvalidArgumentError: Integer division by zero encountered in (floor) divide. Please check the input value.
Error: ../paddle/phi/kernels/funcs/elementwise_functor.h:545 Assertion `b != 0` failed. InvalidArgumentError: Integer division by zero encountered in (floor) divide. Please check the input value.
Error: ../paddle/phi/kernels/funcs/elementwise_functor.h:545 Assertion `b != 0` failed. InvalidArgumentError: Integer division by zero encountered in (floor) divide. Please check the input value.
Error: ../paddle/phi/kernels/funcs/elementwise_functor.h:545 Assertion `b != 0` failed. InvalidArgumentError: Integer division by zero encountered in (floor) divide. Please check the input value.
Traceback (most recent call last):
  File "D:\Anaconda\envs\paddle\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\Anaconda\envs\paddle\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "c:\Users\lenovo\.vscode\extensions\ms-python.python-2022.14.0\pythonFiles\lib\python\debugpy\adapter/../..\debugpy\launcher/../..\debugpy\__main__.py", line 39, in <module>
    cli.main()
  File "c:\Users\lenovo\.vscode\extensions\ms-python.python-2022.14.0\pythonFiles\lib\python\debugpy\adapter/../..\debugpy\launcher/../..\debugpy/..\debugpy\server\cli.py", line 430, in main   
    run()
  File "c:\Users\lenovo\.vscode\extensions\ms-python.python-2022.14.0\pythonFiles\lib\python\debugpy\adapter/../..\debugpy\launcher/../..\debugpy/..\debugpy\server\cli.py", line 284, in run_file
    runpy.run_path(target, run_name="__main__")
  File "c:\Users\lenovo\.vscode\extensions\ms-python.python-2022.14.0\pythonFiles\lib\python\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 321, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "c:\Users\lenovo\.vscode\extensions\ms-python.python-2022.14.0\pythonFiles\lib\python\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 135, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "c:\Users\lenovo\.vscode\extensions\ms-python.python-2022.14.0\pythonFiles\lib\python\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 124, in _run_code
    exec(code, run_globals)
  File "./main.py", line 13, in <module>
    mymain()
  File ".\tools\train.py", line 202, in mymain
    main(config, device, logger, vdl_writer)
  File ".\tools\train.py", line 175, in main
    program.train(config, train_dataloader, valid_dataloader, device, model,
  File ".\tools\program.py", line 304, in train
    preds = model(batch)
  File "D:\Anaconda\envs\paddle\lib\site-packages\paddle\fluid\dygraph\layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "D:\Anaconda\envs\paddle\lib\site-packages\paddle\fluid\dygraph\layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "E:\jyjt\脚本测试文件\模型\PaddleOCR-release-2.6\ppocr\modeling\architectures\base_model.py", line 86, in forward
    x = self.backbone(x)
  File "D:\Anaconda\envs\paddle\lib\site-packages\paddle\fluid\dygraph\layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "D:\Anaconda\envs\paddle\lib\site-packages\paddle\fluid\dygraph\layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "E:\jyjt\脚本测试文件\模型\PaddleOCR-release-2.6\ppocr\modeling\backbones\vqa_layoutlm.py", line 166, in forward
    x = self.model(
  File "D:\Anaconda\envs\paddle\lib\site-packages\paddle\fluid\dygraph\layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "D:\Anaconda\envs\paddle\lib\site-packages\paddle\fluid\dygraph\layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "D:\Anaconda\envs\paddle\lib\site-packages\paddlenlp\transformers\layoutxlm\modeling.py", line 1040, in forward
    outputs = self.layoutxlm(
  File "D:\Anaconda\envs\paddle\lib\site-packages\paddle\fluid\dygraph\layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "D:\Anaconda\envs\paddle\lib\site-packages\paddle\fluid\dygraph\layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "D:\Anaconda\envs\paddle\lib\site-packages\paddlenlp\transformers\layoutxlm\modeling.py", line 925, in forward
    final_bbox = paddle.concat([bbox, visual_bbox], axis=1)
  File "D:\Anaconda\envs\paddle\lib\site-packages\paddle\tensor\manipulation.py", line 331, in concat
    return paddle.fluid.layers.concat(input=x, axis=axis, name=name)
  File "D:\Anaconda\envs\paddle\lib\site-packages\paddle\fluid\layers\tensor.py", line 343, in concat
    _C_ops.concat(input, out, 'axis', axis)
OSError: (External) CUDA error(719), unspecified launch failure.
  [Hint: 'cudaErrorLaunchFailure'. An exception occurred on the device while executing a kernel. Common causes include dereferencing an invalid device pointerand accessing out of bounds shared 
memory. Less common cases can be system specific - more information about these cases canbe found in the system specific user guide. This leaves the process in an inconsistent state and any further CUDA work willreturn the same error. To continue using CUDA, the process must be terminated and relaunched.] (at ..\paddle\phi\backends\gpu\cuda\cuda_info.cc:258)
  [operator < concat > error]

**Comment by andyjpaddle** [comment]
有更改配置文件吗？有的话，详细描述下你这边改了啥

**Comment by slightly0** [comment]
> 有更改配置文件吗？有的话，详细描述下你改了啥

只修改了批次大小

**Comment by slightly0** [comment]
> 有更改配置文件吗？有话，详细描述下你改了啥

只修改了批次大小

**Comment by andyjpaddle** [comment]
训练命令是啥？paddle确保安装成功了吗

**Comment by slightly0** [comment]
> 训练命令是啥？paddle确保安装成功了吗

paddle安装成功的，使用vscode训练的，数据集也是按照配置文件里的路劲创建的

**Comment by andyjpaddle** [comment]
提供一下训练命令和配置文件吧

**Comment by slightly0** [comment]
> 提供一下训练命令和配置文件吧
![image](https://user-images.githubusercontent.com/113175005/189802549-2cc0005c-5c19-4ca0-aa96-c535882be8d9.png)

**Comment by slightly0** [comment]
> 提供一下训练命令和配置文件吧

其他的都是默认设置

**Comment by andyjpaddle** [comment]
num_workers改成0

**Comment by slightly0** [comment]
> num_workers改成0

改成0也会报错上面那个错QAQ

**Comment by andyjpaddle** [comment]
运行命令提供一下，windows只支持单卡训练

**Comment by slightly0** [comment]
我是通过VScode的debug运行的  
![image](https://user-images.githubusercontent.com/113175005/189822314-36dbfae8-78a9-4b22-bac1-ba2270ca9e3d.png)

**Comment by slightly0** [comment]
> 运行命令提供一下，windows只支持单卡训练

上面的图是我train.py的程序运行入口

**Comment by andyjpaddle** [comment]
按照文档在命令行执行训练指令

**Comment by slightly0** [comment]
> 按照文档在命令行执行训练指令
我只在文档上看到检测和部署命令  能给我发下相关文档吗

**Comment by andyjpaddle** [comment]
推理部署文档里面有给训练文档链接 https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/doc/doc_ch/kie.md

**Comment by slightly0** [comment]
> 推理部署文档里面有给训练文档链接 https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/doc/doc_ch/kie.md

[2022/09/13 14:23:01] ppocr INFO: During the training process, after the 0th iteration, an evaluation is run every 19 iterations
Error: ../paddle/phi/kernels/funcs/elementwise_functor.h:545 Assertion `b != 0` failed. InvalidArgumentError: Integer division by zero encountered in (floor) divide. Please check the input value.
Error: ../paddle/phi/kernels/funcs/elementwise_functor.h:545 Assertion `b != 0` failed. InvalidArgumentError: Integer division by zero encountered in (floor) divide. Please check the input value.
Error: ../paddle/phi/kernels/funcs/elementwise_functor.h:545 Assertion `b != 0` failed. InvalidArgumentError: Integer division by zero encountered in (floor) divide. Please check the input value.
Error: ../paddle/phi/kernels/funcs/elementwise_functor.h:545 Assertion `b != 0` failed. InvalidArgumentError: Integer division by zero encountered in (floor) divide. Please check the input value.
Error: ../paddle/phi/kernels/funcs/elementwise_functor.h:545 Assertion `b != 0` failed. InvalidArgumentError: Integer division by zero encountered in (floor) divide. Please check the input value.
Error: ../paddle/phi/kernels/funcs/elementwise_functor.h:545 Assertion `b != 0` failed. InvalidArgumentError: Integer division by zero encountered in (floor) divide. Please check the input value.
Error: ../paddle/phi/kernels/funcs/elementwise_functor.h:545 Assertion `b != 0` failed. InvalidArgumentError: Integer division by zero encountered in (floor) divide. Please check the input value.
Error: ../paddle/phi/kernels/funcs/elementwise_functor.h:545 Assertion `b != 0` failed. InvalidArgumentError: Integer division by zero encountered in (floor) divide. Please check the input value.
Error: ../paddle/phi/kernels/funcs/elementwise_functor.h:545 Assertion `b != 0` failed. InvalidArgumentError: Integer division by zero encountered in (floor) divide. Please check the input value.
Error: ../paddle/phi/kernels/funcs/elementwise_functor.h:545 Assertion `b != 0` failed. InvalidArgumentError: Integer division by zero encountered in (floor) divide. Please check the input value.
Error: ../paddle/phi/kernels/funcs/elementwise_functor.h:545 Assertion `b != 0` failed. InvalidArgumentError: Integer division by zero encountered in (floor) divide. Please check the input value.
Error: ../paddle/phi/kernels/funcs/elementwise_functor.h:545 Assertion `b != 0` failed. InvalidArgumentError: Integer division by zero encountered in (floor) divide. Please check the input value.
Error: ../paddle/phi/kernels/funcs/elementwise_functor.h:545 Assertion `b != 0` failed. InvalidArgumentError: Integer division by zero encountered in (floor) divide. Please check the input value.
Error: ../paddle/phi/kernels/funcs/elementwise_functor.h:545 Assertion `b != 0` failed. InvalidArgumentError: Integer division by zero encountered in (floor) divide. Please check the input value.
Error: ../paddle/phi/kernels/funcs/elementwise_functor.h:545 Assertion `b != 0` failed. InvalidArgumentError: Integer division by zero encountered in (floor) divide. Please check the input value.
Error: ../paddle/phi/kernels/funcs/elementwise_functor.h:545 Assertion `b != 0` failed. InvalidArgumentError: Integer division by zero encountered in (floor) divide. Please check the input value.
Error: ../paddle/phi/kernels/funcs/elementwise_functor.h:545 Assertion `b != 0` failed. InvalidArgumentError: Integer division by zero encountered in (floor) divide. Please check the input value.
Error: ../paddle/phi/kernels/funcs/elementwise_functor.h:545 Assertion `b != 0` failed. InvalidArgumentError: Integer division by zero encountered in (floor) divide. Please check the input value.
Error: ../paddle/phi/kernels/funcs/elementwise_functor.h:545 Assertion `b != 0` failed. InvalidArgumentError: Integer division by zero encountered in (floor) divide. Please check the input value.
Error: ../paddle/phi/kernels/funcs/elementwise_functor.h:545 Assertion `b != 0` failed. InvalidArgumentError: Integer division by zero encountered in (floor) divide. Please check the input value.
Error: ../paddle/phi/kernels/funcs/elementwise_functor.h:545 Assertion `b != 0` failed. InvalidArgumentError: Integer division by zero encountered in (floor) divide. Please check the input value.
Error: ../paddle/phi/kernels/funcs/elementwise_functor.h:545 Assertion `b != 0` failed. InvalidArgumentError: Integer division by zero encountered in (floor) divide. Please check the input value.
Error: ../paddle/phi/kernels/funcs/elementwise_functor.h:545 Assertion `b != 0` failed. InvalidArgumentError: Integer division by zero encountered in (floor) divide. Please check the input value.
Error: ../paddle/phi/kernels/funcs/elementwise_functor.h:545 Assertion `b != 0` failed. InvalidArgumentError: Integer division by zero encountered in (floor) divide. Please check the input value.
Error: ../paddle/phi/kernels/funcs/elementwise_functor.h:545 Assertion `b != 0` failed. InvalidArgumentError: Integer division by zero encountered in (floor) divide. Please check the input value.
Error: ../paddle/phi/kernels/funcs/elementwise_functor.h:545 Assertion `b != 0` failed. InvalidArgumentError: Integer division by zero encountered in (floor) divide. Please check the input value.
Error: ../paddle/phi/kernels/funcs/elementwise_functor.h:545 Assertion `b != 0` failed. InvalidArgumentError: Integer division by zero encountered in (floor) divide. Please check the input value.
Error: ../paddle/phi/kernels/funcs/elementwise_functor.h:545 Assertion `b != 0` failed. InvalidArgumentError: Integer division by zero encountered in (floor) divide. Please check the input value.
Error: ../paddle/phi/kernels/funcs/elementwise_functor.h:545 Assertion `b != 0` failed. InvalidArgumentError: Integer division by zero encountered in (floor) divide. Please check the input value.
Error: ../paddle/phi/kernels/funcs/elementwise_functor.h:545 Assertion `b != 0` failed. InvalidArgumentError: Integer division by zero encountered in (floor) divide. Please check the input value.
Error: ../paddle/phi/kernels/funcs/elementwise_functor.h:545 Assertion `b != 0` failed. InvalidArgumentError: Integer division by zero encountered in (floor) divide. Please check the input value.
Error: ../paddle/phi/kernels/funcs/elementwise_functor.h:545 Assertion `b != 0` failed. InvalidArgumentError: Integer division by zero encountered in (floor) divide. Please check the input value.
Traceback (most recent call last):
  File "tools/train.py", line 209, in <module>
    main(config, device, logger, vdl_writer)
  File "tools/train.py", line 175, in main
    program.train(config, train_dataloader, valid_dataloader, device, model,
  File "E:\吉元\脚本测试文件\模型\PaddleOCR-release-2.6\tools\program.py", line 304, in train
    preds = model(batch)
  File "D:\Anaconda\envs\paddle\lib\site-packages\paddle\fluid\dygraph\layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "D:\Anaconda\envs\paddle\lib\site-packages\paddle\fluid\dygraph\layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "E:\吉元\脚本测试文件\模型\PaddleOCR-release-2.6\ppocr\modeling\architectures\base_model.py", line 86, in forward
    x = self.backbone(x)
  File "D:\Anaconda\envs\paddle\lib\site-packages\paddle\fluid\dygraph\layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "D:\Anaconda\envs\paddle\lib\site-packages\paddle\fluid\dygraph\layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "E:\吉元\脚本测试文件\模型\PaddleOCR-release-2.6\ppocr\modeling\backbones\vqa_layoutlm.py", line 166, in forward
    x = self.model(
  File "D:\Anaconda\envs\paddle\lib\site-packages\paddle\fluid\dygraph\layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "D:\Anaconda\envs\paddle\lib\site-packages\paddle\fluid\dygraph\layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "D:\Anaconda\envs\paddle\lib\site-packages\paddlenlp\transformers\layoutxlm\modeling.py", line 1040, in forward
    outputs = self.layoutxlm(
  File "D:\Anaconda\envs\paddle\lib\site-packages\paddle\fluid\dygraph\layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "D:\Anaconda\envs\paddle\lib\site-packages\paddle\fluid\dygraph\layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "D:\Anaconda\envs\paddle\lib\site-packages\paddlenlp\transformers\layoutxlm\modeling.py", line 911, in forward
    visual_bbox = paddle.stack(
  File "D:\Anaconda\envs\paddle\lib\site-packages\paddle\tensor\manipulation.py", line 903, in stack
    return layers.stack(x, axis, name)
  File "D:\Anaconda\envs\paddle\lib\site-packages\paddle\fluid\layers\nn.py", line 10397, in stack
    return _C_ops.stack(x, 'axis', axis)
OSError: (External) CUDA error(719), unspecified launch failure.
  [Hint: 'cudaErrorLaunchFailure'. An exception occurred on the device while executing a kernel. Common causes include dereferencing an invalid device pointerand accessing out of bounds shared memory. Less common cases can be system specific - more information about these cases canbe found in the system specific user guide. This leaves the process in an inconsistent state and any further CUDA work willreturn the same error. To continue using CUDA, the process must be terminated and relaunched.] (at ..\paddle\phi\backends\gpu\cuda\cuda_info.cc:251)
  [operator < stack > error]

**Comment by slightly0** [comment]
> 推理部署文档里面有给训练文档链接 https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/doc/doc_ch/kie.md
报的还是之前的错误

**Comment by andyjpaddle** [comment]
先测试下paddle能否正常运行
```
import paddle
paddle.utils.run_check()
```
如果正常，提供一下完整的配置文件和运行命令

**Comment by slightly0** [comment]
> 先测试下paddle能否正常运行

![image](https://user-images.githubusercontent.com/113175005/189826568-b3cee435-7415-4c05-a01d-2eb5343c9803.png)
可以正常运行

**Comment by slightly0** [comment]
Global:
  use_gpu: True
  epoch_num: &epoch_num 200
  log_smooth_window: 10
  print_batch_step: 10
  save_model_dir: ./output/ser_layoutlm_xfund_zh
  save_epoch_step: 2000
  # evaluation is run every 10 iterations after the 0th iteration
  eval_batch_step: [ 0, 19 ]
  cal_metric_during_train: False
  save_inference_dir:
  use_visualdl: False
  seed: 2022
  infer_img: ppstructure/docs/kie/input/zh_val_42.jpg
  save_res_path: ./output/re_layoutlm_xfund_zh/res

Architecture:
  model_type: kie
  algorithm: &algorithm "LayoutLM"
  Transform:
  Backbone:
    name: LayoutLMForSer
    pretrained: True
    checkpoints:
    num_classes: &num_classes 7

Loss:
  name: VQASerTokenLayoutLMLoss
  num_classes: *num_classes

Optimizer:
  name: AdamW
  beta1: 0.9
  beta2: 0.999
  lr:
    name: Linear
    learning_rate: 0.00005
    epochs: *epoch_num
    warmup_epoch: 2
  regularizer:
    name: L2
    factor: 0.00000
    
PostProcess:
  name: VQASerTokenLayoutLMPostProcess
  class_path: &class_path train_data/XFUND/class_list_xfun.txt

Metric:
  name: VQASerTokenMetric
  main_indicator: hmean

Train:
  dataset:
    name: SimpleDataSet
    data_dir: train_data/XFUND/zh_train/image
    label_file_list: 
      - train_data/XFUND/zh_train/train.json
    ratio_list: [ 1.0 ]
    transforms:
      - DecodeImage: # load image
          img_mode: RGB
          channel_first: False
      - VQATokenLabelEncode: # Class handling label
          contains_re: False
          algorithm: *algorithm
          class_path: *class_path
      - VQATokenPad:
          max_seq_len: &max_seq_len 512
          return_attention_mask: True
      - VQASerTokenChunk:
          max_seq_len: *max_seq_len
      - Resize:
          size: [224,224]
      - NormalizeImage:
          scale: 1
          mean: [ 123.675, 116.28, 103.53 ]
          std: [ 58.395, 57.12, 57.375 ]
          order: 'hwc' 
      - ToCHWImage:
      - KeepKeys:
          keep_keys: [ 'input_ids', 'bbox', 'attention_mask', 'token_type_ids', 'image', 'labels'] # dataloader will return list in this order
  loader:
    shuffle: True
    drop_last: False
    batch_size_per_card: 1
    num_workers: 0

Eval:
  dataset:
    name: SimpleDataSet
    data_dir: train_data/XFUND/zh_val/image
    label_file_list:
      - train_data/XFUND/zh_val/val.json
    transforms:
      - DecodeImage: # load image
          img_mode: RGB
          channel_first: False
      - VQATokenLabelEncode: # Class handling label
          contains_re: False
          algorithm: *algorithm
          class_path: *class_path
      - VQATokenPad:
          max_seq_len: *max_seq_len
          return_attention_mask: True
      - VQASerTokenChunk:
          max_seq_len: *max_seq_len
      - Resize:
          size: [224,224]
      - NormalizeImage:
          scale: 1
          mean: [ 123.675, 116.28, 103.53 ]
          std: [ 58.395, 57.12, 57.375 ]
          order: 'hwc'
      - ToCHWImage:
      - KeepKeys:
          keep_keys: [ 'input_ids', 'bbox', 'attention_mask', 'token_type_ids', 'image', 'labels'] # dataloader will return list in this order
  loader:
    shuffle: False
    drop_last: False
    batch_size_per_card: 8
    num_workers: 4

**Comment by slightly0** [comment]
![image](https://user-images.githubusercontent.com/113175005/189826987-2549afe8-61b8-4e87-a6d3-f0fbeafa8fcb.png)
![image](https://user-images.githubusercontent.com/113175005/189827377-20a21af9-8c1e-47e2-8e3e-3f67063624bd.png)
![image](https://user-images.githubusercontent.com/113175005/189827484-2fbbf2e1-c7ee-4ded-aed4-dbd758cd45a1.png)
![image](https://user-images.githubusercontent.com/113175005/189827519-f58fdeb0-a35b-40a5-ac87-f2a9f1622442.png)
运行命令
![image](https://user-images.githubusercontent.com/113175005/189827683-e61381bf-6ab7-4611-ba1e-632298d83af0.png)

**Comment by littletomatodonkey** [comment]
你好，看你配置写的是layoutlm，但是代码报错走到了layoutxlm.py文件中了，这里建议安装下paddlenlp：https://paddleocr.bj.bcebos.com/ppstructure/whl/paddlenlp-2.3.0.dev0-py3-none-any.whl


同时拉下最新代码和数据看下：https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/configs/kie/layoutlm_series/ser_layoutlm_xfund_zh.yml

**Comment by slightly0** [comment]
> 你好，看你配置写的是layoutlm，但是代码报错了layoutxlm.py文件中了，这里建议安装下paddlenlp：[https://paddleocr.bj.bcebos.com/ppstructure/whl/paddlenlp-2.3.0 。 dev0-py3-none-any.whl](https://paddleocr.bj.bcebos.com/ppstructure/whl/paddlenlp-2.3.0.dev0-py3-none-any.whl)
> 
> 拉下最新代码和数据看下：https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/configs/kie/layoutlm_series/ser_layoutlm_xfund_zh.yml

好的 我拉下最新的代码看下

**Comment by slightly0** [comment]
> 你好，看你配置写的是layoutlm，但是代码报错了layoutxlm.py文件中了，这里建议安装下paddlenlp：[https://paddleocr.bj.bcebos.com/ppstructure/whl/paddlenlp-2.3.0 。 dev0-py3-none-any.whl](https://paddleocr.bj.bcebos.com/ppstructure/whl/paddlenlp-2.3.0.dev0-py3-none-any.whl)
> 
> 拉下最新代码和数据看下：https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/configs/kie/layoutlm_series/ser_layoutlm_xfund_zh.yml

最新的代码  报错还是一样 错误发生在paddle.tensor数据计算时报错，最终定位报错位置是在以下这个文件中
![image](https://user-images.githubusercontent.com/113175005/189838246-9d53d8d9-831b-4f53-9af8-789f00e045bc.png)

**Comment by littletomatodonkey** [comment]
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/14270174/190042888-ff5f2674-5847-4733-bae9-005b840c593a.png">

你好，我这边训练比较正常，你可以拉下代码再试下，建议先不要修改配置文件，按照教程先把流程走通

* paddlenlp：https://paddleocr.bj.bcebos.com/ppstructure/whl/paddlenlp-2.3.0.dev0-py3-none-any.whl
* xfund数据地址： https://paddleocr.bj.bcebos.com/ppstructure/dataset/XFUND.tar
* paddlepaddle：2.3.1
* paddleocr：dygraph

**Comment by husiluanxiang** [comment]
> <img alt="image" width="1440" src="https://user-images.githubusercontent.com/14270174/190042888-ff5f2674-5847-4733-bae9-005b840c593a.png">
> 
> 你好，我这边训练比较正常，你可以拉下代码再试下，建议先不要修改配置文件，按照教程先把流程走通
> 
> * paddlenlp：https://paddleocr.bj.bcebos.com/ppstructure/whl/paddlenlp-2.3.0.dev0-py3-none-any.whl
> * xfund数据地址： https://paddleocr.bj.bcebos.com/ppstructure/dataset/XFUND.tar
> * paddlepaddle：2.3.1
> * paddleocr：dygraph

我也是同样的错误
[2022/09/27 13:54:04] ppocr INFO: train dataloader has 149 iters
[2022/09/27 13:54:04] ppocr INFO: valid dataloader has 50 iters
[2022/09/27 13:54:04] ppocr INFO: During the training process, after the 0th iteration, an evaluation is run every 19 iterations
Traceback (most recent call last):
  File "D:\QB\pypro\PaddleOCR\tools\train.py", line 202, in <module>
    main(config, device, logger, vdl_writer)
  File "D:\QB\pypro\PaddleOCR\tools\train.py", line 175, in main
    program.train(config, train_dataloader, valid_dataloader, device, model,
  File "D:\QB\pypro\PaddleOCR\tools\program.py", line 320, in train
    loss = loss_class(preds, batch)
  File "D:\QB\Anaconda3\lib\site-packages\paddle\fluid\dygraph\layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "D:\QB\Anaconda3\lib\site-packages\paddle\fluid\dygraph\layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "D:\QB\pypro\PaddleOCR\ppocr\losses\vqa_token_layoutlm_loss.py", line 41, in forward
    loss = self.loss_class(active_output, active_label)
  File "D:\QB\Anaconda3\lib\site-packages\paddle\fluid\dygraph\layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "D:\QB\Anaconda3\lib\site-packages\paddle\fluid\dygraph\layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "D:\QB\Anaconda3\lib\site-packages\paddle\nn\layer\loss.py", line 397, in forward
    ret = paddle.nn.functional.cross_entropy(
  File "D:\QB\Anaconda3\lib\site-packages\paddle\nn\functional\loss.py", line 1718, in cross_entropy
    if label_min < 0:
  File "D:\QB\Anaconda3\lib\site-packages\paddle\fluid\dygraph\varbase_patch_methods.py", line 669, in __bool__
    return self.__nonzero__()
  File "D:\QB\Anaconda3\lib\site-packages\paddle\fluid\dygraph\varbase_patch_methods.py", line 666, in __nonzero__
    return bool(np.all(tensor.__array__() > 0))
OSError: (External) CUDA error(719), unspecified launch failure. 
  [Hint: 'cudaErrorLaunchFailure'. An exception occurred on the device while executing a kernel. Common causes include dereferencing an invalid device pointerand accessing out of bounds shared memory. Less common cases can be system specific - more information about these cases canbe found in the system specific user guide. This leaves the process in an inconsistent state and any further CUDA work willreturn the same error. To continue using CUDA, the process must be terminated and relaunched.] (at ..\paddle\phi\backends\gpu\cuda\cuda_info.cc:258)
这个错误是和显卡有关吗？你们的程序运行是不是基于V100的基础来运行的
