### ISSUE TITLE
ImportError: libcudart.so.10.2: cannot open shared object file: No such file or directory 

### ISSUE THREAD

**Issue by Mrfuhang** [PaddlePaddle/PaddleOCR#9049]
Has the problem been solved?

**Comment by LDOUBLEV** [comment]
An error message indicates that the cuda.so file cannot be found, please check whether libcudart.so.10.2 exists in the cuda/lib64 directory
if exists:
You can get the cuda version of your machine through the `nvcc -V` command.
Then install the cuda version suitable for your machine such as
```
pip install paddlepaddle-gpu==2.4.1 -i https://pypi.tuna.tsinghua.edu.cn/simple
pip install paddlepaddle-gpu==2.4.1.post112 -f https://www.paddlepaddle.org.cn/whl/linux/mkl/avx/stable.html
pip install paddlepaddle-gpu==2.4.1.post116 -f https://www.paddlepaddle.org.cn/whl/linux/mkl/avx/stable.html
```
if not :
Redirect the libcudart.so.10.2 file to a new directory
such as 
`sudo ldconfig /usr/local/your installed cuda path/lib64`

**Comment by Mrfuhang** [comment]
> An error message indicates that the cuda.so file cannot be found, please check whether libcudart.so.10.2 exists in the cuda/lib64 directory if exists: You can get the cuda version of your machine through the `nvcc -V` command. Then install the cuda version suitable for your machine such as
> 
> ```
> pip install paddlepaddle-gpu==2.4.1 -i https://pypi.tuna.tsinghua.edu.cn/simple
> pip install paddlepaddle-gpu==2.4.1.post112 -f https://www.paddlepaddle.org.cn/whl/linux/mkl/avx/stable.html
> pip install paddlepaddle-gpu==2.4.1.post116 -f https://www.paddlepaddle.org.cn/whl/linux/mkl/avx/stable.html
> ```
> 
> if not : Redirect the libcudart.so.10.2 file to a new directory such as `sudo ldconfig /usr/local/your installed cuda path/lib64`

ImportError: libcudart.so.11.0: cannot open shared object file: No such file or directory

**Comment by Siddhijain16** [comment]
How to resolve this issue , any update ?

**Comment by smallzhao** [comment]
```
conda install cudatoolkit=10.2
export LD_LIBRARY_PATH=~/miniconda3/envs/env_paddle/lib
```
this works for me

**Comment by Fissionalist** [comment]
> ```
> conda install cudatoolkit=10.2
> export LD_LIBRARY_PATH=~/miniconda3/envs/env_paddle/lib
> ```
> 
> this works for me

谢谢，这样可以解决问题。
因为在conda环境中PaddlePaddle的whl安装包将库文件安装在了`~/anaconda3/envs/paddle_env/lib`目录下，但系统运行脚本时默认不会搜索这个目录,所以找不到相关库文件。设置`LD_LIBRARY_PATH`环境变量后，系统就会在这个目录下搜索动态链接库文件。
但是每一次重启系统后都会被重置，又得再运行一遍这行指令，我希望能有一劳永逸解决这个问题的方案，比如：
1. 给训练脚本添加这个环境变量设置。

例如，在`tools/train.py`脚本开头添加：
```python
import os
os.environ['LD_LIBRARY_PATH'] = 'your_paddle_env/lib'
```
2. 添加环境变量设置到系统环境中。以Ubuntu为例：

打开系统环境变量配置文件，执行：
```shell
sudo gedit /etc/environment
```
在里面添加一行:
```shell
LD_LIBRARY_PATH=/your/paddle/env/lib
```
保存退出。
3. 如果没有更改系统环境变量的权限，可以在home下的.bashrc或.zshrc配置文件里加：
```shell
export LD_LIBRARY_PATH=/your/paddle/env/lib
```
保存退出后执行：
```shell
source .bashrc
```
希望这些方法有效。
