### ISSUE TITLE
SAST inference error - OSError: (External) CUDNN error(9), CUDNN_STATUS_NOT_SUPPORTED

### ISSUE THREAD

**Issue by htdung167** [PaddlePaddle/PaddleOCR#9545]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：Google Colab, Ubuntu 20.04.5 LTS, CUDA 11.8
- 版本号/Version：Paddle：0.0.0.post117  PaddleOCR：2.6.1.3 

I am training text detection model on google colab. All models is fine. 

But when using command tools/infer/predict_det.py with SAST after exporting, I got error OSError: (External) CUDNN error(9), CUDNN_STATUS_NOT_SUPPORTED.

I tried with other Paddle and PaddleOCR version but I still got this error. 

I appreciate your help.

- Command:
!python3 tools/infer/predict_det.py --det_algorithm="SAST" \
                                    --use_gpu=True \
                                    --det_model_dir=/content/drive/MyDrive/OCR/inference/det_r50_vd_sast_icdar15_v2.0_train \
                                    --draw_img_save_dir=/content/drive/MyDrive/OCR/det_r50_vd_sast_icdar15_v2.0_train \
                                    --image_dir=/content/images

- Error Message:
Traceback (most recent call last):
  File "/content/drive/OCR/PaddleOCR/tools/infer/predict_det.py", line 315, in <module>
    dt_boxes, _ = text_detector(img)
  File "/content/drive/OCR/PaddleOCR/tools/infer/predict_det.py", line 243, in __call__
    self.predictor.run()
OSError: (External) CUDNN error(9), CUDNN_STATUS_NOT_SUPPORTED. 
  [Hint: Please search for the error code(9) on website (https://docs.nvidia.com/deeplearning/cudnn/api/index.html#cudnnStatus_t) to get Nvidia's official solution and advice about CUDNN Error.] (at /paddle/paddle/phi/kernels/fusion/gpu/conv_fusion_kernel.cu:609)
  [operator < conv2d_fusion > error]

**Comment by MissPenguin** [comment]
You're running the inference command with pre-trained model. Try to replace the `det_model_dir` with inference model.

**Comment by htdung167** [comment]
> * Google Colab, Ubuntu 20.04.5 LTS, CUDA 11.8

Thanks for your reply.

I exported trained model to inference model. The above dir is inference model.
And it worked fine when --use_gpu=False.
So i think the problem is version conflict.

**Comment by pansinm** [comment]
EAST推理也报错，使用`--user_gpu False`能够正常执行
> NVIDIA-SMI 515.43.04    Driver Version: 515.43.04    CUDA Version: 11.7
> cudnn-linux-x86_64-8.9.2.26_cuda11
```bash
$ python3 tools/infer/predict_det.py --image_dir="images" --det_model_dir="./inference/det_r50_east/" --det_algorithm="EAST"  
```

```
/home/pansinm/miniconda3/envs/paddle/lib/python3.9/site-packages/pkg_resources/__init__.py:121: DeprecationWarning: pkg_resources is deprecated as an API
  warnings.warn("pkg_resources is deprecated as an API", DeprecationWarning)
/home/pansinm/miniconda3/envs/paddle/lib/python3.9/site-packages/pkg_resources/__init__.py:2870: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('mpl_toolkits')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
/home/pansinm/miniconda3/envs/paddle/lib/python3.9/site-packages/pkg_resources/__init__.py:2870: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('google')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
------------- <ppocr.postprocess.east_postprocess.EASTPostProcess object at 0x7fba100a22b0>
Traceback (most recent call last):
  File "/home/pansinm/workspace/casstime/PaddleOCR/tools/infer/predict_det.py", line 315, in <module>
    dt_boxes, _ = text_detector(img)
  File "/home/pansinm/workspace/casstime/PaddleOCR/tools/infer/predict_det.py", line 243, in __call__
    self.predictor.run()
OSError: (External) CUDNN error(9), CUDNN_STATUS_NOT_SUPPORTED. 
  [Hint: Please search for the error code(9) on website (https://docs.nvidia.com/deeplearning/cudnn/api/index.html#cudnnStatus_t) to get Nvidia's official solution and advice about CUDNN Error.] (at /paddle/paddle/fluid/operators/fused/conv_fusion_op.cu:519)
  [operator < conv2d_fusion > error]
```

**Comment by keyfall** [comment]
我知道答案，你先看看cuda中是否复制过了cudnn，如果有的话，可能是我这个问题：我这里是本机安装了cuda和cudnn，conda安装了cuda和cudnn，我这里tools/train.py可以，tools/infer/predict_det.py就会报上述错误，这里我发现conda虚拟环境运行命令时使用的cuda一直是本地的cuda，然后cudnn用的是虚拟环境的cudnn，直接说结果
修改环境变量，我这里加上了一个`/usr/local/cuda-11.7/lib64`,使用了这个应该就会把设置的cuda设置为一直调用的cuda，所以把这句删了，就好了

**Comment by keyfall** [comment]
试一下这个，你先看看cuda中是否复制过了cudnn，如果有的话，可能是我这个问题：我这里是本机安装了cuda和cudnn，conda安装了cuda和cudnn，我这里tools/train.py可以，tools/infer/predict_det.py就会报上述错误，这里我发现conda虚拟环境运行命令时使用的cuda一直是本地的cuda，然后cudnn用的是虚拟环境的cudnn，直接说结果
修改环境变量，我这里加上了一个/usr/local/cuda-11.7/lib64,使用了这个应该就会把设置的cuda设置为一直调用的cuda，所以把这句删了，就好了

**Comment by yes-github** [comment]
安装paddlepaddle-gpu==2.4.2.post116遇到相同问题，换cuDNN v8.4.0 (April 1st, 2022), for CUDA 11.x版本后解决，下载地址：
https://developer.nvidia.com/rdp/cudnn-archive
