### ISSUE TITLE
安装好环境后试运行提示缺少库cudnn64_7.dll

### ISSUE THREAD

**Issue by ozxdno** [PaddlePaddle/PaddleOCR#9913]
系统：Win10
GPU：RTX3070TI
CUDA：11.3
CUDNN：8.9.1
paddleocr：2.6.1.3
paddlepaddle-gpu：2.4.2

CUDA 是对应了GPU装的11.3，能找到对应11.3的所有CUDNN版本都找不到cudnn64_7.dll，只有cudnn64_8.dll
我需要下载cudnn64_7.dll直接放到cudnn64_8.dll同目录下，还是说有别的解决办法？

报错详细信息：
RuntimeError: (PreconditionNotMet) The third-party dynamic library (cudnn64_7.dll) that Paddle depends on is not configured correctly. (error code is 126)

**Comment by ozxdno** [comment]
解决了。去官网看对应GPU的安装方法。例如我的：
pip install paddlepaddle-gpu==2.4.2.post112 -f https://www.paddlepaddle.org.cn/whl/windows/mkl/avx/stable.html
