### ISSUE TITLE
PaddleeOCR, GPU进行推理报错FatalError: `Segmentation fault` is detected by the operating system

### ISSUE THREAD

**Issue by lucky0604** [PaddlePaddle/PaddleOCR#9929]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：Ubuntu20.04
- 版本号/Version：
    - Paddle：  paddlepaddle-gpu==2.4.2
    - PaddleOCR： paddleocr==2.6.1
    - Python: 3.9
    - Cuda: 11.2
    - Cudnn: 8.2.1
  问题相关组件/Related components：PaddleOCR
> 关于paddlepaddle-gpu版本，我的cuda版本是11.2，cudnn版本为8.2.1，如果直接pip install paddlepaddle-gpu，可以默认安装paddlepaddle-gpu2.4.2版本，此时运行`paddle.utils.run_check`是正常的，但是如果按照官网安装paddlepaddle-gpu-2.4.2.post112，则报下面的错误
```shell
OSError: In user code:

    File "<stdin>", line 1, in <module>
      
    File "/root/miniconda3/envs/paddleocr/lib/python3.9/site-packages/paddle/utils/install_check.py", line 269, in run_check
      _run_static_single(use_cuda, use_xpu, use_npu)
    File "/root/miniconda3/envs/paddleocr/lib/python3.9/site-packages/paddle/utils/install_check.py", line 159, in _run_static_single
      input, out, weight = _simple_network()
    File "/root/miniconda3/envs/paddleocr/lib/python3.9/site-packages/paddle/utils/install_check.py", line 38, in _simple_network
      linear_out = paddle.nn.functional.linear(x=input, weight=weight, bias=bias)
    File "/root/miniconda3/envs/paddleocr/lib/python3.9/site-packages/paddle/nn/functional/common.py", line 1911, in linear
      helper.append_op(
    File "/root/miniconda3/envs/paddleocr/lib/python3.9/site-packages/paddle/fluid/layer_helper.py", line 45, in append_op
      return self.main_program.current_block().append_op(*args, **kwargs)
    File "/root/miniconda3/envs/paddleocr/lib/python3.9/site-packages/paddle/fluid/framework.py", line 4040, in append_op
      op = Operator(
    File "/root/miniconda3/envs/paddleocr/lib/python3.9/site-packages/paddle/fluid/framework.py", line 2879, in __init__
      for frame in traceback.extract_stack():

    ExternalError: CUBLAS error(7). 
      [Hint: Please search for the error code(7) on website (https://docs.nvidia.com/cuda/cublas/index.html#cublasstatus_t) to get Nvidia's offici
al solution and advice about CUBLAS Error.] (at /paddle/paddle/phi/backends/gpu/gpu_context.cc:593)
      [operator < matmul_v2 > error]
```

如果安装`paddlepaddle-gpu==2.4.2`(非post112版本)，运行以下示例代码报错
- 运行指令/Command Code：
示例程序
```python
from paddleocr import PaddleOCR, draw_ocr

# Paddleocr目前支持的多语言语种可以通过修改lang参数进行切换
# 例如`ch`, `en`, `fr`, `german`, `korean`, `japan`
ocr = PaddleOCR(use_angle_cls=True, lang="ch", use_gpu=False)  # need to run only once to download and load model into memory
img_path = './imgs/11.jpg'
result = ocr.ocr(img_path, cls=True)
for idx in range(len(result)):
    res = result[idx]
    for line in res:
        print(line)

# 显示结果
# 如果本地没有simfang.ttf，可以在doc/fonts目录下下载
from PIL import Image
result = result[0]
image = Image.open(img_path).convert('RGB')
boxes = [line[0] for line in result]
txts = [line[1][0] for line in result]
scores = [line[1][1] for line in result]
im_show = draw_ocr(image, boxes, txts, scores, font_path='doc/fonts/simfang.ttf')
im_show = Image.fromarray(im_show)
im_show.save('result.jpg')
```
- 完整报错/Complete Error Message：
```shell
C++ Traceback (most recent call last):
--------------------------------------
No stack trace in paddle, may be caused by external reasons.

----------------------
Error Message Summary:
----------------------
FatalError: `Segmentation fault` is detected by the operating system.
  [TimeInfo: *** Aborted at 1683877065 (unix time) try "date -d @1683877065" if you are using GNU date ***]
  [SignalInfo: *** SIGSEGV (@0x0) received by PID 120083 (TID 0x7f4c92b5c280) from PID 0 ***]

Segmentation fault (core dumped)
```

- 补充
之前我的cuda版本是11.4，cudnn 8.4，也是这种情况，`paddlepaddle-gpu==2.4.2`正常run_check()，但是执行代码就报错segmentation fault，后面按照官网指定的几个版本更换到了cuda11.2，仍然是这种情况
cuda和cudnn是正常的，因为在用另外一个paddlenlp的项目中是正常跑的，就是paddleocr会报错

**Comment by aiXia121** [comment]
paddleocr --image_dir ./test_image/t1.jpg --use_angle_cls true --use_gpu false
不会报错


$paddleocr --image_dir ./test_image/t1.jpg --use_angle_cls true
/data/xxxxx/miniconda3/lib/python3.8/site-packages/skimage/morphology/_skeletonize.py:241: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  0, 1, 1, 0, 0, 1, 0, 0, 0], dtype=np.bool)
/data/xxxxxx/miniconda3/lib/python3.8/site-packages/skimage/morphology/_skeletonize.py:256: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=np.bool)
/data/xxxxx/miniconda3/lib/python3.8/site-packages/skimage/restoration/inpaint.py:6: DeprecationWarning: Please use `laplace` from the `scipy.ndimage` namespace, the `scipy.ndimage.filters` namespace is deprecated.
  from scipy.ndimage.filters import laplace
/data/xxxxx/miniconda3/lib/python3.8/site-packages/skimage/feature/_orb_descriptor_positions.py:8: DeprecationWarning: loadtxt(): Parsing an integer via a float is deprecated.  To avoid this warning, you can:
    * make sure the original data is stored as integers.
    * use the `converters=` keyword argument.  If you only use
      NumPy 1.23 or later, `converters=float` will normally work.
    * Use `np.loadtxt(...).astype(np.int64)` parsing the file as
      floating point and then convert it.  (On all NumPy versions.)
  (Deprecated NumPy 1.23)
  POS = np.loadtxt(os.path.join(this_dir, "orb_descriptor_positions.txt"),
/data/xxxxx/miniconda3/lib/python3.8/site-packages/skimage/filters/_unsharp_mask.py:2: DeprecationWarning: Please use `gaussian_filter` from the `scipy.ndimage` namespace, the `scipy.ndimage.filters` namespace is deprecated.
  from scipy.ndimage.filters import gaussian_filter
/data/xxxxxxx/miniconda3/lib/python3.8/site-packages/skimage/segmentation/random_walker_segmentation.py:49: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  if Version(scipy.__version__) >= Version('1.1'):
[2023/06/30 11:32:28] ppocr DEBUG: Namespace(alpha=1.0, benchmark=False, beta=1.0, cls_batch_num=6, cls_image_shape='3, 48, 192', cls_model_dir='/home/xxxxx/.paddleocr/whl/cls/ch_ppocr_mobile_v2.0_cls_infer', cls_thresh=0.9, cpu_threads=10, crop_res_save_dir='./output', det=True, det_algorithm='DB', det_box_type='quad', det_db_box_thresh=0.6, det_db_score_mode='fast', det_db_thresh=0.3, det_db_unclip_ratio=1.5, det_east_cover_thresh=0.1, det_east_nms_thresh=0.2, det_east_score_thresh=0.8, det_limit_side_len=960, det_limit_type='max', det_model_dir='/home/xxxxx/.paddleocr/whl/det/ch/ch_PP-OCRv3_det_infer', det_pse_box_thresh=0.85, det_pse_min_area=16, det_pse_scale=1, det_pse_thresh=0, det_sast_nms_thresh=0.2, det_sast_score_thresh=0.5, draw_img_save_dir='./inference_results', drop_score=0.5, e2e_algorithm='PGNet', e2e_char_dict_path='./ppocr/utils/ic15_dict.txt', e2e_limit_side_len=768, e2e_limit_type='max', e2e_model_dir=None, e2e_pgnet_mode='fast', e2e_pgnet_score_thresh=0.5, e2e_pgnet_valid_set='totaltext', enable_mkldnn=False, fourier_degree=5, gpu_mem=500, help='==SUPPRESS==', image_dir='./test_image/t1.jpg', image_orientation=False, ir_optim=True, kie_algorithm='LayoutXLM', label_list=['0', '180'], lang='ch', layout=True, layout_dict_path=None, layout_model_dir=None, layout_nms_threshold=0.5, layout_score_threshold=0.5, max_batch_size=10, max_text_length=25, merge_no_span_structure=True, min_subgraph_size=15, mode='structure', ocr=True, ocr_order_method=None, ocr_version='PP-OCRv3', output='./output', page_num=0, precision='fp32', process_id=0, re_model_dir=None, rec=True, rec_algorithm='SVTR_LCNet', rec_batch_num=6, rec_char_dict_path='/data/xxxxx/miniconda3/lib/python3.8/site-packages/paddleocr/ppocr/utils/ppocr_keys_v1.txt', rec_image_inverse=True, rec_image_shape='3, 48, 320', rec_model_dir='/home/yuyongbo/.paddleocr/whl/rec/ch/ch_PP-OCRv3_rec_infer', recovery=False, save_crop_res=False, save_log_path='./log_output/', scales=[8, 16, 32], ser_dict_path='../train_data/XFUND/class_list_xfun.txt', ser_model_dir=None, show_log=True, sr_batch_num=1, sr_image_shape='3, 32, 128', sr_model_dir=None, structure_version='PP-StructureV2', table=True, table_algorithm='TableAttn', table_char_dict_path=None, table_max_len=488, table_model_dir=None, total_process_num=1, type='ocr', use_angle_cls=True, use_dilation=False, use_gpu=True, use_mp=False, use_npu=False, use_onnx=False, use_pdf2docx_api=False, use_pdserving=False, use_space_char=True, use_tensorrt=False, use_visual_backbone=True, use_xpu=False, vis_font_path='./doc/fonts/simfang.ttf', warmup=False)
[2023/06/30 11:32:32] ppocr INFO: **********./test_image/t1.jpg**********


--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
No stack trace in paddle, may be caused by external reasons.

----------------------
Error Message Summary:
----------------------
FatalError: `Segmentation fault` is detected by the operating system.
  [TimeInfo: *** Aborted at 1688095953 (unix time) try "date -d @1688095953" if you are using GNU date ***]
  [SignalInfo: *** SIGSEGV (@0x0) received by PID 20279 (TID 0x7fc7e77e1740) from PID 0 ***]

段错误(吐核)

**Comment by lipeng1109** [comment]
我也是出现相同的错误，使用paddlepaddle-gpu==2.4.2.post11.6出现：OSError: (External) CUBLAS error(7).
  [Hint: Please search for the error code(7) on website (https://docs.nvidia.com/cuda/cublas/index.html#cublasstatus_t) to get Nvidia's official solution and advice about CUBLAS Error.] (at /paddle/paddle/phi/backends/gpu/gpu_context.cc:593)

**Comment by lipeng1109** [comment]
可以正常推理的环境：
我在T4机器上单独安装paddlepaddle-gpu==2.4.2.post11.6，没有安装cudatools包，环境可以正常推理，基础镜像使用的是英伟达官方的pytorch镜像21.09，对应torch为1.10.0a0+3fd9dcf

不可以推理的环境：在V100机器上构建了环境，因为是无法连接外网，构建使用的清华镜像源，安装使用官方建议的方式，就出现了user_gpu=True不能推理，包上面的错误：OSError: (External) CUBLAS error(7).
使用user_gpu=False可以推理

**Comment by BrownTen** [comment]
同样的问题，我也有看到其他issues有这样的问题，都没有人回答正解吗。。太难受了。
